"""`libero_goal` — LIBERO-Goal's ten tasks as ONE compile unit. L2.

    families/libero_goal.family      GENERATED by tools/tasks/gen_libero_family.mojo
    scenes/libero_goal.xml           composed from it (GENERATED, gen-family-scenes)
    libero_goal_dims.mojo            read off MuJoCo (GENERATED, gen-dims, CI-checked)
    THIS FILE                        the comptime model def

The base is robosuite's Panda + PandaGripper + RethinkMount
(`envs/robots/assets/panda_robosuite.xml`, vendored by
`tools/robots/vendor_panda_robosuite.py`) at LIBERO's `base_pos`; slot 0 is
the styled tabletop arena; then three static fixtures (wooden cabinet with
three slide joints, flat stove with its button hinge, wine rack) and four
free objects (bowl, cream cheese, wine bottle, plate).

⚠ `cone_type` IS ELLIPTIC, NOT PYRAMIDAL. robosuite's `base.xml` sets
`cone="elliptic" impratio="20"` and the composed scene inherits that
`<option>` (`inherit_option=1`). The SO-101 family runs pyramidal; this one
must not, or the friction model differs from the benchmark's.

⚠⚠ `max_contacts` WAS 64 AND THE SCENE NEEDS 112 — MEASURED, NOW GENERATED.
Every prop landing at reset touches the table with all its collision boxes at
once: 112 contacts, on every task, on all fifty frozen inits, and MuJoCo counts
the same 112 at the same substep (`tools/tasks/libero_contact_budget.mojo`).
The batched env truncates at the cap SILENTLY, so for its whole life until this
the landing ran on a truncated contact set. The budget is
`libero_envs/budgets.LIBERO_GOAL_MAX_CONTACTS`, from that measurement and the
rule in `tools/tasks/gen_libero_envs.mojo`.
"""

from noeira.physics3d.parser import ModelDefFromXML
from noeira.physics3d.types import ConeType
from noeira.tasks.libero_goal_dims import LIBERO_GOAL_DIMS
from noeira.tasks.libero_envs.budgets import LIBERO_GOAL_MAX_CONTACTS

comptime _pm = LIBERO_GOAL_DIMS

comptime LIBERO_GOAL_N_FREE_SLOTS: Int = 4
comptime LIBERO_GOAL_N_GOAL_WORDS: Int = 9
comptime LIBERO_GOAL_OBS_DIM: Int = (
    _pm.NQ + _pm.NV + LIBERO_GOAL_N_FREE_SLOTS + LIBERO_GOAL_N_GOAL_WORDS
)
"""`qpos`, `qvel`, one active word per free slot, nine goal words — the layout
`tasks/task_hooks.write_task_obs` writes.

⚠⚠ IT WAS `NQ + NV` WHILE NOTHING FILLED THE REST, AND IT GREW IN THE COMMIT
THAT FILLS IT. Declaring a width nothing writes is a policy input that is
always zero; `tests/tasks/test_libero_task_hooks.mojo` asserts this equals
`NQ + NV + LiberoGoalPlacement.N_FREE + TASK_GOAL_WORDS`, so the four literals
above cannot drift from the table and the hook."""

comptime LiberoGoalModel = ModelDefFromXML[
    xml_path="noeira/tasks/scenes/libero_goal.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    nsensor=_pm.NSENSOR, nsensordata=_pm.NSENSORDATA,
    neq=_pm.NEQ,
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    cone_type=ConeType.ELLIPTIC,
    # ⚠⚠ THE SCENE'S OWN MAX CONDIM (4: robosuite's finger pads), NOT THE
    # DEFAULT 3. Without it the batched solver clamps every finger-pad contact
    # to condim 3 and drops its TORSIONAL row — while the CPU replay leg
    # (`StudioIntegEll`, built at MAX_CONDIM 6) keeps it, so batch and CPU
    # disagreed on every grasp. Found by the blocked-solver work (§13.54).
    max_condim=_pm.MAX_CONDIM,
    max_contacts=LIBERO_GOAL_MAX_CONTACTS,
    obs_dim_override=LIBERO_GOAL_OBS_DIM,
    # ⚠⚠ SEVEN, NOT THE NINE ACTUATORS. LIBERO's policy emits OSC_POSE's
    # action — six end-effector pose deltas and one gripper word — and
    # `Phyics3dEnvConfig.HAS_OSC_CONTROLLER` maps it onto the model's nine
    # actuator commands. This said 9 while nothing drove the model; a config
    # with the controller on `constrained`s on it being 7, so the two cannot
    # drift apart silently.
    action_dim_override=7,
]
