"""Oriented-plane narrow phase vs MuJoCo — the gate the 2026-08-01 fix never had.

WHY THIS EXISTS, AND WHY IT IS NOT A REGRESSION TEST.

Until 2026-08-01 every plane narrow phase reduced the plane to `ground_z =
<the plane geom's world z>` and hardcoded the contact normal to `(0, 0, 1)`, so
a plane was modelled as a HORIZONTAL FLOOR AT THE HEIGHT OF ITS ORIGIN however
it actually faced. `collision/plane_frame.mojo` fixed that by rebasing the
whole computation into the plane's own frame, and the fix has been live in both
`contact_detection.mojo` and `broadphase_sap.mojo` ever since.

**Nothing has ever checked it.** Every plane in every physics3d test is
`type="plane" pos="0 0 0"` with no rotation, and `plane_frame.mojo`'s own
docstring states that for an identity plane quaternion the new arithmetic
reduces to the old BIT FOR BIT. So all 78 tests that ran green alongside the
fix would have run green without it — they are the axis-aligned control, and
they cannot be anything else. The "zero regressions" recorded when the fix
landed is a true statement that carries no information about correctness.

This is the same shape as the touch-sensor ray inversion, which survived hopper,
finger AND manipulator for a month because every gated contact was inside its
zone and only a contact OUTSIDE it discriminates. A fix needs a pose that can
EXPRESS the defect.

THE MODEL is built to make every component wrong under the old rule:

  * the plane's normal is (0.3149, -0.4949, 0.8099) — no axis dominates, so a
    hardcoded (0,0,1) is wrong in all three components, and a sign error in any
    one of them is visible;
  * the plane's origin is (0.1, -0.2, 0.3), NOT the world origin, so
    `ground_z = wpz[plane]` would be 0.3 while the true contact heights run
    from +0.30 down to -0.35;
  * the five test geoms sit at world z from +0.34 to -0.35, i.e. on BOTH sides
    of the old rule's phantom floor. Under the old code some of these pairs
    report no contact at all and others report a deep one.

WHAT IS COMPARED — all FOUR parts of the contact record, per the standing
invariant in docs/DM_CONTROL_PORT.md: bodies, depth, normal, POSITION. Three
separate bugs (39 count, 40 point, 43 position) have been found where some
parts were right and others wrong, and two of them survived a passing gate that
compared only the other three. Contact COUNT is compared too, per pair.

Both entry points are gated: `detect_contacts` (naive, all-pairs) and
`detect_contacts_sap` (the broadphase), which are separate implementations of
the plane branch — `broadphase_sap.mojo` has five `from_plane_frame` call sites
of its own.

ALL FIVE GEOM TYPES ARE GATED EXACTLY. The cylinder was the last holdout: it
emitted ONE point against `mjc_PlaneCylinder`'s manifold until 2026-08-03, and
was pinned here by a self-cleaning test that failed with its own cleanup
instructions the moment the manifold landed. That test is gone and the cylinder
now sits in the exact set with the other four.

⚠ NOT COVERED: plane/mesh. The plane-mesh vertex scan takes the same
`ground_z`, but a mesh needs an STL asset the synthetic model here has no way
to carry. It remains ungated.

Run: pixi run mojo run -I . tests/physics3d/test_oriented_plane_vs_mujoco.mojo
"""

from std.math import abs, sqrt
from std.python import Python, PythonObject
from std.testing import assert_true, TestSuite
from max.gpu.host import DeviceContext

from mojo_rl.physics3d.parser import parse_xml, ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.physics3d.fields import Data, Model, Dims
from mojo_rl.physics3d.kinematics.forward_kinematics import forward_kinematics
from mojo_rl.physics3d.collision.contact_detection import detect_contacts
from mojo_rl.physics3d.collision.broadphase_sap import detect_contacts_sap
from mojo_rl.physics3d.gpu.constants import (
    CONTACT_SIZE,
    META_IDX_NUM_CONTACTS,
    CONTACT_IDX_BODY_A,
    CONTACT_IDX_BODY_B,
    CONTACT_IDX_POS_X,
    CONTACT_IDX_POS_Y,
    CONTACT_IDX_POS_Z,
    CONTACT_IDX_NX,
    CONTACT_IDX_NY,
    CONTACT_IDX_NZ,
    CONTACT_IDX_DIST,
)


comptime DTYPE = DType.float64

# Generated by a script that computes the plane frame and places each geom to
# penetrate by exactly 5 mm along the plane NORMAL — see the module docstring
# for why the orientation and origin are what they are. The long literals are
# the exact doubles MuJoCo compiles; rounding them would move the penetration
# off 5 mm and make every tolerance below a guess.
comptime PLANE_XML = """
<mujoco model="oriented_plane">
  <option timestep="0.002" gravity="0 0 0"/>
  <default>
    <geom friction="1 0.005 0.0001" solimp="0.9 0.95 0.001" solref="0.02 1"/>
  </default>
  <worldbody>
    <geom name="tilted" type="plane" size="5 5 .1" pos="0.1 -0.2 0.3" quat="0.9512776374956277 0.260130890407222 0.16553783935005031 -0.0"/>
    <body name="b_sph" pos="0.1141725200259742 -0.22227110289795948 0.33644362292393365" quat="0.9512776374956277 0.260130890407222 0.16553783935005031 -0.0">
      <joint name="j_sph" type="slide" axis="0.3149448894660932 -0.4949133977324323 0.8098582871985256"/>
      <geom name="g_sph" type="sphere" size=".05"/>
    </body>
    <body name="b_cap" pos="0.5836202948746302 -0.1742604633744189 0.17087259531890178" quat="0.9512776374956277 0.260130890407222 0.16553783935005031 -0.0">
      <joint name="j_cap" type="slide" axis="0.3149448894660932 -0.4949133977324323 0.8098582871985256"/>
      <geom name="g_cap" type="capsule" size=".04" fromto="-.06 0 0 .06 0 0"/>
    </body>
    <body name="b_box" pos="1.059366967512608 -0.13614809180552695 0.021498733457840417" quat="0.9512776374956277 0.260130890407222 0.16553783935005031 -0.0">
      <joint name="j_box" type="slide" axis="0.3149448894660932 -0.4949133977324323 0.8098582871985256"/>
      <geom name="g_box" type="box" size=".05 .05 .05"/>
    </body>
    <body name="b_ell" pos="1.531964191255925 -0.0930865862593107 -0.1359737112752062" quat="0.9512776374956277 0.260130890407222 0.16553783935005031 -0.0">
      <joint name="j_ell" type="slide" axis="0.3149448894660932 -0.4949133977324323 0.8098582871985256"/>
      <geom name="g_ell" type="ellipsoid" size=".06 .045 .05"/>
    </body>
    <body name="b_cyl" pos="2.001411966104581 -0.0450759467357701 -0.3015447388802381" quat="0.9512776374956277 0.260130890407222 0.16553783935005031 -0.0">
      <joint name="j_cyl" type="slide" axis="0.3149448894660932 -0.4949133977324323 0.8098582871985256"/>
      <geom name="g_cyl" type="cylinder" size=".05 .04"/>
    </body>
  </worldbody>
</mujoco>
"""

comptime pp = parse_xml(PLANE_XML)
comptime PM = ModelDefFromXML[
    xml=PLANE_XML,
    nbody=pp.NBODY, njoint=pp.NJOINT, nq=pp.NQ, nv=pp.NV,
    ngeom=pp.NGEOM, nact=pp.NACT, ntex=pp.NTEX, nmat=pp.NMAT,
    nlight=pp.NLIGHT, ncam=pp.NCAM, nsite=pp.NSITE,
    max_tendon=pp.NTENDON,
    cone_type=ConeType.PYRAMIDAL,
    max_contacts=64,
    obs_dim_override=1,
    obs_qpos_skip=0,
    timestep=pp.TIMESTEP,
]

comptime NGEOM = PM.NGEOM
comptime NBODY = PM.NBODY
comptime MC = PM.MAX_CONTACTS

# Every geom penetrates by exactly this, by construction.
comptime DEPTH: Float64 = 0.005

# Both sides read the same decimal literals and MuJoCo's plane arithmetic is
# the one we transcribed, so these are rounding budgets, not modelling ones.
comptime TOL_DIST: Float64 = 1e-12
comptime TOL_NORMAL: Float64 = 1e-12
comptime TOL_POS: Float64 = 1e-9

comptime Dat = Data[DTYPE, PM.NQ, PM.NV, NBODY, MC, PM.NSITE, 1]
comptime Mod = Model[DTYPE, Dims[nv=PM.NV, nbody=NBODY, njoint=PM.NJOINT, ngeom=NGEOM, nequality=PM.MAX_EQUALITY, ntendon=PM.MAX_TENDON, nsite=PM.NSITE, nexclude=PM.NEXCLUDE, nmesh_verts=0]]


def _names() -> List[String]:
    return [
        String("sphere"), String("capsule"), String("box"),
        String("ellipsoid"), String("cylinder"),
    ]


def _build() raises -> Mod:
    var ctx = DeviceContext()
    var mf = Mod()
    PM.init_fields[DTYPE, 0](ctx, mf)
    return mf^


def _check(mut d: Dat, mf: Mod, label: String) raises:
    """Compare our contact SET against MuJoCo's, per test body, all four parts.

    Matching is by POSITION (nearest MuJoCo point for each of ours) rather than
    by index: both engines emit manifolds whose point ORDER is decided by the
    last bits of the rotation, so an index-wise comparison would report an
    ordering difference as a geometry error.
    """
    var mujoco = Python.import_module("mujoco")
    var m = mujoco.MjModel.from_xml_string(materialize[PLANE_XML]())
    var md = mujoco.MjData(m)
    mujoco.mj_forward(m, md)

    var names = _names()
    var n_ours = Int(d.meta.data[META_IDX_NUM_CONTACTS])
    var n_mj = Int(py=md.ncon)
    print("  [" + label + "] contacts: ours", n_ours, " MuJoCo", n_mj)

    assert_true(
        n_ours > 0,
        label + ": we emit NO contacts against the tilted plane. Under the"
        " pre-2026-08-01 rule (floor at the origin's z, normal (0,0,1)) that is"
        " exactly what several of these pairs produce.",
    )

    var per_body_ours = List[Int]()
    var per_body_mj = List[Int]()
    for _ in range(NBODY):
        per_body_ours.append(0)
        per_body_mj.append(0)

    for k in range(n_mj):
        var cc = md.contact[k]
        var q1 = Int(py=m.geom_bodyid[cc.geom1])
        var q2 = Int(py=m.geom_bodyid[cc.geom2])
        var other = q1 if q2 == 0 else q2
        per_body_mj[other] = per_body_mj[other] + 1

    # Dump BOTH sides before asserting. A contact-set mismatch is only
    # diagnosable next to the rows themselves.
    print("    OURS:")
    for c in range(n_ours):
        var b = c * CONTACT_SIZE
        print("      a", Int(d.contacts.data[b + CONTACT_IDX_BODY_A]),
              "b", Int(d.contacts.data[b + CONTACT_IDX_BODY_B]),
              " dist", Float64(d.contacts.data[b + CONTACT_IDX_DIST]),
              " n [", Float64(d.contacts.data[b + CONTACT_IDX_NX]),
              Float64(d.contacts.data[b + CONTACT_IDX_NY]),
              Float64(d.contacts.data[b + CONTACT_IDX_NZ]),
              "]  pos [", Float64(d.contacts.data[b + CONTACT_IDX_POS_X]),
              Float64(d.contacts.data[b + CONTACT_IDX_POS_Y]),
              Float64(d.contacts.data[b + CONTACT_IDX_POS_Z]), "]")
    print("    MuJoCo:")
    for k in range(n_mj):
        var cc = md.contact[k]
        print("      g", Int(py=cc.geom1), Int(py=cc.geom2),
              " dist", Float64(py=cc.dist),
              " n [", Float64(py=cc.frame[0]), Float64(py=cc.frame[1]),
              Float64(py=cc.frame[2]),
              "]  pos [", Float64(py=cc.pos[0]), Float64(py=cc.pos[1]),
              Float64(py=cc.pos[2]), "]")

    var worst_dist = Float64(0)
    var worst_norm = Float64(0)
    var worst_pos = Float64(0)

    for c in range(n_ours):
        var b = c * CONTACT_SIZE
        var ba = Int(d.contacts.data[b + CONTACT_IDX_BODY_A])
        var bb = Int(d.contacts.data[b + CONTACT_IDX_BODY_B])
        var px = Float64(d.contacts.data[b + CONTACT_IDX_POS_X])
        var py_ = Float64(d.contacts.data[b + CONTACT_IDX_POS_Y])
        var pz = Float64(d.contacts.data[b + CONTACT_IDX_POS_Z])
        var nx = Float64(d.contacts.data[b + CONTACT_IDX_NX])
        var ny = Float64(d.contacts.data[b + CONTACT_IDX_NY])
        var nz = Float64(d.contacts.data[b + CONTACT_IDX_NZ])
        var dist = Float64(d.contacts.data[b + CONTACT_IDX_DIST])

        # PART 1 — BODIES. One side must be the world (the plane), the other a
        # test body. A plane contact naming two dynamic bodies is a broadphase
        # error, not a narrow-phase one.
        #
        # ⚠ THE WORLD BODY ID IS 0 IN THE NAIVE PATH AND -1 IN THE SAP PATH.
        # That is a documented, deliberate difference — `_plane_box_contacts`
        # takes it as an argument precisely because hardcoding either would
        # silently change one path (DM_CONTROL_PORT.md, entry (ag)). A test
        # that assumes 0 fails on SAP for a reason that is not a defect, which
        # is what the first run of this file did.
        var a_world = (ba == 0 or ba == -1)
        var b_world = (bb == 0 or bb == -1)
        var other = ba if b_world else bb
        assert_true(
            a_world != b_world,
            label + ": plane contact does not name the world body exactly once"
            " (a=" + String(ba) + ", b=" + String(bb) + ")",
        )
        assert_true(
            other >= 1 and other <= 5,
            label + ": contact names an unexpected body " + String(other),
        )
        per_body_ours[other] = per_body_ours[other] + 1
        var nm = names[other - 1]

        # PART 2 — DEPTH. Every geom is placed to penetrate by exactly DEPTH,
        # so this is checked against BOTH MuJoCo and the construction. The
        # second check is what catches the two engines agreeing on a wrong
        # answer, which a MuJoCo-only comparison cannot.
        assert_true(
            abs(dist + DEPTH) <= 1e-9,
            label + " " + nm + ": depth " + String(dist) + " is not the -5 mm"
            " the model was built to produce",
        )

        # PART 4 — POSITION, matched to the nearest MuJoCo point on the same
        # body, and PART 3 — NORMAL, taken from that same point.
        var best = Float64(1e18)
        var mj_d = Float64(0)
        var mj_n0 = Float64(0)
        var mj_n1 = Float64(0)
        var mj_n2 = Float64(0)
        var mj_b1 = -1
        var mj_b2 = -1
        for k in range(n_mj):
            var cc = md.contact[k]
            var q1 = Int(py=m.geom_bodyid[cc.geom1])
            var q2 = Int(py=m.geom_bodyid[cc.geom2])
            if q1 != other and q2 != other:
                continue
            var dx = px - Float64(py=cc.pos[0])
            var dy = py_ - Float64(py=cc.pos[1])
            var dz = pz - Float64(py=cc.pos[2])
            var r = sqrt(dx * dx + dy * dy + dz * dz)
            if r < best:
                best = r
                mj_d = Float64(py=cc.dist)
                mj_n0 = Float64(py=cc.frame[0])
                mj_n1 = Float64(py=cc.frame[1])
                mj_n2 = Float64(py=cc.frame[2])
                mj_b1 = q1
                mj_b2 = q2
        assert_true(
            mj_b1 >= 0,
            label + " " + nm + ": we emit a contact MuJoCo has no counterpart"
            " for on that body",
        )
        if best > worst_pos:
            worst_pos = best

        var dd = abs(dist - mj_d)
        if dd > worst_dist:
            worst_dist = dd

        # THE DIRECTION INVARIANT. Ours points body_b -> body_a; MuJoCo's
        # geom1 -> geom2. The SIGN is predicted from the body labels, which is
        # what makes this a direction check rather than a magnitude one.
        #
        # ⚠ NORMALISE THE WORLD ID FIRST. SAP writes -1 for the world and
        # MuJoCo uses 0, so comparing the raw labels makes `expect_same` false
        # on every SAP plane contact and reports a perfectly correct normal as
        # off by 2.0. The first run of this file did exactly that, and the
        # printed vectors were IDENTICAL beside the failure message — which is
        # the tell that the predicate, not the normal, was wrong.
        var ba_n = 0 if ba == -1 else ba
        var bb_n = 0 if bb == -1 else bb
        var expect_same = (mj_b1 == bb_n and mj_b2 == ba_n)
        var sgn = Float64(1.0) if expect_same else Float64(-1.0)
        var e = max(
            abs(nx - sgn * mj_n0),
            max(abs(ny - sgn * mj_n1), abs(nz - sgn * mj_n2)),
        )
        if e > worst_norm:
            worst_norm = e

        assert_true(
            dd <= TOL_DIST,
            label + " " + nm + ": dist diverges from MuJoCo by " + String(dd),
        )
        assert_true(
            e <= TOL_NORMAL,
            label + " " + nm + ": CONTACT NORMAL diverges from MuJoCo by "
            + String(e) + ". Ours (" + String(nx) + ", " + String(ny) + ", "
            + String(nz) + ") vs MuJoCo's (" + String(mj_n0) + ", "
            + String(mj_n1) + ", " + String(mj_n2) + "). A normal of (0,0,1)"
            " here means the plane's orientation is being ignored.",
        )
        assert_true(
            best <= TOL_POS,
            label + " " + nm + ": contact POSITION is " + String(best)
            + " from MuJoCo's nearest point on the same body. Depth and normal"
            " can both be right while the point is wrong — that was bug 43, and"
            " it cost stacker 0.15-0.41 relative qacc error.",
        )

    # PART 1b — the contact COUNT per pair. `mjc_PlaneBox` emits up to four
    # points and `mjc_PlaneCapsule` two, so a single-point answer here is the
    # manifold defect (bug 39) reappearing on the plane branch.
    print("    per-body contacts (ours vs MuJoCo):")
    for i in range(1, 6):
        print("      ", names[i - 1], per_body_ours[i], "vs", per_body_mj[i])
    for i in range(1, 6):
        assert_true(
            per_body_ours[i] == per_body_mj[i],
            label + " " + names[i - 1] + ": we emit "
            + String(per_body_ours[i]) + " contacts where MuJoCo emits "
            + String(per_body_mj[i]),
        )
    # The ellipsoid is the reason this file exists in its current form: until
    # 2026-08-03 `broadphase_sap.mojo` had no ELLIPSOID branch at all, so this
    # count was 0 on the SAP path while the naive path reported 1.
    assert_true(
        per_body_ours[4] == 1,
        label + ": the ellipsoid produces no contact. If this is the SAP path,"
        " the GEOM_ELLIPSOID branch has been lost again — every ellipsoid in"
        " any model with NGEOM >= 16 then falls through the plane silently.",
    )

    print("    worst: dist", worst_dist, " normal", worst_norm,
          " position", worst_pos)


def test_oriented_plane_naive_narrow_phase() raises:
    """`detect_contacts` — the all-pairs path."""
    var sf = PM.make_spec_fields[DTYPE]()
    print("--- oriented plane: detect_contacts ---")
    var mf = _build()
    var d = Dat()
    PM.reset_data(sf, d)
    forward_kinematics["cpu"](d, mf)
    detect_contacts["cpu"](d, mf)
    _check(d, mf, String("naive"))


def test_oriented_plane_sap_broadphase() raises:
    """`detect_contacts_sap` — a SEPARATE implementation of the plane branch.

    `broadphase_sap.mojo` carries five `from_plane_frame` call sites of its own;
    a fix applied to one file and not the other is the shape of the two-parser
    bug this project has hit repeatedly.
    """
    var sf = PM.make_spec_fields[DTYPE]()
    print("--- oriented plane: detect_contacts_sap ---")
    var mf = _build()
    var d = Dat()
    PM.reset_data(sf, d)
    forward_kinematics["cpu"](d, mf)
    detect_contacts_sap["cpu"](d, mf)
    _check(d, mf, String("sap"))


def test_the_plane_is_actually_oriented() raises:
    """Non-vacuity: this model must be able to EXPRESS the defect.

    If the plane's normal ever became axis-aligned, or its origin moved to the
    world origin, every assertion above would still pass while testing exactly
    what the 78 pre-existing tests already test. That is the failure mode this
    whole file exists to close, so it is asserted rather than assumed.
    """
    var mujoco = Python.import_module("mujoco")
    var m = mujoco.MjModel.from_xml_string(materialize[PLANE_XML]())
    var md = mujoco.MjData(m)
    mujoco.mj_forward(m, md)

    var n0 = Float64(py=md.contact[0].frame[0])
    var n1 = Float64(py=md.contact[0].frame[1])
    var n2 = Float64(py=md.contact[0].frame[2])
    print("--- non-vacuity: plane normal =", n0, n1, n2)
    assert_true(
        abs(n0) > 0.2 and abs(n1) > 0.2 and abs(n2) > 0.2,
        "the plane normal has become near-axis-aligned — this file no longer"
        " discriminates the oriented-plane fix from the code it replaced",
    )

    # The old rule read the plane's origin z (0.3) as the floor height. The
    # test geoms must straddle it, or 'a floor at 0.3' would be a harmless
    # approximation for all of them.
    var lo = Float64(1e18)
    var hi = Float64(-1e18)
    for b in range(1, 6):
        var z = Float64(py=md.xpos[b][2])
        if z < lo:
            lo = z
        if z > hi:
            hi = z
    print("    test-body world z spans", lo, "..", hi,
          " against the plane origin's z = 0.3")
    assert_true(
        lo < 0.3 and hi > 0.3,
        "the test geoms no longer straddle the plane origin's z, so the old"
        " 'floor at ground_z' rule would not be grossly wrong for them",
    )


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
