"""MESH x {BOX, MESH} contact MANIFOLDS against MuJoCo — the native-CCD gap.

WHAT THIS GATES. `mjc_Convex` gives a mesh pair up to FOUR contact points, not
one. It does it by an entirely different route from the perturbation loop in
`collision/multi_ccd.mojo`: `maxContacts` (`engine_collision_convex.c:843`)
returns 4 when BOTH geoms are box-or-mesh, which takes an EARLY RETURN past the
perturbation loop into `multicontact()` (`engine_collision_gjk.c:2111`). That
routine reads the EPA witness face, recovers the polygon on each geom that the
face came from, and CLIPS one against the other. A single point cannot hold a
flat contact — the body rotates about it and sinks — so this is the difference
between a mesh resting on a table and a mesh pivoting on a corner.

⚠ BOX x BOX IS NOT IN SCOPE HERE AND IS NOT MISSING. MuJoCo dispatches it to
`mjc_BoxBox`, not `mjc_Convex` (`engine_collision_driver.c:53`), and our port of
that primitive is exact: `test_box_box_sweep` matches all 571 manifold points
across 400 poses. A note in the constraint-sequencing arc recorded "box-box
ncon 2 vs 4" as evidence of a multicontact gap; that attribution was wrong, and
the sweep is the reason to believe this one instead.

⚠ MESH x {CYLINDER, CAPSULE} IS ALSO NOT IN SCOPE. Only ONE of those geoms is
box-or-mesh, so `maxContacts` returns 1 and they reach the perturbation loop —
which is ported and gated by `test_narrow_phase_pairs`. The split is by geom
TYPE, and getting it wrong in either direction has already cost this repo two
rewrites; see the docstring of `collision/multi_ccd.mojo`.

THE FIXTURES. `mc_cube.stl` (6 quads) and `mc_hex.stl` (2 hexagons + 6 quads)
are generated by `assets/make_multicontact_meshes.py`, which explains why their
extents are what they are — MuJoCo re-frames a mesh to its principal axes, so a
carelessly shaped fixture comes back rotated and every local-frame comparison
becomes meaningless. `test_mesh_frames_are_identity` asserts that has not
happened, so the rest of this file can be trusted.

Run: pixi run mojo run -I . tests/physics3d/test_mesh_manifold_vs_mujoco.mojo
"""

from std.math import abs, sqrt, sin, cos
from std.python import Python, PythonObject
from std.testing import assert_true, TestSuite
from max.gpu.host import DeviceContext

from mojo_rl.physics3d.parser import parse_xml, ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.physics3d.fields import Data, Model
from mojo_rl.physics3d.kinematics.forward_kinematics import forward_kinematics
from mojo_rl.physics3d.collision.contact_detection import detect_contacts
from mojo_rl.physics3d.collision.native_multicontact import MC_ENABLED
from mojo_rl.physics3d.gpu.constants import (
    CONTACT_SIZE,
    META_IDX_NUM_CONTACTS,
    CONTACT_IDX_BODY_A,
    CONTACT_IDX_BODY_B,
    CONTACT_IDX_POS_X,
    CONTACT_IDX_POS_Y,
    CONTACT_IDX_POS_Z,
    CONTACT_IDX_NX,
    CONTACT_IDX_NY,
    CONTACT_IDX_NZ,
    CONTACT_IDX_DIST,
)


comptime DTYPE = DType.float64

# Five groups, 2 m apart so no group can reach another. Body A of each group is
# STATIC (no joint) and body B carries a free joint — two bodies both welded to
# the world would be filtered out by MuJoCo before the narrow phase ever runs.
#
# Both ORDERINGS of mesh/box appear, because the narrow-phase branch is chosen
# from the order the two geoms arrive in and the reversed branches are exactly
# where `feedback_contact_direction_conventions` says the bugs live.
comptime MM_XML = """
<mujoco model="mesh manifold">
  <option timestep="0.002"/>
  <asset>
    <mesh name="cube" file="tests/physics3d/assets/mc_cube.stl"/>
    <mesh name="hex" file="tests/physics3d/assets/mc_hex.stl"/>
  </asset>
  <worldbody>
    <body name="a0" pos="0 0 0.5">
      <geom name="g0a" type="mesh" mesh="cube"/>
    </body>
    <body name="b0" pos="0 0 0.5">
      <joint name="j0" type="free"/>
      <geom name="g0b" type="box" size=".05 .04 .06"/>
    </body>

    <body name="a1" pos="2 0 0.5">
      <geom name="g1a" type="box" size=".05 .04 .06"/>
    </body>
    <body name="b1" pos="2 0 0.5">
      <joint name="j1" type="free"/>
      <geom name="g1b" type="mesh" mesh="cube"/>
    </body>

    <body name="a2" pos="4 0 0.5">
      <geom name="g2a" type="mesh" mesh="cube"/>
    </body>
    <body name="b2" pos="4 0 0.5">
      <joint name="j2" type="free"/>
      <geom name="g2b" type="mesh" mesh="cube"/>
    </body>

    <body name="a3" pos="6 0 0.5">
      <geom name="g3a" type="mesh" mesh="hex"/>
    </body>
    <body name="b3" pos="6 0 0.5">
      <joint name="j3" type="free"/>
      <geom name="g3b" type="box" size=".05 .04 .06"/>
    </body>

    <body name="a4" pos="8 0 0.5">
      <geom name="g4a" type="mesh" mesh="hex"/>
    </body>
    <body name="b4" pos="8 0 0.5">
      <joint name="j4" type="free"/>
      <geom name="g4b" type="mesh" mesh="cube"/>
    </body>
  </worldbody>
</mujoco>
"""

comptime mm = parse_xml(MM_XML)
comptime MMM = ModelDefFromXML[
    xml=MM_XML,
    nbody=mm.NBODY, njoint=mm.NJOINT, nq=mm.NQ, nv=mm.NV,
    ngeom=mm.NGEOM, nact=mm.NACT, ntex=mm.NTEX, nmat=mm.NMAT,
    nlight=mm.NLIGHT, ncam=mm.NCAM, nsite=mm.NSITE,
    max_tendon=mm.NTENDON,
    cone_type=ConeType.PYRAMIDAL,
    max_contacts=64,
    obs_dim_override=1,
    obs_qpos_skip=0,
    timestep=mm.TIMESTEP,
]

comptime NQ: Int = MMM.NQ
comptime NV: Int = MMM.NV
comptime NBODY: Int = MMM.NBODY
comptime MC: Int = MMM.MAX_CONTACTS
# cube (8) + hex (12); padded so a fixture edit does not silently truncate a
# hull — `fields_build` treats an over-run as a hard error, not a warning.
comptime NMESHV: Int = 64

comptime NGROUP: Int = 5


def _group_name(g: Int) -> StaticString:
    if g == 0:
        return "mesh(cube) x box  "
    if g == 1:
        return "box x mesh(cube)  "
    if g == 2:
        return "mesh(cube) x mesh "
    if g == 3:
        return "mesh(hex)  x box  "
    return "mesh(hex)  x mesh "

comptime Dat = Data[DTYPE, NQ, NV, NBODY, MC, MMM.NSITE, 1]
comptime Mod = Model[
    DTYPE, NV, NBODY, MMM.NJOINT, MMM.NGEOM, MMM.MAX_EQUALITY, MMM.MAX_TENDON,
    MMM.NSITE, MMM.NEXCLUDE, NMESHV,
]

comptime NPOSE: Int = 160
comptime SPAN: Float64 = 0.055
comptime TOL_POS: Float64 = 1e-6
comptime TOL_DIST: Float64 = 1e-9
comptime TOL_DIR: Float64 = 1e-7


def _stack_z(g: Int) -> Float64:
    """Face-to-face separation of the two geoms of group `g` when aligned.

    ⚠ THE POSE SCHEDULE IS THE MEASUREMENT, AND UNIFORM RANDOM POSES DO NOT
    MAKE IT. The first version of this file drew a uniform random quaternion
    for every pose; over 120 poses MuJoCo emitted 123 manifold points, i.e.
    almost every contact was a VERTEX or EDGE touching a face, which is one
    point in the reference too. A sweep like that reports "3 count mismatches"
    and looks like a small gap while gating essentially nothing about the
    four-point face manifold this file exists for. Two flat faces meet only on
    a set of measure zero, so they have to be constructed, not sampled.
    """
    if g == 0:
        return 0.05 + 0.06  # cube half 0.05, box half-z 0.06
    if g == 1:
        return 0.06 + 0.05
    if g == 2:
        return 0.05 + 0.05
    if g == 3:
        return 0.08 + 0.06  # hex half-height 0.08
    return 0.08 + 0.05


struct Lcg(Copyable, Movable):
    """A fixed 64-bit LCG, so a failing pose index is reproducible."""

    var s: UInt64

    def __init__(out self, seed: UInt64):
        self.s = seed

    def next(mut self) -> Float64:
        self.s = self.s * 6364136223846793005 + 1442695040888963407
        return Float64((self.s >> 11) & 0x1FFFFFFFFFFFFF) / 9007199254740992.0

    def sym(mut self, span: Float64) -> Float64:
        return (self.next() * 2.0 - 1.0) * span


def _build() raises -> Mod:
    var ctx = DeviceContext()
    var mf = Mod()
    MMM.init_fields[DTYPE, NMESHV](ctx, mf)
    return mf^


def test_mesh_frames_are_identity() raises:
    """The fixtures must reach MuJoCo unmoved, or nothing below compares solids.

    MuJoCo's compiler translates a mesh to its centre of mass and rotates it to
    its principal inertia axes. Our loader does neither. So a fixture whose
    frame MuJoCo changes is a DIFFERENT SOLID in the two engines, and a
    manifold comparison over it would be measuring the reframing, not the
    collision. Both fixtures are shaped to make that transform the identity;
    this asserts it rather than trusting it.
    """
    var mujoco = Python.import_module("mujoco")
    var np = Python.import_module("numpy")
    var m = mujoco.MjModel.from_xml_string(String(MM_XML))
    var nmesh = Int(py=m.nmesh)
    print("--- mesh frames: nmesh =", nmesh)
    for i in range(nmesh):
        var p = m.mesh_pos[i]
        var q = m.mesh_quat[i]
        var dp = Float64(py=np.max(np.abs(p)))
        var dq = max(
            abs(Float64(py=q[0]) - 1.0),
            max(
                abs(Float64(py=q[1])),
                max(abs(Float64(py=q[2])), abs(Float64(py=q[3]))),
            ),
        )
        print("   mesh", i, " |pos| =", dp, " |quat - identity| =", dq)
        assert_true(
            dp < 1e-9 and dq < 1e-9,
            String("fixture mesh ") + String(i) + " was RE-FRAMED by MuJoCo"
            " (|pos|=" + String(dp) + " |quat-I|=" + String(dq) + ")."
            " Regenerate it with extents that keep the principal moments"
            " descending — see assets/make_multicontact_meshes.py",
        )


def test_mesh_manifold_vs_mujoco() raises:
    """Manifold point COUNT and POSITIONS, per group, over NPOSE poses."""
    print("--- mesh manifold:", NPOSE, "poses x", NGROUP, "groups")
    var mf = _build()
    var d = Dat()

    var mujoco = Python.import_module("mujoco")
    var m = mujoco.MjModel.from_xml_string(String(MM_XML))
    var dat = mujoco.MjData(m)

    var rng = Lcg(0x243F6A8885A308D3)

    # Per-group tallies, so a group that regresses is named.
    var g_both = List[Int](length=NGROUP, fill=0)
    var g_mj_pts = List[Int](length=NGROUP, fill=0)
    var g_our_pts = List[Int](length=NGROUP, fill=0)
    var g_cnt_bad = List[Int](length=NGROUP, fill=0)
    var g_worst_pos = List[Float64](length=NGROUP, fill=0.0)
    var g_worst_dist = List[Float64](length=NGROUP, fill=0.0)
    var g_worst_dir = List[Float64](length=NGROUP, fill=0.0)
    var g_mj_max = List[Int](length=NGROUP, fill=0)

    for p in range(NPOSE):
        MMM.reset_data(d)
        # One random relative pose per group, all applied in the same pass.
        for g in range(NGROUP):
            var base = Float64(g) * 2.0
            var qo = g * 7
            var px: Float64
            var py: Float64
            var pz: Float64
            var qx: Float64
            var qy: Float64
            var qz: Float64
            var qw: Float64

            # FOUR REGIMES, cycled, so each is a quarter of the sweep:
            #   0  exactly aligned, stacked      -> face/face, 4 points
            #   1  sub-degree tilt               -> face/face at the tolerance
            #                                       edge of `alignedFaces`
            #   2  a few degrees                 -> edge/face, 2 points
            #   3  uniform random                -> vertex/face, 1 point
            # Regime 3 alone is what the first version of this sweep did.
            var regime = p % 4
            if regime == 3:
                px = base + rng.sym(SPAN)
                py = rng.sym(SPAN)
                pz = 0.5 + rng.sym(SPAN)
                qx = rng.sym(1.0)
                qy = rng.sym(1.0)
                qz = rng.sym(1.0)
                qw = rng.sym(1.0)
            else:
                # Slide in the contact plane but stay stacked, so the clipped
                # polygon is a genuinely different shape each pose — full
                # overlap, partial overlap and a corner-on-corner sliver.
                var pen = 0.001 + 0.004 * rng.next()
                px = base + rng.sym(0.05)
                py = rng.sym(0.05)
                pz = 0.5 + _stack_z(g) - pen
                var ang: Float64
                if regime == 0:
                    ang = 0.0
                elif regime == 1:
                    ang = rng.sym(0.008)  # < 0.5 deg
                else:
                    ang = rng.sym(0.09)  # ~5 deg
                var ax = rng.sym(1.0)
                var ay = rng.sym(1.0)
                var az = rng.sym(1.0)
                var an = sqrt(ax * ax + ay * ay + az * az)
                if an < 1e-9:
                    ax = 1.0
                    ay = 0.0
                    az = 0.0
                    an = 1.0
                var s = sin(0.5 * ang) / an
                qw = cos(0.5 * ang)
                qx = ax * s
                qy = ay * s
                qz = az * s

            var qn = sqrt(qx * qx + qy * qy + qz * qz + qw * qw)
            if qn < 1e-6:
                qx = 0.0
                qy = 0.0
                qz = 0.0
                qw = 1.0
                qn = 1.0
            qx /= qn
            qy /= qn
            qz /= qn
            qw /= qn
            # ⚠ Free-joint qpos is (x, y, z, qw, qx, qy, qz) — MuJoCo's order,
            # NOT the (x, y, z, w) the contact records use.
            d.qpos.data[qo + 0] = Scalar[DTYPE](px)
            d.qpos.data[qo + 1] = Scalar[DTYPE](py)
            d.qpos.data[qo + 2] = Scalar[DTYPE](pz)
            d.qpos.data[qo + 3] = Scalar[DTYPE](qw)
            d.qpos.data[qo + 4] = Scalar[DTYPE](qx)
            d.qpos.data[qo + 5] = Scalar[DTYPE](qy)
            d.qpos.data[qo + 6] = Scalar[DTYPE](qz)
            dat.qpos[qo + 0] = px
            dat.qpos[qo + 1] = py
            dat.qpos[qo + 2] = pz
            dat.qpos[qo + 3] = qw
            dat.qpos[qo + 4] = qx
            dat.qpos[qo + 5] = qy
            dat.qpos[qo + 6] = qz

        forward_kinematics["cpu"](d, mf)
        detect_contacts["cpu"](d, mf)
        var nc = Int(d.meta.data[META_IDX_NUM_CONTACTS])

        for i in range(NV):
            dat.qvel[i] = 0.0
        mujoco.mj_forward(m, dat)
        var mjn = Int(py=dat.ncon)

        for g in range(NGROUP):
            # Group g owns bodies 2g+1 (static A) and 2g+2 (free B).
            var ba_id = 2 * g + 1
            var bb_id = 2 * g + 2

            # ---- MuJoCo's points for this group
            var mj_idx = List[Int]()
            for k in range(mjn):
                var c = dat.contact[k]
                var b1 = Int(py=m.geom_bodyid[c.geom1])
                var b2 = Int(py=m.geom_bodyid[c.geom2])
                if (b1 == ba_id and b2 == bb_id) or (
                    b1 == bb_id and b2 == ba_id
                ):
                    mj_idx.append(k)

            # ---- ours
            var our_idx = List[Int]()
            for k in range(nc):
                var o = k * CONTACT_SIZE
                var b1 = Int(d.contacts.data[o + CONTACT_IDX_BODY_A])
                var b2 = Int(d.contacts.data[o + CONTACT_IDX_BODY_B])
                if (b1 == ba_id and b2 == bb_id) or (
                    b1 == bb_id and b2 == ba_id
                ):
                    our_idx.append(k)

            if len(mj_idx) == 0 or len(our_idx) == 0:
                continue
            g_both[g] += 1
            g_mj_pts[g] += len(mj_idx)
            g_our_pts[g] += len(our_idx)
            if len(mj_idx) > g_mj_max[g]:
                g_mj_max[g] = len(mj_idx)
            if len(mj_idx) != len(our_idx):
                g_cnt_bad[g] += 1

            # Deepest-point depth and normal, which are shared by every point
            # of a MuJoCo manifold and so are comparable even when the counts
            # disagree. Compared as SETS via nearest neighbour: the two engines
            # have no reason to emit a manifold in the same order.
            var mj_best = mj_idx[0]
            var mj_bd = Float64(py=dat.contact[mj_idx[0]].dist)
            for t in range(1, len(mj_idx)):
                var dk = Float64(py=dat.contact[mj_idx[t]].dist)
                if dk < mj_bd:
                    mj_bd = dk
                    mj_best = mj_idx[t]
            var our_best = our_idx[0]
            var our_bd = Float64(
                d.contacts.data[our_idx[0] * CONTACT_SIZE + CONTACT_IDX_DIST]
            )
            for t in range(1, len(our_idx)):
                var dk = Float64(
                    d.contacts.data[
                        our_idx[t] * CONTACT_SIZE + CONTACT_IDX_DIST
                    ]
                )
                if dk < our_bd:
                    our_bd = dk
                    our_best = our_idx[t]

            var dd = abs(our_bd - mj_bd)
            if dd > g_worst_dist[g]:
                g_worst_dist[g] = dd

            var con = dat.contact[mj_best]
            var o_off = our_best * CONTACT_SIZE
            var ourA = Int(d.contacts.data[o_off + CONTACT_IDX_BODY_A])
            var ourB = Int(d.contacts.data[o_off + CONTACT_IDX_BODY_B])
            var mb1 = Int(py=m.geom_bodyid[con.geom1])
            var mb2 = Int(py=m.geom_bodyid[con.geom2])
            var sgn = 1.0 if (mb1 == ourB and mb2 == ourA) else -1.0
            var e = max(
                abs(Float64(d.contacts.data[o_off + CONTACT_IDX_NX])
                    - sgn * Float64(py=con.frame[0])),
                max(
                    abs(Float64(d.contacts.data[o_off + CONTACT_IDX_NY])
                        - sgn * Float64(py=con.frame[1])),
                    abs(Float64(d.contacts.data[o_off + CONTACT_IDX_NZ])
                        - sgn * Float64(py=con.frame[2])),
                ),
            )
            if e > g_worst_dir[g]:
                g_worst_dir[g] = e

            # Hausdorff: every MuJoCo point must have one of ours near it.
            for t in range(len(mj_idx)):
                var mc = dat.contact[mj_idx[t]]
                var mx = Float64(py=mc.pos[0])
                var my = Float64(py=mc.pos[1])
                var mz = Float64(py=mc.pos[2])
                var nearest = Float64(1e30)
                for u in range(len(our_idx)):
                    var oo = our_idx[u] * CONTACT_SIZE
                    var ex = Float64(d.contacts.data[oo + CONTACT_IDX_POS_X]) - mx
                    var ey = Float64(d.contacts.data[oo + CONTACT_IDX_POS_Y]) - my
                    var ez = Float64(d.contacts.data[oo + CONTACT_IDX_POS_Z]) - mz
                    var dist = sqrt(ex * ex + ey * ey + ez * ez)
                    if dist < nearest:
                        nearest = dist
                if nearest > g_worst_pos[g]:
                    g_worst_pos[g] = nearest

    print(
        "  group                  poses  MuJoCo pts  ours  cnt!=  maxMJ "
        " worst|dpos|   worst|ddist|  worst|dn|"
    )
    var tot_cnt_bad = 0
    var worst_pos_all = Float64(0)
    var worst_dist_all = Float64(0)
    var worst_dir_all = Float64(0)
    for g in range(NGROUP):
        print(
            "  ", _group_name(g), g_both[g], "   ", g_mj_pts[g], "  ",
            g_our_pts[g], "  ", g_cnt_bad[g], "  ", g_mj_max[g], "  ",
            g_worst_pos[g], " ", g_worst_dist[g], " ", g_worst_dir[g],
        )
        tot_cnt_bad += g_cnt_bad[g]
        if g_worst_pos[g] > worst_pos_all:
            worst_pos_all = g_worst_pos[g]
        if g_worst_dist[g] > worst_dist_all:
            worst_dist_all = g_worst_dist[g]
        if g_worst_dir[g] > worst_dir_all:
            worst_dir_all = g_worst_dir[g]

    for g in range(NGROUP):
        assert_true(
            g_both[g] >= NPOSE / 8,
            String("group ") + String(g) + " produced a contact in both"
            " engines on only " + String(g_both[g]) + " of " + String(NPOSE)
            + " poses — it gates almost nothing",
        )

    # DEPTH is asserted unconditionally: EPA already matches MuJoCo to 1e-16
    # on every group, and it must not regress while the manifold work goes on.
    assert_true(
        worst_dist_all <= TOL_DIST,
        String("mesh contact DEPTH diverges from MuJoCo by ")
        + String(worst_dist_all),
    )

    # ⚠ THE MANIFOLD ASSERTIONS TRACK `MC_ENABLED` ON PURPOSE. The native
    # `multicontact()` path is committed switched OFF because it is not correct
    # yet (see `collision/native_multicontact.mojo`), so with the flag down this
    # file MEASURES the gap and prints it rather than failing every run in a
    # shared tree. Flip the flag and the same numbers become hard gates — no
    # second edit, and no chance of the gate being quietly loosened to match
    # whatever the fix happens to produce.
    if not MC_ENABLED:
        print(
            "  NOTE: MC_ENABLED is False — the native multicontact path is"
            " OFF, so ONE point per pair is expected here."
        )
        print(
            "  OPEN GAP: count mismatches =", tot_cnt_bad,
            " worst |dpos| =", worst_pos_all,
            " worst |dn| =", worst_dir_all,
        )
        return

    assert_true(
        worst_dir_all <= TOL_DIR,
        String("mesh contact NORMAL diverges from MuJoCo by ")
        + String(worst_dir_all),
    )
    assert_true(
        tot_cnt_bad == 0,
        String("manifold POINT COUNT differs from MuJoCo on ")
        + String(tot_cnt_bad) + " (pose, group) cases — this is the native"
        " `multicontact()` gap",
    )
    assert_true(
        worst_pos_all <= TOL_POS,
        String("a MuJoCo manifold point is ") + String(worst_pos_all)
        + " m from the nearest of ours",
    )


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
