"""Every count the RENDER HOOKS use as a bound is already inside `RenderFields`.

WHY THIS EXISTS
===============
The fifteen render hooks on `ModelDefFromXML` are *almost* pure functions of
`rf: RenderFields` — that is what makes one `ModelRenderer` able to draw any
file, and it is the load-bearing observation behind the physics3d studio. The
"almost" is a handful of COMPTIME STRUCT PARAMETERS used as loop bounds and
bounds checks:

    for i in range(Self.NGEOM):          # render_body_geoms
        if mid >= 0 and mid < Self.nmat: # material lookup
    for c in range(Self.ncam):           # setup_cameras
    for t in range(Self.ntex):           # get_skybox_colors
    for s in range(Self.NSITE):          # render_sites

A model loaded at RUNTIME has no such parameters — `DynDims` answers
`DIM_POISON` — so each one has to become `len(rf.<the list it bounds>)`.

⚠⚠ THAT SUBSTITUTION IS ONLY SAFE IF THE TWO NUMBERS AGREE, AND NOBODY HAS
EVER CHECKED. They come from different places: the parameter is hand-written
in the model def (or generated by a bake script), while the list is filled by
`build_render_fields` from `parse_xml_full`. This tree has a scar exactly
here — `so_arm100` shipped with `nexclude` defaulted to 0 while the parser
found 1, and the `<exclude>` was silently unbuilt for months. A count that is
too SMALL truncates the draw silently; too LARGE reads past the end.

So this gate runs first, and it is what licenses the substitution. It also
keeps licensing it: a model def added later with a stale count fails HERE,
naming the family, instead of drawing 71 of its 72 geoms.

Run: pixi run mojo run -I . tests/physics3d/test_render_counts_are_in_render_fields.mojo
"""

from mojo_rl.physics3d.parser.render_fields import (
    RenderFields, build_render_fields,
)
from mojo_rl.physics3d.parser.full_parser import parse_xml_full

from mojo_rl.envs.walker2d.walker2d_xml import Walker2dModel
from mojo_rl.envs.hopper.hopper_xml import HopperModel
from mojo_rl.envs.humanoid.humanoid_xml import HumanoidModel
from mojo_rl.envs.ant.ant_xml import AntModel
from mojo_rl.envs.pusher.pusher_xml import PusherModel
from mojo_rl.envs.robots.so_arm100_xml import SoArm100Model
from mojo_rl.envs.dm_control.quadruped.quadruped_xml import DMQuadrupedWalkModel
from mojo_rl.envs.dm_control.point_mass.point_mass_xml import DMPointMassModel
from mojo_rl.envs.dm_control.cheetah.cheetah_xml import DMCheetahModel
from mojo_rl.envs.dm_control.cartpole.cartpole_xml import DMCartpole1Model


struct Tally:
    var checks: Int
    var fails: Int

    def __init__(out self):
        self.checks = 0
        self.fails = 0

    def eq(mut self, got: Int, want: Int, msg: String):
        self.checks += 1
        if got == want:
            print("  ok:", msg, "=", got)
        else:
            self.fails += 1
            print("  FAIL:", msg, "— the def says", want,
                  "but RenderFields holds", got)


def check[
    NGEOM: Int, NSITE: Int, ncam: Int, ntex: Int, nmat: Int, nlight: Int
](mut t: Tally, xml_text: String, base: String, name: String) raises:
    """One model: the def's six counts against the six list lengths."""
    var rf = build_render_fields(parse_xml_full(xml_text, base))
    print("---", name)
    t.eq(len(rf.geom_type), NGEOM, String(name, ": ngeom"))
    t.eq(len(rf.site_pos_x), NSITE, String(name, ": nsite"))
    t.eq(len(rf.cam_fovy), ncam, String(name, ": ncam"))
    t.eq(rf.ntex, ntex, String(name, ": ntex"))
    t.eq(len(rf.mat_rgba_r), nmat, String(name, ": nmat"))
    t.eq(len(rf.light_dir_x), nlight, String(name, ": nlight"))
    # ⚠ NON-VACUITY. A model whose every count is 0 would pass all six arms
    # while proving nothing about the substitution.
    t.checks += 1
    if NGEOM > 0:
        print("  ok:", name, ": non-vacuous (ngeom", NGEOM, ")")
    else:
        t.fails += 1
        print("  FAIL:", name, ": VACUOUS — ngeom is 0, this row tests nothing")


def main() raises:
    var t = Tally()
    print("=== render-hook bounds vs RenderFields list lengths ===")
    check[
        Walker2dModel.NGEOM, Walker2dModel.NSITE, Walker2dModel.ncam,
        Walker2dModel.ntex, Walker2dModel.nmat, Walker2dModel.nlight
    ](t, Walker2dModel.xml_text(), Walker2dModel.asset_base_dir(), "walker2d")
    check[
        HopperModel.NGEOM, HopperModel.NSITE, HopperModel.ncam,
        HopperModel.ntex, HopperModel.nmat, HopperModel.nlight
    ](t, HopperModel.xml_text(), HopperModel.asset_base_dir(), "hopper")
    check[
        HumanoidModel.NGEOM, HumanoidModel.NSITE, HumanoidModel.ncam,
        HumanoidModel.ntex, HumanoidModel.nmat, HumanoidModel.nlight
    ](t, HumanoidModel.xml_text(), HumanoidModel.asset_base_dir(), "humanoid")
    check[
        AntModel.NGEOM, AntModel.NSITE, AntModel.ncam,
        AntModel.ntex, AntModel.nmat, AntModel.nlight
    ](t, AntModel.xml_text(), AntModel.asset_base_dir(), "ant")
    check[
        PusherModel.NGEOM, PusherModel.NSITE, PusherModel.ncam,
        PusherModel.ntex, PusherModel.nmat, PusherModel.nlight
    ](t, PusherModel.xml_text(), PusherModel.asset_base_dir(), "pusher")
    check[
        SoArm100Model.NGEOM, SoArm100Model.NSITE, SoArm100Model.ncam,
        SoArm100Model.ntex, SoArm100Model.nmat, SoArm100Model.nlight
    ](t, SoArm100Model.xml_text(), SoArm100Model.asset_base_dir(), "so_arm100")
    check[
        DMQuadrupedWalkModel.NGEOM, DMQuadrupedWalkModel.NSITE,
        DMQuadrupedWalkModel.ncam, DMQuadrupedWalkModel.ntex,
        DMQuadrupedWalkModel.nmat, DMQuadrupedWalkModel.nlight
    ](t, DMQuadrupedWalkModel.xml_text(),
      DMQuadrupedWalkModel.asset_base_dir(), "dm_quadruped_walk")
    check[
        DMPointMassModel.NGEOM, DMPointMassModel.NSITE, DMPointMassModel.ncam,
        DMPointMassModel.ntex, DMPointMassModel.nmat, DMPointMassModel.nlight
    ](t, DMPointMassModel.xml_text(), DMPointMassModel.asset_base_dir(),
      "dm_point_mass")
    check[
        DMCheetahModel.NGEOM, DMCheetahModel.NSITE, DMCheetahModel.ncam,
        DMCheetahModel.ntex, DMCheetahModel.nmat, DMCheetahModel.nlight
    ](t, DMCheetahModel.xml_text(), DMCheetahModel.asset_base_dir(),
      "dm_cheetah")
    check[
        DMCartpole1Model.NGEOM, DMCartpole1Model.NSITE, DMCartpole1Model.ncam,
        DMCartpole1Model.ntex, DMCartpole1Model.nmat, DMCartpole1Model.nlight
    ](t, DMCartpole1Model.xml_text(), DMCartpole1Model.asset_base_dir(),
      "dm_cartpole1")

    print("===", t.checks - t.fails, "/", t.checks, "passed ===")
    if t.fails != 0:
        raise Error(
            "test_render_counts_are_in_render_fields: "
            + String(t.fails) + " failed"
        )
