"""Every LIBERO family on the batched GPU env — model defs, budgets, envs.

    from mojo_rl.tasks.libero_envs.libero_kitchen_scene3_xml import (
        LiberoKitchenScene3Model, LiberoKitchenScene3OscEnv,
        LIBERO_KITCHEN_SCENE3_OBS_DIM,
    )
    from mojo_rl.tasks.libero_envs.budgets import LIBERO_GOAL_MAX_CONTACTS

`budgets.mojo` and the twenty `<family>_xml.mojo` are GENERATED by
`tools/tasks/gen_libero_envs.mojo`; the `<family>_dims.mojo` beside them by
`tools/gen_model_dims.py`. `libero_goal`, `libero_object` and `libero_spatial`
keep their hand-written `tasks/libero_<suite>_xml.mojo`.
"""
