"""DreamerOpt CPU step parity vs the reference optax chain.

Ground truth: `tests/nn2/dreamerv3/fixtures/dreamer_opt_fixture.txt`,
generated by `extract.py` running the VERBATIM reference transforms
(`clip_by_agc` / `scale_by_rms` / `scale_by_momentum` from
`references/dreamerv3-main/embodied/jax/opt.py`) under real jax+optax.

The fixture's two leaves (12 + 4 elems) map onto a `Linear[3,4]` walk
(weight=12 then bias=4). AGC norm is over the whole flattened leaf and
rms/momentum are elementwise, so the 1-D fixture leaves line up with the
flat per-Param walk regardless of the (3,4) shape. lr=1.0 in the fixture
so per-step deltas are O(1) and the 1e-6 abs-diff bound is meaningful.

Also covers the warmup schedule (`LinearWarmupSchedule` vs optax
join_schedules curve probes) and an nu/mu/step save→load round-trip.
"""

from std.memory import alloc
from std.testing import assert_true
from layout import TileTensor, row_major
from std.gpu.memory import AddressSpace

from mojo_rl.nn2.constants import DT
from mojo_rl.nn2.core.param_visitor import ParamVisitor
from mojo_rl.nn2.primitives.linear import Linear
from mojo_rl.nn2.initializer import Kaiming
from mojo_rl.nn2.optimizer.dreamer_opt import DreamerOpt
from mojo_rl.nn2.optimizer.schedules import LinearWarmupSchedule


comptime IN = 3
comptime OUT = 4
comptime MODEL = Linear[IN, OUT]   # weight=12, bias=4 → 16 params
comptime FIXTURE = "tests/nn2/dreamerv3/fixtures/dreamer_opt_fixture.txt"


# ──────────────────────────────────────────────────────────────────────
# Visitors: set params / set grads / read params from a flat walk-order
# stream.
# ──────────────────────────────────────────────────────────────────────


@fieldwise_init
struct _SetParamVisitor(ParamVisitor):
    var src: UnsafePointer[List[Scalar[DT]], MutAnyOrigin]
    var idx: Int

    def visit(
        mut self,
        name: String,
        param: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC, element_size=1, ...
        ],
        grad: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC, element_size=1, ...
        ],
        n_elems: Int,
        apply_decay: Bool,
    ) raises:
        var p = rebind[UnsafePointer[Scalar[DT], MutAnyOrigin]](param.ptr)
        for k in range(n_elems):
            p[k] = self.src[][self.idx]
            self.idx += 1


@fieldwise_init
struct _SetGradVisitor(ParamVisitor):
    var src: UnsafePointer[List[Scalar[DT]], MutAnyOrigin]
    var idx: Int

    def visit(
        mut self,
        name: String,
        param: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC, element_size=1, ...
        ],
        grad: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC, element_size=1, ...
        ],
        n_elems: Int,
        apply_decay: Bool,
    ) raises:
        var g = rebind[UnsafePointer[Scalar[DT], MutAnyOrigin]](grad.ptr)
        for k in range(n_elems):
            g[k] = self.src[][self.idx]
            self.idx += 1


@fieldwise_init
struct _ReadParamVisitor(ParamVisitor):
    var dst: UnsafePointer[List[Scalar[DT]], MutAnyOrigin]

    def visit(
        mut self,
        name: String,
        param: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC, element_size=1, ...
        ],
        grad: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC, element_size=1, ...
        ],
        n_elems: Int,
        apply_decay: Bool,
    ) raises:
        var p = rebind[UnsafePointer[Scalar[DT], MutAnyOrigin]](param.ptr)
        for k in range(n_elems):
            self.dst[].append(p[k])


# ──────────────────────────────────────────────────────────────────────
# Fixture parsing helpers (line-based, mirrors test_optimizer_state_save).
# ──────────────────────────────────────────────────────────────────────


def _split_lines(content: String) raises -> List[String]:
    var lines = List[String]()
    var current = String("")
    var bytes = content.as_bytes()
    for i in range(len(bytes)):
        var c = bytes[i]
        if c == UInt8(ord("\n")):
            lines.append(current)
            current = String("")
        else:
            current += chr(Int(c))
    if current.byte_length() > 0:
        lines.append(current)
    return lines^


def _get_scalar(lines: List[String], key: String) raises -> Float64:
    var pfx = key + "="
    for i in range(len(lines)):
        if lines[i].startswith(pfx):
            return atof(String(lines[i][byte=pfx.byte_length():]))
    raise Error("fixture: key not found: " + key)


def _read_flat(lines: List[String], name: String) raises -> List[Scalar[DT]]:
    """Find the `name#size=N` header and read the next N float lines."""
    var pfx = name + "#size="
    for i in range(len(lines)):
        if lines[i].startswith(pfx):
            var n = atol(String(lines[i][byte=pfx.byte_length():]))
            var out = List[Scalar[DT]]()
            for k in range(n):
                out.append(Scalar[DT](atof(lines[i + 1 + k])))
            return out^
    raise Error("fixture: section not found: " + name)


def _max_abs_diff(
    a: List[Scalar[DT]], b: List[Scalar[DT]]
) -> Scalar[DT]:
    var m: Scalar[DT] = 0.0
    var n = len(a) if len(a) < len(b) else len(b)
    for i in range(n):
        var d = a[i] - b[i]
        var ad = d if d >= Scalar[DT](0) else -d
        if ad > m:
            m = ad
    return m


# ──────────────────────────────────────────────────────────────────────
# Tests.
# ──────────────────────────────────────────────────────────────────────


def test_step_parity() raises:
    print("test_step_parity ...")
    var content: String
    with open(FIXTURE, "r") as f:
        content = String(f.read())
    var lines = _split_lines(content)

    var agc_clip = Scalar[DT](_get_scalar(lines, "agc_clip"))
    var agc_pmin = Scalar[DT](_get_scalar(lines, "agc_pmin"))
    var beta1 = Scalar[DT](_get_scalar(lines, "beta1"))
    var beta2 = Scalar[DT](_get_scalar(lines, "beta2"))
    var eps = Scalar[DT](_get_scalar(lines, "eps"))
    var lr = Scalar[DT](_get_scalar(lines, "lr"))
    var n_steps = Int(_get_scalar(lines, "n_steps"))

    var model = MODEL.make[target="cpu", INIT=Kaiming]()
    var opt = DreamerOpt.make[target="cpu", M=MODEL](model)
    opt.lr = lr
    opt.beta1 = beta1
    opt.beta2 = beta2
    opt.eps = eps
    opt.agc_clip = agc_clip
    opt.agc_pmin = agc_pmin

    # Set initial params.
    var init = _read_flat(lines, "init")
    var sp = _SetParamVisitor(src=UnsafePointer(to=init), idx=0)
    model.for_each_param["cpu", _SetParamVisitor](String(""), sp)

    var worst: Scalar[DT] = 0.0
    for t in range(n_steps):
        var grads = _read_flat(lines, "step" + String(t) + ".grad")
        var sg = _SetGradVisitor(src=UnsafePointer(to=grads), idx=0)
        model.for_each_param["cpu", _SetGradVisitor](String(""), sg)

        opt.step["cpu", M=MODEL](model)

        var got = List[Scalar[DT]]()
        var rp = _ReadParamVisitor(dst=UnsafePointer(to=got))
        model.for_each_param["cpu", _ReadParamVisitor](String(""), rp)

        # ── Closed-form check at step 0 ──
        # With zero moment history, rms normalisation collapses to
        # g_rms = g/(sqrt(g²)+eps) = sign(g) and momentum bias-correction
        # cancels (mu_hat = g_rms), so the exact update is
        #   p_new = p_init - lr·sign(grad)
        # (the AGC scale cancels in g/sqrt(g²)). This validates OUR
        # implementation against the algorithm's closed form, independent
        # of any reference-impl fp32 quirk.
        if t == 0:
            var cf_worst: Scalar[DT] = 0.0
            for e in range(len(got)):
                var s: Scalar[DT] = 0.0
                if grads[e] > Scalar[DT](0):
                    s = 1.0
                elif grads[e] < Scalar[DT](0):
                    s = -1.0
                var cf = init[e] - lr * s
                var dd = got[e] - cf
                var add = dd if dd >= Scalar[DT](0) else -dd
                if add > cf_worst:
                    cf_worst = add
            print("  step 0 closed-form max diff =", cf_worst)
            assert_true(
                cf_worst < Scalar[DT](1e-6),
                "step 0 must equal init - lr·sign(grad) within 1e-6",
            )

        var expected = _read_flat(lines, "step" + String(t) + ".param")
        var d = _max_abs_diff(got, expected)
        print("  step", t, "max|param diff vs optax| =", d)
        if d > worst:
            worst = d

    # Tolerance note: the residual vs the reference is pure fp32
    # evaluation-order noise, NOT an algorithm difference. optax computes
    # the EMA coefficient (1-decay) in float64-then-cast but the bias-
    # correction denominator (1 - decay**count) entirely in float32; at
    # count=1 these are mathematically the same 0.001 yet differ ~5e-6
    # relative in f32, so they don't perfectly cancel. Our Mojo derives
    # both from the same f32 beta, so they cancel exactly — leaving a
    # ~7e-6/step difference that accumulates linearly (≈4e-5 over 6 steps).
    # A genuine algorithmic error (wrong moment wiring / AGC / order)
    # would be O(0.1-1), four+ orders larger. 1e-4 catches real bugs with
    # a 1000x margin; the closed-form step-0 check above pins correctness.
    print("  worst over", n_steps, "steps =", worst)
    assert_true(
        worst < Scalar[DT](1e-4),
        "DreamerOpt CPU step must match optax chain within f32 noise (1e-4)",
    )
    print("  ok")


def test_warmup_schedule() raises:
    print("test_warmup_schedule ...")
    var content: String
    with open(FIXTURE, "r") as f:
        content = String(f.read())
    var lines = _split_lines(content)

    var sched_lr = Scalar[DT](_get_scalar(lines, "sched_lr"))
    var warmup = Int(_get_scalar(lines, "sched_warmup"))
    var sched = LinearWarmupSchedule.make(sched_lr, warmup)

    var worst: Scalar[DT] = 0.0
    var n_checked = 0
    for i in range(len(lines)):
        if lines[i].startswith("sched_probe "):
            var rest = String(lines[i][byte="sched_probe ".byte_length():])
            # "<step> <value>"
            var sp_idx = rest.find(" ")
            var step = atol(String(rest[byte=:sp_idx]))
            var expected = Scalar[DT](atof(String(rest[byte=(sp_idx + 1):])))
            var got = sched.lr_at(step)
            var d = got - expected
            var ad = d if d >= Scalar[DT](0) else -d
            if ad > worst:
                worst = ad
            n_checked += 1
    print("  checked", n_checked, "probes, worst diff =", worst)
    assert_true(n_checked > 0, "no schedule probes found in fixture")
    assert_true(
        worst < Scalar[DT](1e-9),
        "LinearWarmupSchedule must match optax curve within 1e-9",
    )
    print("  ok")


def test_save_load_round_trip() raises:
    print("test_save_load_round_trip ...")
    # Build + step a few times to populate nu/mu/step, save, load into a
    # fresh opt (sized to the same model), then assert the next step from
    # both produces identical params.
    var content: String
    with open(FIXTURE, "r") as f:
        content = String(f.read())
    var lines = _split_lines(content)
    var lr = Scalar[DT](_get_scalar(lines, "lr"))

    var model_a = MODEL.make[target="cpu", INIT=Kaiming]()
    var opt_a = DreamerOpt.make[target="cpu", M=MODEL](model_a)
    opt_a.lr = lr

    var init = _read_flat(lines, "init")
    var sp = _SetParamVisitor(src=UnsafePointer(to=init), idx=0)
    model_a.for_each_param["cpu", _SetParamVisitor](String(""), sp)

    # 3 steps to build state.
    for t in range(3):
        var grads = _read_flat(lines, "step" + String(t) + ".grad")
        var sg = _SetGradVisitor(src=UnsafePointer(to=grads), idx=0)
        model_a.for_each_param["cpu", _SetGradVisitor](String(""), sg)
        opt_a.step["cpu", M=MODEL](model_a)
        _ = grads

    # Save opt_a.
    var dump = String("")
    opt_a.save(dump, String("dopt"))
    var opt_path = String("/tmp/test_nn2_dreamer_opt.txt")
    with open(opt_path, "w") as f:
        f.write(dump)

    # Snapshot model_a params, then take one more step on A.
    var grads3 = _read_flat(lines, "step3.grad")
    var sg3a = _SetGradVisitor(src=UnsafePointer(to=grads3), idx=0)
    model_a.for_each_param["cpu", _SetGradVisitor](String(""), sg3a)
    _ = grads3
    opt_a.step["cpu", M=MODEL](model_a)
    var params_a = List[Scalar[DT]]()
    var rpa = _ReadParamVisitor(dst=UnsafePointer(to=params_a))
    model_a.for_each_param["cpu", _ReadParamVisitor](String(""), rpa)

    # Fresh model_b with the SAME params after 3 steps as A had pre-step-4.
    # Reconstruct A's post-3-step params by replaying into model_b, then
    # load A's optimizer state and take step 4 — must match A.
    var model_b = MODEL.make[target="cpu", INIT=Kaiming]()
    var opt_b = DreamerOpt.make[target="cpu", M=MODEL](model_b)
    opt_b.lr = Scalar[DT](999.0)  # nonsense — load must overwrite

    # Re-derive model_b's post-3-step params by replaying steps 0..2 with a
    # second opt (state discarded — we only need the params trajectory).
    var sp_b = _SetParamVisitor(src=UnsafePointer(to=init), idx=0)
    model_b.for_each_param["cpu", _SetParamVisitor](String(""), sp_b)
    _ = init
    var opt_tmp = DreamerOpt.make[target="cpu", M=MODEL](model_b)
    opt_tmp.lr = lr
    for t in range(3):
        var grads = _read_flat(lines, "step" + String(t) + ".grad")
        var sg = _SetGradVisitor(src=UnsafePointer(to=grads), idx=0)
        model_b.for_each_param["cpu", _SetGradVisitor](String(""), sg)
        opt_tmp.step["cpu", M=MODEL](model_b)
        _ = grads

    # Load A's optimizer state into opt_b.
    var loaded: String
    with open(opt_path, "r") as f:
        loaded = String(f.read())
    var llines = _split_lines(loaded)
    var idx = 0
    opt_b.load(llines, idx, String("dopt"))

    assert_true(
        opt_b.lr == lr, "load must overwrite lr (was 999.0 pre-load)"
    )
    assert_true(opt_b.step_count == 3, "step_count must round-trip to 3")

    # Step 4 on B with the loaded state. Re-read step3 grads fresh (reusing
    # `grads3` would dangle — Mojo can end its lifetime after the sg3a use).
    var grads3b = _read_flat(lines, "step3.grad")
    var sg3b = _SetGradVisitor(src=UnsafePointer(to=grads3b), idx=0)
    model_b.for_each_param["cpu", _SetGradVisitor](String(""), sg3b)
    _ = grads3b
    opt_b.step["cpu", M=MODEL](model_b)
    var params_b = List[Scalar[DT]]()
    var rpb = _ReadParamVisitor(dst=UnsafePointer(to=params_b))
    model_b.for_each_param["cpu", _ReadParamVisitor](String(""), rpb)

    var d = _max_abs_diff(params_a, params_b)
    print("  max|A - B| after resumed step 4 =", d)
    assert_true(
        d < Scalar[DT](1e-5),
        "resumed step must match within text-round-trip tolerance",
    )
    print("  ok")


def main() raises:
    print("=" * 70)
    print("DreamerOpt parity (vs optax) + warmup + save/load")
    print("=" * 70)
    test_step_parity()
    test_warmup_schedule()
    test_save_load_round_trip()
    print("=" * 70)
    print("ALL PASSED")
    print("=" * 70)
