"""Render a ComputeGraph to a Markdown file with an embedded mermaid
diagram (GitHub renders ```mermaid fences natively).

Run:
    pixi run mojo run -I . examples/nn/export_graph_mermaid.mojo

Writes `docs/WM_LOSS_GRAPH.md`. `describe` reads only the comptime
topology, so the graph is default-constructed — no make / device context.
"""

from mojo_rl.nn.combinators import MermaidExporter
from mojo_rl.deep_agents.dreamerv3.wm import WMLossGraph


def write_md(path: String, title: String, mermaid: String) raises:
    var s = String("# ") + title + "\n\n"
    s += "_Auto-generated by `examples/nn/export_graph_mermaid.mojo`._\n\n"
    s += "```mermaid\n"
    s += mermaid
    s += "```\n"
    with open(path, "w") as f:
        f.write(s)


def main() raises:
    # Tiny RSSM dims — only the topology matters for describe.
    comptime WM = WMLossGraph[
        8,   # DETER
        16,  # H
        4,   # STOCH
        4,   # CLASSES
        2,   # BLOCKS
        3,   # ACT
        12,  # TOKEN
        10,  # OBS
        16,  # DEC_U
        16,  # HU
        5,   # BINS
    ]
    var g = WM()

    var m = MermaidExporter()
    g.describe(m, "WMLossGraph")

    var out_path = String("docs/WM_LOSS_GRAPH.md")
    write_md(out_path, "DreamerV3 WMLossGraph", m.out)
    print("Wrote", out_path, "(", m.out.byte_length(), "bytes of mermaid )")
