"""Phase B gate — conv-PC PCModule trains on nn storage + nn Adam (CPU).

Proves the Phase-A storage model propagates to NON-linear block types: a
`PCModule` mixing a `ConvPCBlock` with a linear readout `PCBlock` is built
via the legacy-`nn`-free `make_pcn[PCXavier]` (which delegates to each
block's `pc_init_params`), and trained by nn `Adam` driven from PCN's
settling loop.

The target is generated by a *teacher* PCModule of the same architecture
(random init), so it is exactly representable — the student (different init)
must drive the readout loss sharply down.

Validates:
  - `PCModule[ConvPCBlock, PCBlock]` (mixed block types) conforms to nn
    `Module`; one `Param` holds the whole conv+linear weight slab.
  - `make_pcn` → `PCSequential.init_params_pc` → per-block `pc_init_params`
    (conv W via vendored `PCXavier`; legacy-`nn`-free init path).
  - vendored `apple_sgemm_accum` + `TPB`/`MMA` constants drive the conv
    forward / weight-grad under the new path.

Run:
    pixi run mojo run -I . tests/pcn/test_pc_module_conv_nn.mojo
"""

from std.random import seed, random_float64
from std.testing import assert_true
from layout import Layout, LayoutTensor

from mojo_rl.nn.constants import DT
from mojo_rl.nn.optimizer.adam import Adam

from mojo_rl.experimental.pcn.pc_block import PCBlock
from mojo_rl.experimental.pcn.pc_conv_block import ConvPCBlock
from mojo_rl.experimental.pcn.predictive_model import PCIdentity
from mojo_rl.experimental.pcn.pc_sequential import PCSequential
from mojo_rl.experimental.pcn.pc_module import PCModule
from mojo_rl.experimental.pcn.pc_initializer import PCXavier
from mojo_rl.experimental.pcn.pc_module_trainer import pc_module_train_one_batch
from mojo_rl.nn.core.ptr import mptr


def main() raises:
    # 1 channel 6×6 → Conv(1→2, k3 s1 p1) = 2×6×6 = 72 → linear readout → 3.
    comptime C_IN = 1
    comptime H = 6
    comptime W = 6
    comptime IN = C_IN * H * W  # 36
    comptime C_OUT = 2
    comptime CONV_OUT = C_OUT * H * W  # 72
    comptime OUT = 3
    comptime BATCH = 8
    comptime T_INFER = 20
    comptime N_STEPS = 250

    comptime Net = PCModule[
        ConvPCBlock[C_IN, C_OUT, 3, 1, 1, H, W, PCIdentity],
        PCBlock[CONV_OUT, OUT, PCIdentity],
    ]
    comptime Seq = PCSequential[
        ConvPCBlock[C_IN, C_OUT, 3, 1, 1, H, W, PCIdentity],
        PCBlock[CONV_OUT, OUT, PCIdentity],
    ]

    seed(0)

    # Random inputs.
    var x_s = List[Scalar[DT]](capacity=BATCH * IN)
    for _ in range(BATCH * IN):
        x_s.append(Scalar[DT](random_float64() * 2.0 - 1.0))
    var x_in = LayoutTensor[DT, Layout.row_major(BATCH, IN), MutAnyOrigin](
        mptr(x_s)
    )

    # Teacher (random init) defines an exactly-representable target.
    var teacher = Net.make_pcn[PCXavier]()
    var y_s = List[Scalar[DT]](capacity=BATCH * OUT)
    for _ in range(BATCH * OUT):
        y_s.append(Scalar[DT](0))
    var y_target = LayoutTensor[DT, Layout.row_major(BATCH, OUT), MutAnyOrigin](
        mptr(y_s)
    )
    var teacher_params = LayoutTensor[
        DT, Layout.row_major(Seq.PARAM_SIZE), MutAnyOrigin
    ](mptr(teacher.weights.val.data))
    Seq.forward_eval[BATCH](x_in, teacher_params, y_target)

    # Student (different draws) trains to match.
    var net = Net.make_pcn[PCXavier]()
    var opt = Adam(lr=Scalar[DT](5e-3))

    var loss_first = Float64(0.0)
    var loss_last = Float64(0.0)
    for step in range(N_STEPS):
        var r = pc_module_train_one_batch[BATCH](
            net, opt, x_in, y_target, T_INFER, Scalar[DT](0.1)
        )
        if step == 0:
            loss_first = r.output_loss_final
        if step == N_STEPS - 1:
            loss_last = r.output_loss_final

    print("conv-PC readout loss: first =", loss_first, " last =", loss_last)
    assert_true(loss_last == loss_last, "loss is NaN")
    assert_true(loss_last < loss_first, "loss did not decrease")
    assert_true(
        loss_last < loss_first * 0.2,
        "conv-PC PCModule did not learn (loss fell < 5×)",
    )
    print("PASS: conv-PC PCModule trains on nn storage via nn Adam (Phase B)")
