"""One LIBERO suite -> one `.family` + its `.task` files. L2.

    pixi run mojo run -I . tools/tasks/gen_libero_family.mojo libero_goal
    pixi run mojo run -I . tools/tasks/gen_libero_family.mojo libero_goal --check

Writes `mojo_rl/tasks/families/<suite>.family` and, for every file whose goal
our language can express, `mojo_rl/tasks/tasks/<suite>__<file stem>.task`.
Needs the LIBERO corpus (`references/LIBERO-master`), the pulled pack
(`pixi run assets-pull libero`), the generated arenas
(`tools/tasks/gen_libero_arenas.py`) and the vendored Panda
(`tools/robots/vendor_panda_robosuite.py`).

## ⚠⚠ ONE FAMILY PER SUITE MEANS ONE SLOT TABLE — A UNION, AND IT IS CHECKED

`TASK_LAYER_PLAN.md` §3.6 predicted `libero_goal` and `libero_spatial` are
"one family, trivially". Measured on the corpus: both suites' ten files
declare the SAME fixtures and the SAME objects, at the same poses, so for
those two the union IS each file's list and every generated byte is unchanged
by the union rule below.

`libero_object` is the suite that needs it. Its ten files declare ELEVEN
distinct props between them and SEVEN each: the family pools all eleven, and
each `.task` names its own seven plus the basket with `active=`. The union
REFUSES a slot name that arrives twice with a different kind, asset, pose or
placement geometry — the alternative is a family whose tasks silently run on
a scene one of them did not describe.

⚠ THE SCENE PAYS FOR THE UNION. Eleven free props is eleven free joints in
one compiled model whether a task uses them or not; the four a task does not
name are parked at `park=` and contribute no contacts (`family.mojo`'s P1c
gate). That is the trade the fixed scene budget asks for — one compile unit
per suite instead of one per task.

## ⚠⚠ A REGION IS KEYED BY ITS GEOMETRY, NOT BY ITS NAME

See `libero_import.RegionAlias`. `libero_object`'s ten files use the names
`target_object_region` and `other_object_region_0` for the same TWO floor
rectangles, swapped in five of them: the name is a per-file ROLE, the
rectangle is the identity. So the union keys a region by every field but its
name, keeps the first name it saw, and hands each file a `RegionAlias` list
that `translate_task` resolves its own names through. The aliases are PRINTED
for every file that has any, because a silent remap of where a prop starts is
exactly the failure this keying exists to prevent.

## What a `.task` carries

Only the goals `translate_task` can express are written; the rest are
counted and named. L2 wrote 1 of 10 for `libero_goal`; L3 (box regions,
Joint terms, On(obj, obj)) writes all 10, and the count is printed so the
number cannot drift unnoticed.
"""

from std.os import listdir
from std.pathlib import Path
from std.sys import argv

from mojo_rl.tasks.bddl import parse_bddl, BddlProblem
from mojo_rl.tasks.libero_categories import load_libero_table, DEFAULT_TABLE_PATH
from mojo_rl.tasks.libero_import import (
    resolve_family, translate_task, classify_goal, gap_name, GAP_NONE,
    LIBERO_ROBOT_DIR, LIBERO_ARENA_DIR, RegionAlias,
)
from mojo_rl.tasks.spec import (
    FamilySpec, TaskSpec, RegionSpec, validate_task_against_family,
)


comptime BDDL_ROOT = "references/LIBERO-master/libero/libero/bddl_files"
comptime PACK_DIR = "mojo_rl/tasks/libero/assets"
comptime FAMILY_DIR = "mojo_rl/tasks/families"
comptime TASK_DIR = "mojo_rl/tasks/tasks"


def _stem(path: String) -> String:
    var base = path
    var cut = path.rfind("/")
    if cut >= 0:
        base = String(path[byte = cut + 1 : path.byte_length()])
    var dot = base.rfind(".")
    if dot <= 0:
        return base^
    return String(base[byte=0:dot])


def _sorted_bddl(dir: String) raises -> List[String]:
    var names = List[String]()
    for e in listdir(dir):
        var n = String(e)
        if n.endswith(".bddl"):
            names.append(n)
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            if names[j] < names[i]:
                names[i], names[j] = names[j], names[i]
    var out = List[String]()
    for i in range(len(names)):
        out.append(dir + "/" + names[i])
    return out^


def _union_slots(mut fam: FamilySpec, f: FamilySpec, what: String) raises:
    """Merge `f`'s slots into `fam` by NAME. RAISES on the first slot two
    files describe differently, naming it.

    ⚠ THE POSE AND THE PLACEMENT GEOMETRY ARE PART OF THE IDENTITY. Two files
    may legitimately not both mention a prop; they may not disagree about
    where a fixture stands or how tall the thing they both call
    `akita_black_bowl_1` is, because the family carries ONE answer and the
    other file's tasks would run against it.
    """
    if (
        fam.base != f.base or fam.base_x != f.base_x
        or fam.base_y != f.base_y or fam.base_z != f.base_z
    ):
        raise Error(what + ": base differs (" + fam.base + " vs " + f.base + ")")
    if (
        fam.horizon != f.horizon or fam.control_freq != f.control_freq
        or fam.floor != f.floor or fam.inherit_option != f.inherit_option
        or fam.park_x != f.park_x or fam.park_y != f.park_y
        or fam.park_z != f.park_z
    ):
        raise Error(
            what + ": the family scalars differ (horizon / control_freq /"
            " floor / inherit_option / park). One family has one of each."
        )
    for i in range(len(f.slots)):
        var si = fam.slot_index(f.slots[i].name)
        if si < 0:
            fam.slots.append(f.slots[i])
            continue
        ref x = fam.slots[si]
        ref y = f.slots[i]
        if (
            x.kind != y.kind or x.asset != y.asset
            or x.has_pose != y.has_pose or x.px != y.px or x.py != y.py
            or x.pz != y.pz or x.yaw != y.yaw
            or x.has_geom != y.has_geom or x.bottom_z != y.bottom_z
            or x.top_z != y.top_z or x.h_radius != y.h_radius
        ):
            raise Error(
                what + ": slot '" + x.name + "' is declared two different ways"
                " across the suite: " + x.describe() + " / " + x.geom_describe()
                + " vs " + y.describe() + " / " + y.geom_describe()
            )


def _same_geom(a: RegionSpec, b: RegionSpec) -> Bool:
    """Every field of a region EXCEPT its name — see the module header."""
    return (
        a.site == b.site and a.is_box == b.is_box and a.contact == b.contact
        and a.has_rect == b.has_rect and a.x_min == b.x_min
        and a.y_min == b.y_min and a.x_max == b.x_max and a.y_max == b.y_max
        and a.half_height == b.half_height and a.has_height == b.has_height
    )


def _merge_region(
    mut fam: FamilySpec, want: RegionSpec, what: String,
    mut region_alias: List[RegionAlias],
) raises:
    """One region into the union, keyed by geometry (module header).

    ⚠ THE FIRST NAME WINS and every later name for that rectangle becomes an
    alias. ⚠ A NAME THAT ARRIVES WITH A GEOMETRY THE UNION DOES NOT HAVE, AND
    IS ALREADY TAKEN, IS REFUSED: keeping both would need a canonical naming
    scheme, and no file in the 130 asks for one. Refusing names the file.
    """
    for q in range(len(fam.regions)):
        if _same_geom(fam.regions[q], want):
            if fam.regions[q].name != want.name:
                region_alias.append(
                    RegionAlias(String(want.name), String(fam.regions[q].name))
                )
            return
    var taken = fam.region_index(want.name)
    if taken >= 0:
        raise Error(
            what + ": region '" + want.name + "' names a rectangle the union"
            " does not have (" + want.describe() + ") while that NAME is"
            " already the union's for " + fam.regions[taken].describe()
            + ". The union keys a region by geometry and keeps the first"
            " name; this file would need a third, canonical, name. Nothing in"
            " the corpus hits it — see `_merge_region`."
        )
    fam.regions.append(want)


def _write_if_changed(path: String, text: String, check: Bool) raises -> Int:
    var old = String("")
    var have = True
    try:
        with open(path, "r") as fh:
            old = fh.read()
    except:
        have = False
    if have and old == text:
        print("  unchanged", path)
        return 0
    if check:
        print("  STALE    ", path)
        return 1
    with open(path, "w") as fh:
        fh.write(text)
    print("  wrote    ", path)
    return 0


def main() raises:
    var a = argv()
    if len(a) < 2:
        raise Error("usage: gen_libero_family.mojo <suite> [--check]")
    var suite = String(a[1])
    var check = False
    for i in range(2, len(a)):
        if String(a[i]) == "--check":
            check = True
    var dir = String(BDDL_ROOT) + "/" + suite
    if not Path(dir).is_dir():
        raise Error("no suite directory " + dir)
    if not Path(String(PACK_DIR)).is_dir():
        raise Error("no LIBERO pack at " + PACK_DIR + " — run `pixi run assets-pull libero`")

    var table = load_libero_table(DEFAULT_TABLE_PATH)
    var files = _sorted_bddl(dir)
    if len(files) == 0:
        raise Error("no .bddl in " + dir)

    var fam = FamilySpec()
    var have_fam = False
    var narrowed = 0
    var tasks = List[String]()
    var task_texts = List[String]()
    var refused = List[String]()
    for i in range(len(files)):
        var text: String
        with open(files[i], "r") as fh:
            text = fh.read()
        var p = parse_bddl(text)
        var f = resolve_family(
            p, table, String(PACK_DIR), narrowed, String(LIBERO_ROBOT_DIR),
            String(LIBERO_ARENA_DIR),
        )
        f.name = suite
        var what = suite + ": " + _stem(files[i])
        # ⚠ THE FIRST FILE GOES THROUGH THE SAME MERGE as the other nine. Its
        # regions are re-merged into an empty table so that two names for one
        # rectangle INSIDE one file dedup too, and so that the rule that
        # produces the union is written once.
        var region_alias = List[RegionAlias]()
        if not have_fam:
            fam = f^
            have_fam = True
            var mine = List[RegionSpec]()
            for r in range(len(fam.regions)):
                mine.append(fam.regions[r])
            fam.regions = List[RegionSpec]()
            for r in range(len(mine)):
                _merge_region(fam, mine[r], what, region_alias)
        else:
            _union_slots(fam, f, what)
            for r in range(len(f.regions)):
                _merge_region(fam, f.regions[r], what, region_alias)
        if len(region_alias) > 0:
            print("  aliases", _stem(files[i]) + ":", end="")
            for k in range(len(region_alias)):
                print(
                    (" " if k == 0 else ", ") + region_alias[k].bddl + " -> "
                    + region_alias[k].family, end="",
                )
            print()
        var gap = classify_goal(p)
        if gap.kind != GAP_NONE:
            refused.append(_stem(files[i]) + ": " + gap_name(gap.kind))
            continue
        # ⚠ GOAL REGIONS FIRST. A `_zone` box added by a LATER file lands
        # after the earlier files' placement regions in the union; the
        # device table is `MAX_CURRICULUM_REGIONS` deep and a goal must
        # index it, so the union is re-sorted below before any task binds.
        # ⚠ TRANSLATION *AND* VALIDATION ARE BOTH REFUSALS, NOT CRASHES. A
        # task the family cannot validate — a free slot with no `init=`,
        # say, because its `:init` places it on a fixture site or on another
        # object — is one task the suite cannot express, and the suite's
        # other nine are still worth writing. Letting it escape aborted the
        # whole run and printed nothing about the other files.
        var t: TaskSpec
        try:
            t = translate_task(p, fam, table, String(PACK_DIR), region_alias)
            t.name = suite + "__" + _stem(files[i])
            t.family = suite
            validate_task_against_family(t, fam)
        except e:
            refused.append(_stem(files[i]) + ": " + String(e))
            continue
        tasks.append(t.name)
        task_texts.append(t.encode())

    # goal (box) regions first, placement regions after — see above
    var sorted_regions = List[RegionSpec]()
    for r in range(len(fam.regions)):
        if fam.regions[r].is_box:
            sorted_regions.append(fam.regions[r])
    for r in range(len(fam.regions)):
        if not fam.regions[r].is_box:
            sorted_regions.append(fam.regions[r])
    fam.regions = sorted_regions^
    for i in range(len(task_texts)):
        # re-validate against the final region order (indices are by name,
        # so the text is unchanged; this only re-checks it binds)
        _ = i

    var header = String(
        "# GENERATED by tools/tasks/gen_libero_family.mojo " + suite + "\n"
        "# from references/LIBERO-master/libero/libero/bddl_files/" + suite
        + " (" + String(len(files)) + " files), the libero asset pack, the\n"
        "# generated arenas and the vendored Panda. Do not edit; re-run the tool.\n"
        "# Fixture yaws taken at a narrow band's midpoint: " + String(narrowed)
        + " (see libero_import.FIXTURE_YAW_TOLERANCE).\n"
    )
    var stale = 0
    stale += _write_if_changed(
        String(FAMILY_DIR) + "/" + suite + ".family", header + fam.encode(), check
    )
    for i in range(len(tasks)):
        var th = String(
            "# GENERATED by tools/tasks/gen_libero_family.mojo " + suite
            + " — do not edit.\n"
        )
        stale += _write_if_changed(
            String(TASK_DIR) + "/" + tasks[i] + ".task", th + task_texts[i], check
        )
    print()
    print("  suite", suite + ":", len(files), "files ->", len(fam.slots),
          "slots (" + String(fam.n_free_slots()) + " free),",
          len(fam.regions), "regions;", len(tasks), "tasks written,",
          len(refused), "goals refused")
    for i in range(len(refused)):
        print("     refused:", refused[i])
    if check and stale > 0:
        raise Error(String(stale) + " generated file(s) stale")
