"""`libero_spatial` — LIBERO-Goal's ten tasks as ONE compile unit. L2.

    families/libero_spatial.family      GENERATED by tools/tasks/gen_libero_family.mojo
    scenes/libero_spatial.xml           composed from it (GENERATED, gen-family-scenes)
    libero_spatial_dims.mojo            read off MuJoCo (GENERATED, gen-dims, CI-checked)
    THIS FILE                        the comptime model def

The base is robosuite's Panda + PandaGripper + RethinkMount
(`envs/robots/assets/panda_robosuite.xml`, vendored by
`tools/robots/vendor_panda_robosuite.py`) at LIBERO's `base_pos`; slot 0 is
the styled tabletop arena; then two static fixtures (wooden cabinet with three
slide joints, flat stove with its button hinge) and five free objects (two black bowls, the cookie box, the ramekin, the plate).

⚠ FIVE FREE SLOTS, NOT FOUR — `libero_spatial` is the suite whose whole
premise is that the SAME bowl starts somewhere different in each of its ten
tasks, so it carries two `akita_black_bowl` instances plus three props.

⚠ `cone_type` IS ELLIPTIC, NOT PYRAMIDAL. robosuite's `base.xml` sets
`cone="elliptic" impratio="20"` and the composed scene inherits that
`<option>` (`inherit_option=1`). The SO-101 family runs pyramidal; this one
must not, or the friction model differs from the benchmark's.

⚠⚠ `max_contacts` WAS 64 AND THE SCENE PEAKS AT 228 — MEASURED, NOW GENERATED.
Five props landing at reset (`tools/tasks/libero_contact_budget.mojo`); the
batched env truncates at the cap silently. The budget is
`libero_envs/budgets.LIBERO_SPATIAL_MAX_CONTACTS` — see
`tools/tasks/gen_libero_envs.mojo` for the rule and what it does not prove.
"""

from mojo_rl.physics3d.parser import ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.tasks.libero_spatial_dims import LIBERO_SPATIAL_DIMS
from mojo_rl.tasks.libero_envs.budgets import LIBERO_SPATIAL_MAX_CONTACTS

comptime _pm = LIBERO_SPATIAL_DIMS

comptime LIBERO_SPATIAL_N_FREE_SLOTS: Int = 5
comptime LIBERO_SPATIAL_N_GOAL_WORDS: Int = 9
comptime LIBERO_SPATIAL_OBS_DIM: Int = (
    _pm.NQ + _pm.NV + LIBERO_SPATIAL_N_FREE_SLOTS + LIBERO_SPATIAL_N_GOAL_WORDS
)

comptime LiberoSpatialModel = ModelDefFromXML[
    xml_path="mojo_rl/tasks/scenes/libero_spatial.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    nsensor=_pm.NSENSOR, nsensordata=_pm.NSENSORDATA,
    neq=_pm.NEQ,
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    cone_type=ConeType.ELLIPTIC,
    max_contacts=LIBERO_SPATIAL_MAX_CONTACTS,
    obs_dim_override=LIBERO_SPATIAL_OBS_DIM,
    # ⚠ SEVEN, NOT THE NINE ACTUATORS — OSC_POSE's action, as in
    # `libero_goal_xml.mojo`. This said 9 until `test_libero_task_hooks`'s
    # per-family facts read it; no batched env had been built on this family,
    # so nothing had compiled the controller's `constrained` against it.
    action_dim_override=7,
]
