"""`libero_goal` — LIBERO-Goal's ten tasks as ONE compile unit. L2.

    families/libero_goal.family      GENERATED by tools/tasks/gen_libero_family.mojo
    scenes/libero_goal.xml           composed from it (GENERATED, gen-family-scenes)
    libero_goal_dims.mojo            read off MuJoCo (GENERATED, gen-dims, CI-checked)
    THIS FILE                        the comptime model def

The base is robosuite's Panda + PandaGripper + RethinkMount
(`envs/robots/assets/panda_robosuite.xml`, vendored by
`tools/robots/vendor_panda_robosuite.py`) at LIBERO's `base_pos`; slot 0 is
the styled tabletop arena; then three static fixtures (wooden cabinet with
three slide joints, flat stove with its button hinge, wine rack) and four
free objects (bowl, cream cheese, wine bottle, plate).

⚠ `cone_type` IS ELLIPTIC, NOT PYRAMIDAL. robosuite's `base.xml` sets
`cone="elliptic" impratio="20"` and the composed scene inherits that
`<option>` (`inherit_option=1`). The SO-101 family runs pyramidal; this one
must not, or the friction model differs from the benchmark's.

⚠ `max_contacts` IS A BUDGET, NOT A MEASUREMENT, exactly as
`so101_tabletop_xml.mojo` says of its own. 64 covers the Panda's gripper on
one object plus the object on the table with margin; it is the number to
revisit first if the batched env reports dropped contacts.
"""

from mojo_rl.physics3d.parser import ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.tasks.libero_goal_dims import LIBERO_GOAL_DIMS

comptime _pm = LIBERO_GOAL_DIMS

comptime LIBERO_GOAL_MAX_CONTACTS: Int = 64
comptime LIBERO_GOAL_N_FREE_SLOTS: Int = 4
comptime LIBERO_GOAL_N_GOAL_WORDS: Int = 9
comptime LIBERO_GOAL_OBS_DIM: Int = _pm.NQ + _pm.NV
"""The plain state, and NOT YET the task layer's words.

⚠⚠ THIS WAS `NQ + NV + N_FREE_SLOTS + N_GOAL_WORDS` AND NOTHING WROTE THE
EXTRA THIRTEEN. The model default writes `qpos ++ qvel` and stops, so an env
built on the wider figure would have reported thirteen constant zeros as
observation — a policy input that is always the same number, which trains
without error and cannot be told from a feature that happens not to matter.
`So101TabletopConfig.custom_extract_obs_gpu` is what fills those words for its
family (the per-slot active flag and pose, then the goal's own coordinates);
the LIBERO equivalent lands with the task hooks, and this constant grows again
in the same commit. Declaring a width nothing fills is the trap."""

comptime LiberoGoalModel = ModelDefFromXML[
    xml_path="mojo_rl/tasks/scenes/libero_goal.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    nsensor=_pm.NSENSOR, nsensordata=_pm.NSENSORDATA,
    neq=_pm.NEQ,
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    cone_type=ConeType.ELLIPTIC,
    max_contacts=LIBERO_GOAL_MAX_CONTACTS,
    obs_dim_override=LIBERO_GOAL_OBS_DIM,
    # ⚠⚠ SEVEN, NOT THE NINE ACTUATORS. LIBERO's policy emits OSC_POSE's
    # action — six end-effector pose deltas and one gripper word — and
    # `Phyics3dEnvConfig.HAS_OSC_CONTROLLER` maps it onto the model's nine
    # actuator commands. This said 9 while nothing drove the model; a config
    # with the controller on `constrained`s on it being 7, so the two cannot
    # drift apart silently.
    action_dim_override=7,
]
