"""`libero_object` — LIBERO-Object's ten tasks as ONE compile unit. L2.

    families/libero_object.family     GENERATED by tools/tasks/gen_libero_family.mojo
    scenes/libero_object.xml          composed from it (GENERATED, gen-family-scenes)
    libero_object_dims.mojo           read off MuJoCo (GENERATED, gen-dims, CI-checked)
    THIS FILE                         the comptime model def

⚠⚠ THE FIRST UNION FAMILY, and it is why this file exists at all. The suite's
ten `.bddl` files declare ELEVEN props between them and SEVEN each; the
family pools all eleven and every `.task` names its own seven plus the basket
with `active=`. So this ONE compile unit carries eleven free joints — nq 86,
nv 75, against `libero_goal`'s 46/37 — and each task parks the four props it
does not use (`gen_libero_family`'s header states the trade).

⚠ A DIFFERENT BASE AND A DIFFERENT FLOOR. `LIBERO_Floor_Manipulation` stands
the Panda on the ground with NO Rethink mount
(`panda_robosuite_nomount.xml`, `base_pos=-0.6,0,0`) and the props lie on the
arena's own floor plane (`floor=0`), not on a table 0.912 m up. Every z in
this family's region table is therefore near zero, and a resting height copied
from `libero_goal` would be a metre wrong.

⚠ THE GOAL REGION TRAVELS. All ten goals are `In(<prop>,
basket_1_contain_region)`, and `basket_1` is a FREE slot — the first family
whose goal box is attached to something that moves. `RegionSpec`'s header
promised that ("a region attached to a movable slot's site moves with that
slot"); `tests/tasks/test_libero_object.mojo` is where it is finally measured,
because a region silently frozen at the basket's reset pose would still pass
every task whose basket nobody pushes.

⚠ `cone_type` IS ELLIPTIC, NOT PYRAMIDAL. robosuite's `base.xml` sets
`cone="elliptic" impratio="20"` and the composed scene inherits that
`<option>` (`inherit_option=1`). The SO-101 family runs pyramidal; this one
must not, or the friction model differs from the benchmark's.

⚠ `max_contacts` IS A BUDGET, NOT A MEASUREMENT, and this family's is HIGHER
than its two siblings'. Eleven props on one floor plane rest in eleven
independent contact patches before the gripper touches anything, where
`libero_goal`'s four sit on a table; 96 covers that plus the gripper on one
object with margin. It is the number to revisit first if the batched env
reports dropped contacts.
"""

from mojo_rl.physics3d.parser import ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.tasks.libero_object_dims import LIBERO_OBJECT_DIMS

comptime _pm = LIBERO_OBJECT_DIMS

comptime LIBERO_OBJECT_MAX_CONTACTS: Int = 96
comptime LIBERO_OBJECT_N_FREE_SLOTS: Int = 11
comptime LIBERO_OBJECT_N_GOAL_WORDS: Int = 9
comptime LIBERO_OBJECT_OBS_DIM: Int = _pm.NQ + _pm.NV
"""The plain state, and NOT YET the task layer's words — see
`libero_goal_xml.LIBERO_GOAL_OBS_DIM` for why declaring a width nothing fills
is the trap. This constant grows with the task hooks, in their commit."""

comptime LiberoObjectModel = ModelDefFromXML[
    xml_path="mojo_rl/tasks/scenes/libero_object.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    nsensor=_pm.NSENSOR, nsensordata=_pm.NSENSORDATA,
    neq=_pm.NEQ,
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    cone_type=ConeType.ELLIPTIC,
    max_contacts=LIBERO_OBJECT_MAX_CONTACTS,
    obs_dim_override=LIBERO_OBJECT_OBS_DIM,
    # ⚠ SEVEN, NOT THE NINE ACTUATORS — OSC_POSE's action, as in
    # `libero_goal_xml.mojo`.
    action_dim_override=7,
]
