"""`libero_spatial` — LIBERO-Goal's ten tasks as ONE compile unit. L2.

    families/libero_spatial.family      GENERATED by tools/tasks/gen_libero_family.mojo
    scenes/libero_spatial.xml           composed from it (GENERATED, gen-family-scenes)
    libero_spatial_dims.mojo            read off MuJoCo (GENERATED, gen-dims, CI-checked)
    THIS FILE                        the comptime model def

The base is robosuite's Panda + PandaGripper + RethinkMount
(`envs/robots/assets/panda_robosuite.xml`, vendored by
`tools/robots/vendor_panda_robosuite.py`) at LIBERO's `base_pos`; slot 0 is
the styled tabletop arena; then two static fixtures (wooden cabinet with three
slide joints, flat stove with its button hinge) and five free objects (two black bowls, the cookie box, the ramekin, the plate).

⚠ FIVE FREE SLOTS, NOT FOUR — `libero_spatial` is the suite whose whole
premise is that the SAME bowl starts somewhere different in each of its ten
tasks, so it carries two `akita_black_bowl` instances plus three props.

⚠ `cone_type` IS ELLIPTIC, NOT PYRAMIDAL. robosuite's `base.xml` sets
`cone="elliptic" impratio="20"` and the composed scene inherits that
`<option>` (`inherit_option=1`). The SO-101 family runs pyramidal; this one
must not, or the friction model differs from the benchmark's.

⚠ `max_contacts` IS A BUDGET, NOT A MEASUREMENT, exactly as
`so101_tabletop_xml.mojo` says of its own. 64 covers the Panda's gripper on
one object plus the object on the table with margin; it is the number to
revisit first if the batched env reports dropped contacts.
"""

from mojo_rl.physics3d.parser import ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.tasks.libero_spatial_dims import LIBERO_SPATIAL_DIMS

comptime _pm = LIBERO_SPATIAL_DIMS

comptime LIBERO_SPATIAL_MAX_CONTACTS: Int = 64
comptime LIBERO_SPATIAL_N_FREE_SLOTS: Int = 5
comptime LIBERO_SPATIAL_N_GOAL_WORDS: Int = 9
comptime LIBERO_SPATIAL_OBS_DIM: Int = (
    _pm.NQ + _pm.NV + LIBERO_SPATIAL_N_FREE_SLOTS + LIBERO_SPATIAL_N_GOAL_WORDS
)

comptime LiberoSpatialModel = ModelDefFromXML[
    xml_path="mojo_rl/tasks/scenes/libero_spatial.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    nsensor=_pm.NSENSOR, nsensordata=_pm.NSENSORDATA,
    neq=_pm.NEQ,
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    cone_type=ConeType.ELLIPTIC,
    max_contacts=LIBERO_SPATIAL_MAX_CONTACTS,
    obs_dim_override=LIBERO_SPATIAL_OBS_DIM,
    action_dim_override=9,
]
