"""`libero_object` — LIBERO-Object's ten tasks as ONE compile unit. L2.

    families/libero_object.family     GENERATED by tools/tasks/gen_libero_family.mojo
    scenes/libero_object.xml          composed from it (GENERATED, gen-family-scenes)
    libero_object_dims.mojo           read off MuJoCo (GENERATED, gen-dims, CI-checked)
    THIS FILE                         the comptime model def

⚠⚠ THE FIRST UNION FAMILY, and it is why this file exists at all. The suite's
ten `.bddl` files declare ELEVEN props between them and SEVEN each; the
family pools all eleven and every `.task` names its own seven plus the basket
with `active=`. So this ONE compile unit carries eleven free joints — nq 86,
nv 75, against `libero_goal`'s 46/37 — and each task parks the four props it
does not use (`gen_libero_family`'s header states the trade).

⚠ A DIFFERENT BASE AND A DIFFERENT FLOOR. `LIBERO_Floor_Manipulation` stands
the Panda on the ground with NO Rethink mount
(`panda_robosuite_nomount.xml`, `base_pos=-0.6,0,0`) and the props lie on the
arena's own floor plane (`floor=0`), not on a table 0.912 m up. Every z in
this family's region table is therefore near zero, and a resting height copied
from `libero_goal` would be a metre wrong.

⚠ THE GOAL REGION TRAVELS. All ten goals are `In(<prop>,
basket_1_contain_region)`, and `basket_1` is a FREE slot — the first family
whose goal box is attached to something that moves. `RegionSpec`'s header
promised that ("a region attached to a movable slot's site moves with that
slot"); `tests/tasks/test_libero_object.mojo` is where it is finally measured,
because a region silently frozen at the basket's reset pose would still pass
every task whose basket nobody pushes.

⚠ `cone_type` IS ELLIPTIC, NOT PYRAMIDAL. robosuite's `base.xml` sets
`cone="elliptic" impratio="20"` and the composed scene inherits that
`<option>` (`inherit_option=1`). The SO-101 family runs pyramidal; this one
must not, or the friction model differs from the benchmark's.

⚠ `max_contacts` IS GENERATED FROM A MEASUREMENT, and it is a SAMPLED one.
The sampled resets peak at 68 (`tools/tasks/libero_contact_budget.mojo`); the
budget is `libero_envs/budgets.LIBERO_OBJECT_MAX_CONTACTS`. ⚠ LIBERO's OWN
frozen state is 204 contacts in MuJoCo (`test_libero_object`'s header) and there
is no init table for this suite on disk to measure it on ours, so a driver must
report saturated lanes rather than trust the number.
"""

from mojo_rl.physics3d.parser import ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.tasks.libero_object_dims import LIBERO_OBJECT_DIMS
from mojo_rl.tasks.libero_envs.budgets import LIBERO_OBJECT_MAX_CONTACTS

comptime _pm = LIBERO_OBJECT_DIMS

comptime LIBERO_OBJECT_N_FREE_SLOTS: Int = 11
comptime LIBERO_OBJECT_N_GOAL_WORDS: Int = 9
comptime LIBERO_OBJECT_OBS_DIM: Int = (
    _pm.NQ + _pm.NV + LIBERO_OBJECT_N_FREE_SLOTS + LIBERO_OBJECT_N_GOAL_WORDS
)
"""`task_hooks.write_task_obs`'s layout — see `libero_goal_xml.LIBERO_GOAL_OBS_DIM`
and `tests/tasks/test_libero_task_hooks.mojo`, which checks it against the
family's table on every LIBERO family."""

comptime LiberoObjectModel = ModelDefFromXML[
    xml_path="mojo_rl/tasks/scenes/libero_object.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    nsensor=_pm.NSENSOR, nsensordata=_pm.NSENSORDATA,
    neq=_pm.NEQ,
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    cone_type=ConeType.ELLIPTIC,
    # ⚠⚠ THE SCENE'S OWN MAX CONDIM (4: robosuite's finger pads), NOT THE
    # DEFAULT 3. Without it the batched solver clamps every finger-pad contact
    # to condim 3 and drops its TORSIONAL row — while the CPU replay leg
    # (`StudioIntegEll`, built at MAX_CONDIM 6) keeps it, so batch and CPU
    # disagreed on every grasp. Found by the blocked-solver work (§13.54).
    max_condim=_pm.MAX_CONDIM,
    max_contacts=LIBERO_OBJECT_MAX_CONTACTS,
    obs_dim_override=LIBERO_OBJECT_OBS_DIM,
    # ⚠ SEVEN, NOT THE NINE ACTUATORS — OSC_POSE's action, as in
    # `libero_goal_xml.mojo`.
    action_dim_override=7,
]
