"""`so101_tower` — the `so101-tower` rig's family as a COMPILE UNIT.

    families/so101_tower.family      the slot table (authored)
    scenes/so101_tower.xml           composed from it (GENERATED)
    so101_tower_dims.mojo            read off MuJoCo (GENERATED, CI-checked)
    placement/so101_tower.mojo       the device placement table (GENERATED)
    THIS FILE                        the comptime model def

The same shape as `so101_tabletop_xml.mojo`, and read that file's header
first: the fixed scene budget, the GPU leg as ONE monomorphisation, the
regeneration rule. What differs is the SCENE:

  * the base asset is `so_arm101_tower.xml` — the follower with the printed
    wrist-camera mount and the rig's `wrist_cam` (generated by
    `tools/soarm/bake_so_arm101_tower.py`, `docs/camera-rig.md` §4);
  * `tower`, a static slot: the overhead camera stand with `overhead_cam`;
  * `desk`, a static slot: the white mat the props rest on, at desk height;
  * `bowl` and `brick`, the two FREE slots of "grab the cube and put it in
    the bowl" — the recorded task (`projects/so101-tower/datasets/`).

Measured (MuJoCo 3.12.0): nbody 13, njnt 8, nq 20, nv 18, ngeom 52, ncam 2,
nsite 3, and **three kinematic trees with dof blocks [6, 6, 6]** — the arm
and one per free slot. Sparse `nC` 48 against a dense 324.

⚠ TWO CAMERAS, AND THEY ARE THE POINT. `ncam=2` is what the batched tracer
(`physics3d/raytrace`) renders per lane: camera 0 is `robot_wrist_cam` (on
the `gripper` body — composed through `mj_camlight`'s parent-body rule,
gated in `tests/robots/test_so_arm101_camera_vs_mujoco.mojo`), camera 1 is
`tower_overhead_cam` (on the static stand). `tests/tasks/
test_so101_tower_cameras.mojo` pins both world poses against MuJoCo.

⚠ TO CHANGE THE SLOT TABLE: edit the `.family`, then

    pixi run gen-family-scenes && pixi run gen-dims && pixi run gen-placement-tables
"""

from mojo_rl.physics3d.parser import ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.tasks.so101_tower_dims import SO101_TOWER_DIMS
from mojo_rl.tasks.task_hooks import TASK_GOAL_WORDS


comptime _pm = SO101_TOWER_DIMS

# ⚠ A BUDGET, AND NOT YET MEASURED ON THIS FAMILY — see the tabletop's note.
# Higher than the tabletop's 32 on purpose: the bowl is NINE boxes, and a brick
# resting in it touches the base box and up to two walls (each box pair can
# emit up to 8 contacts), before the gripper's meshes join in. Measure with
# `tools/tasks/libero_contact_budget.mojo`'s method once a policy grasps here.
comptime SO101_TOWER_MAX_CONTACTS: Int = 48

# ⚠ MEASURED ON THE COMPOSED SCENE, NOT COPIED FROM THE ARM.
# `tools/tasks/mesh_vertex_budget.mojo mojo_rl/tasks/scenes/so101_tower.xml`
# says what the collidable hulls need; this is that rounded up to a multiple
# of 512. The wrist camera mount is VISUAL ONLY (its hull filled the pinch —
# see the bake), so the collidable meshes are the stock arm's, as on the
# tabletop, plus nothing: the stand's meshes and the bowl's are visual too. A drift here is LOUD —
# `fields_build` raises rather than truncating a hull.
comptime SO101_TOWER_NMESH_VERTS: Int = 26624


# ── THE OBSERVATION'S WIDTH — the tabletop's layout, with TWO free slots ──
#
#   [0            .. NQ)               qpos, IN FULL (no floating base)
#   [NQ           .. NQ+NV)            qvel
#   [NQ+NV        .. NQ+NV+N_FREE)     1.0 if that free slot is active
#   [.. +TASK_GOAL_WORDS)              gripper, subject-gripper, target-subject
#
# `task_hooks.write_task_obs` writes it, over the generated placement table.
comptime SO101_TOWER_N_FREE_SLOTS: Int = 2
comptime SO101_TOWER_OBS_DIM: Int = (
    _pm.NQ + _pm.NV + SO101_TOWER_N_FREE_SLOTS + TASK_GOAL_WORDS
)

comptime So101TowerModel = ModelDefFromXML[
    xml_path="mojo_rl/tasks/scenes/so101_tower.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    nsensor=_pm.NSENSOR, nsensordata=_pm.NSENSORDATA,
    neq=_pm.NEQ,
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    cone_type=ConeType.PYRAMIDAL,
    max_contacts=SO101_TOWER_MAX_CONTACTS,
    obs_dim_override=SO101_TOWER_OBS_DIM,
    action_dim_override=6,
]
