"""TwoHot — DreamerV3 distributional value/reward head (pred + loss + bins).

Ports `embodied/jax/outs.py:TwoHot` and the `symexp_twohot` bin generator
in `embodied/jax/heads.py`. Used by the reward head and the value/slowvalue
heads (`output: symexp_twohot, bins: 255`).

  pred  = Σ_c softmax(logits)_c · bins_c            (squash = identity here)
  loss  = twohot cross-entropy: place `target` between its two nearest bins
          with weights ∝ inverse distance, then −Σ onehot·log_softmax(logits)

`bins` are passed in (loaded from a fixture in tests; generated by
`symexp_twohot_bins` in production). All CPU flat pointers; forward only
(PR5a) — backward is the trainer's job (PR5b).
"""

from std.math import exp, log, log1p, expm1

from mojo_rl.nn.constants import DT


# ──────────────────────────────────────────────────────────────────────
# DREAMER_REWARD_GRID_LO — single source of truth for the symexp-twohot
# reward/value grid lower bound (S4, 2026-06-07). The grid the reward
# head is TRAINED on (`TwoHotLoss.make` in wm_loss_ops.mojo) MUST equal
# the grid it is READ BACK on in imagination (`DreamerV3Trainer.bins`).
# These were two independent `-9.0` literals with long "MUST match"
# warnings; they previously diverged (-9 vs -20 default) → reward decoded
# ~5× small → imagined returns starved → non-convergence. One constant
# makes divergence impossible. If a future consumer needs a different
# scale, change it here (both sites follow).
# ──────────────────────────────────────────────────────────────────────
comptime DREAMER_REWARD_GRID_LO = -9.0


@always_inline
def _symexp(x: Scalar[DT]) -> Scalar[DT]:
    var s = Scalar[DT](1.0) if x >= Scalar[DT](0.0) else Scalar[DT](-1.0)
    var a = x if x >= Scalar[DT](0.0) else -x
    return s * expm1(a)


def symexp_twohot_bins[
    BINS: Int,
    bins_out_o: Origin[mut=True],
](
    bins_out: UnsafePointer[Scalar[DT], bins_out_o],
    lo: Scalar[DT] = Scalar[DT](-20.0),
):
    """Generate the `symexp_twohot` bins (assumes BINS odd, as 255).

    half = symexp(linspace(lo, 0, (BINS-1)//2 + 1));
    bins = concat([half, -half[:-1][::-1]]).

    `lo` is the linspace lower bound (default −20 = reference; the max bin is
    symexp(|lo|)). For small bounded-reward envs, a narrower `lo` keeps the
    twohot head from amplifying off-distribution errors into huge predictions
    (e.g. `lo=−9` → max bin ≈ 8102 vs `lo=−20` → 4.85e8).
    """
    comptime assert BINS % 2 == 1, "symexp_twohot_bins assumes odd BINS"
    comptime nhalf = (BINS - 1) // 2 + 1
    # half[i] = symexp(lo + |lo|*i/(nhalf-1)), i=0..nhalf-1  (ascending to 0)
    for i in range(nhalf):
        var lin = lo - lo * Scalar[DT](i) / Scalar[DT](nhalf - 1)
        bins_out[i] = _symexp(lin)
    # -half[:-1][::-1]: for j=0..nhalf-2, append -half[nhalf-2-j]
    for j in range(nhalf - 1):
        bins_out[nhalf + j] = -bins_out[(nhalf - 2) - j]


@always_inline
def twohot_pred[
    BINS: Int,
    logits_o: Origin[mut=True],
    bins_o: Origin[mut=True],
](
    logits: UnsafePointer[Scalar[DT], logits_o],
    base: Int,
    bins: UnsafePointer[Scalar[DT], bins_o],
) -> Scalar[DT]:
    """Σ_c softmax(logits[base:base+BINS])_c · bins_c."""
    var zmax = logits[base]
    for c in range(1, BINS):
        if logits[base + c] > zmax:
            zmax = logits[base + c]
    var ssum: Scalar[DT] = 0.0
    for c in range(BINS):
        ssum += exp(logits[base + c] - zmax)
    var inv = Scalar[DT](1.0) / ssum
    var acc: Scalar[DT] = 0.0
    for c in range(BINS):
        acc += exp(logits[base + c] - zmax) * inv * bins[c]
    return acc


@always_inline
def twohot_loss[
    BINS: Int,
    logits_o: Origin[mut=True],
    bins_o: Origin[mut=True],
](
    logits: UnsafePointer[Scalar[DT], logits_o],
    base: Int,
    bins: UnsafePointer[Scalar[DT], bins_o],
    target: Scalar[DT],
) -> Scalar[DT]:
    """Twohot cross-entropy of `target` against logits[base:base+BINS]."""
    # below = (#bins <= target) - 1 ; above = BINS - (#bins > target)
    var n_le = 0
    var n_gt = 0
    for c in range(BINS):
        if bins[c] <= target:
            n_le += 1
        else:
            n_gt += 1
    var below = n_le - 1
    var above = BINS - n_gt
    if below < 0:
        below = 0
    if below > BINS - 1:
        below = BINS - 1
    if above < 0:
        above = 0
    if above > BINS - 1:
        above = BINS - 1

    var w_below: Scalar[DT]
    var w_above: Scalar[DT]
    if below == above:
        # equal → dist_to_* both 1 → weights 0.5 each (matches reference).
        w_below = Scalar[DT](0.5)
        w_above = Scalar[DT](0.5)
    else:
        var db = bins[below] - target
        var da = bins[above] - target
        db = db if db >= Scalar[DT](0.0) else -db
        da = da if da >= Scalar[DT](0.0) else -da
        var total = db + da
        w_below = da / total
        w_above = db / total

    # log_softmax(logits)
    var zmax = logits[base]
    for c in range(1, BINS):
        if logits[base + c] > zmax:
            zmax = logits[base + c]
    var ssum: Scalar[DT] = 0.0
    for c in range(BINS):
        ssum += exp(logits[base + c] - zmax)
    var lse = zmax + log(ssum)
    var lp_below = logits[base + below] - lse
    var lp_above = logits[base + above] - lse
    return -(w_below * lp_below + w_above * lp_above)


@always_inline
def twohot_loss_backward[
    BINS: Int,
    logits_o: Origin[mut=True],
    bins_o: Origin[mut=True],
    grad_logits_o: Origin[mut=True],
](
    logits: UnsafePointer[Scalar[DT], logits_o],
    base: Int,
    bins: UnsafePointer[Scalar[DT], bins_o],
    target: Scalar[DT],
    upstream: Scalar[DT],
    grad_logits: UnsafePointer[Scalar[DT], grad_logits_o],
):
    """Accumulate `upstream · (softmax(logits) − twohot(target))` into
    grad_logits[base:base+BINS] (target detached; standard CE gradient)."""
    # below/above + weights (identical to forward).
    var n_le = 0
    for c in range(BINS):
        if bins[c] <= target:
            n_le += 1
    var below = n_le - 1
    var above = n_le            # BINS - (#bins > target) = n_le
    if below < 0:
        below = 0
    if below > BINS - 1:
        below = BINS - 1
    if above < 0:
        above = 0
    if above > BINS - 1:
        above = BINS - 1
    var w_below: Scalar[DT]
    var w_above: Scalar[DT]
    if below == above:
        w_below = Scalar[DT](0.5)
        w_above = Scalar[DT](0.5)
    else:
        var db = bins[below] - target
        var da = bins[above] - target
        db = db if db >= Scalar[DT](0.0) else -db
        da = da if da >= Scalar[DT](0.0) else -da
        var total = db + da
        w_below = da / total
        w_above = db / total
    # softmax(logits)
    var zmax = logits[base]
    for c in range(1, BINS):
        if logits[base + c] > zmax:
            zmax = logits[base + c]
    var ssum: Scalar[DT] = 0.0
    for c in range(BINS):
        ssum += exp(logits[base + c] - zmax)
    var inv = Scalar[DT](1.0) / ssum
    for c in range(BINS):
        grad_logits[base + c] += upstream * (exp(logits[base + c] - zmax) * inv)
    grad_logits[base + below] -= upstream * w_below
    grad_logits[base + above] -= upstream * w_above
