"""Dreamer 4 §6 — shortcut-forcing loss numerical parity vs PyTorch.

    pixi run mojo run -I . tests/nn/test_dreamer4_shortcut_loss_parity.mojo

Validates that our `dynamics_pretrain_loss` host arithmetic (corruption,
empirical-flow term, two-half bootstrap passes, b'/b''/v̄ stop-grad, ramp
weights, batch-weighted combine) matches the reference
`train_dynamics.py:dynamics_pretrain_loss` to ≈1e-5.

The transformer is replaced — in BOTH languages — by a deterministic affine
stub `out = ALPHA·z̃ + BETA`, so the three forward outputs (main, half1,
half2) reproduce exactly and the only quantity transferred from PyTorch is
the scalar loss. Inputs are generated by the SAME closed-form on each side.
The dynamics forward itself is validated separately (CPU↔GPU parity,
overfit). EXPECTED_* below come from the throwaway-venv fixture
/tmp/dreamer4_shortcut_fixture.py (verbatim reference loss):

    loss      = 0.0209311303
    loss_emp  = 0.0416286439
    loss_self = 0.0002336168
"""

from std.memory import alloc
from std.math import sin
from std.gpu.memory import AddressSpace
from std.gpu.host import DeviceContext
from std.testing import assert_true
from layout import TileTensor, row_major

from mojo_rl.nn.constants import DT
from mojo_rl.nn.core import Initializer, AMPPolicy, NoAMP
from mojo_rl.nn.initializer import Xavier
from mojo_rl.nn.core.module import Module, typed_view, typed_view_mut
from mojo_rl.deep_agents.dreamer4.shortcut_loss import (
    dynamics_pretrain_loss,
    ShortcutDynamics,
)


# ── deterministic affine stub: out = ALPHA·z + BETA (matches the fixture) ──
struct _AffineDyn[NSP: Int, DSP: Int](ShortcutDynamics):
    comptime ARITY: Int = 1
    comptime IN_DIMS = InlineArray[Int, 1](fill=Self.NSP * Self.DSP)
    comptime OUT_DIM = Self.NSP * Self.DSP
    comptime ALPHA = 0.7
    comptime BETA = 0.15

    def __init__(out self):
        pass

    @staticmethod
    def make[
        target: StaticString, INIT: Initializer
    ](ctx: Optional[DeviceContext] = None) raises -> Self:
        return Self()

    def set_indices(
        mut self,
        sig: UnsafePointer[Scalar[DT], MutAnyOrigin],
        step: UnsafePointer[Scalar[DT], MutAnyOrigin],
        batch: Int,
    ):
        pass

    def forward[
        target: StaticString, BATCH: Int, POLICY: AMPPolicy = NoAMP
    ](
        mut self,
        var *inputs: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC,
            element_size=1, origin=MutAnyOrigin, ...,
        ],
        mut output: TileTensor[
            mut=True, dtype=DT, address_space=AddressSpace.GENERIC,
            element_size=1, origin=MutAnyOrigin, ...,
        ],
    ) raises:
        var iv = typed_view[BATCH, Self.IN_DIMS[0]](inputs[0])
        var ov = typed_view_mut[BATCH, Self.OUT_DIM](output)
        var ip = rebind[UnsafePointer[Scalar[DT], MutAnyOrigin]](iv.ptr)
        var op = rebind[UnsafePointer[Scalar[DT], MutAnyOrigin]](ov.ptr)
        comptime N = BATCH * Self.OUT_DIM
        for k in range(N):
            op[k] = Scalar[DT](Self.ALPHA) * ip[k] + Scalar[DT](Self.BETA)

    def vjp[
        target: StaticString, BATCH: Int,
        POLICY: AMPPolicy = NoAMP, mode: StaticString = "all",
    ](
        mut self,
        grad_output: TileTensor[
            dtype=DT, address_space=AddressSpace.GENERIC,
            element_size=1, origin=MutAnyOrigin, ...,
        ],
        mut *grad_inputs: TileTensor[
            mut=True, dtype=DT, address_space=AddressSpace.GENERIC,
            element_size=1, origin=MutAnyOrigin, ...,
        ],
    ) raises:
        # Not exercised by this test (loss runs forwards only; the caller
        # owns vjp). Present to satisfy the Module trait.
        pass


def _alloc(n: Int) -> UnsafePointer[Scalar[DT], MutAnyOrigin]:
    return rebind[UnsafePointer[Scalar[DT], MutAnyOrigin]](alloc[Scalar[DT]](n))


def main() raises:
    print("=" * 70)
    print("Dreamer4 §6 — shortcut-forcing loss parity vs PyTorch")
    print("=" * 70)

    comptime B = 2
    comptime T = 2
    comptime NSP = 4         # Sz
    comptime DSP = 4         # Dz
    comptime B_SELF = 1
    comptime KMAX = 4
    comptime BF = B * T
    comptime ND = NSP * DSP
    comptime N = BF * ND

    comptime EXPECTED_LOSS = 0.0209311303

    var dyn = _AffineDyn[NSP, DSP].make[target="cpu", INIT=Xavier]()

    var z1 = _alloc(N)
    var z0 = _alloc(N)
    var sigma = _alloc(BF)
    var sidx = _alloc(BF)     # sigma_idx — ignored by the affine stub
    var pidx = _alloc(BF)     # step_idx
    for idx in range(N):
        z1[idx] = Scalar[DT](0.5 + 0.4 * sin(0.3 + 0.5 * Float64(idx)))
        z0[idx] = Scalar[DT](0.2 * sin(2.1 + 0.9 * Float64(idx)))

    # row0 = empirical (σ=0.4,0.6; step=emax=2), row1 = self (σ=0.3,0.4; step=1)
    sigma[0] = 0.4; sidx[0] = 0.0; pidx[0] = 2.0
    sigma[1] = 0.6; sidx[1] = 0.0; pidx[1] = 2.0
    sigma[2] = 0.3; sidx[2] = 0.0; pidx[2] = 1.0
    sigma[3] = 0.4; sidx[3] = 0.0; pidx[3] = 1.0

    var gz = _alloc(N)
    var zhat = _alloc(N)
    var loss = dynamics_pretrain_loss[
        type_of(dyn), B, T, B_SELF, NSP, DSP, KMAX
    ](dyn, z1, z0, sigma, sidx, pidx, True, gz, zhat)

    var dloss = abs(loss - EXPECTED_LOSS)
    print("  mojo loss     =", loss)
    print("  pytorch loss  =", EXPECTED_LOSS)
    print("  |Δ|           =", dloss)

    assert_true(dloss < 1e-5, "shortcut loss parity vs PyTorch")
    print("=" * 70)
    print("ALL PASSED — §6 shortcut-forcing loss parity (|Δ| < 1e-5)")
    print("=" * 70)
