"""Pin the numpy Mobius prototype as a machine-readable oracle (SWM Phase 0).

`scratch/swm_mobius_proto.py` is the exploratory prototype behind the §1.2
table of `docs/SHEAF_WORLD_MODELS_V2.md`. It prints French prose, which is a
bad thing to gate against. This script re-runs the *same* experiment, in the
same RNG consumption order, and writes two files the Mojo side can parse:

  tests/experimental/swm/reference/mobius_proto.txt   scalars + expected results
  tests/experimental/swm/reference/mobius_pairs.txt   the raw observation pairs

The pairs file is what makes the Phase 1 gate (G4) a real gate rather than a
statistical one: Mojo cannot reproduce numpy's PCG64 draws, but it *can* read
the exact same pairs and be required to land on the same fitted transports.
numpy fits them by SVD; the Mojo side fits them by Newton polar decomposition.
Two different algorithms, one answer — an independent implementation, not a
transcription.

Usage:
    pixi run python tools/swm/dump_mobius_reference.py

Regenerate only when the prototype's generative process changes; the output is
checked in and is the reference of record.
"""
import os
import sys

import numpy as np

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(_ROOT, "scratch"))

import swm_mobius_proto as proto  # noqa: E402

OUT_DIR = os.path.join(_ROOT, "tests", "experimental", "swm", "reference")
FORMAT_VERSION = 1
N_LOOPS = 4
SCALE_SIZES = [12, 24, 48, 96, 192]
BAD_EDGE = 5
BIAS_RAD = 0.3


def _fmt(x):
    """17 significant digits — round-trips a float64 exactly."""
    return repr(float(x))


def _mat_row(name, index, M):
    return f"{name} {index} " + " ".join(_fmt(v) for v in np.asarray(M).ravel())


def holonomy_stats(Rs):
    H = proto.holonomy(Rs)
    return H, float(np.linalg.det(H)), float(np.linalg.norm(H - np.eye(proto.d)))


def scale_table():
    """Noiseless Mobius rings of growing N: holonomy is O(1), lambda_2 ~ 1/N^2.

    Replicates the prototype's final section, including its RNG draws, so the
    numbers match the ones printed there.
    """
    rows = []
    for n in SCALE_SIZES:
        th = proto.rng.uniform(-0.6, 0.6, n)
        th[-1] = -th[:-1].sum()
        Rs = [proto.rot(t) for t in th]
        Rs[-1] = proto.REFL @ Rs[-1]
        H = np.eye(proto.d)
        for R in Rs:
            H = R @ H
        d = proto.d
        L = np.zeros((n * d, n * d))
        for i, R in enumerate(Rs):
            j = (i + 1) % n
            L[i * d:(i + 1) * d, i * d:(i + 1) * d] += R.T @ R
            L[j * d:(j + 1) * d, j * d:(j + 1) * d] += np.eye(d)
            L[i * d:(i + 1) * d, j * d:(j + 1) * d] += -R.T
            L[j * d:(j + 1) * d, i * d:(i + 1) * d] += -R
        lam = np.linalg.eigvalsh(L)
        rows.append(
            (n, float(np.linalg.norm(H - np.eye(d))), float(np.linalg.det(H)),
             float(lam[0]), float(lam[1]), 2.0 * (1.0 - np.cos(np.pi / n)))
        )
    return rows


def main():
    lines = []
    add = lines.append

    add("# SWM Mobius reference — generated by tools/swm/dump_mobius_reference.py")
    add("# Oracle for mojo_rl/experimental/swm/ Phase 1 gates. DO NOT EDIT BY HAND.")
    add("# Source: scratch/swm_mobius_proto.py (docs/SHEAF_WORLD_MODELS_V2.md §1.2)")
    add(f"format_version {FORMAT_VERSION}")
    add(f"numpy_version {np.__version__}")
    add(f"dim {proto.d}")
    add(f"ring_size {proto.N}")
    add(f"noise_std {_fmt(proto.NOISE)}")
    # Two independent noise draws per transition, variance NOISE^2 each: the
    # squared-residual floor a perfect fit cannot go below.
    add(f"noise_floor {_fmt(proto.d * proto.NOISE ** 2)}")
    add(f"n_loops {N_LOOPS}")

    # --- RNG order below must match scratch/swm_mobius_proto.py __main__ ------
    # 1. Mobius world + rollout
    r_true = proto.make_world(mobius=True)
    pairs, seqs = proto.rollout(r_true, n_loops=N_LOOPS)
    n_ep = len(seqs)
    add(f"n_episodes {n_ep}")
    add(f"pairs_per_edge {len(pairs[0])}")
    add(f"mobius_flip_edge {proto.N - 1}")

    for i, R in enumerate(r_true):
        add(_mat_row("world_mobius_true_r", i, R))

    # Model A: per-edge O(2) Procrustes, holonomy read and never optimized.
    fit_a = [proto.procrustes(p) for p in pairs]
    res_a = [float(proto.fit_edge_residual(pairs[i], fit_a[i])) for i in range(proto.N)]
    h_a, det_a, fro_a = holonomy_stats(fit_a)
    lce_a = proto.loop_closure_error(lambda i, x: fit_a[i] @ x, seqs, N_LOOPS)
    lam_a = np.linalg.eigvalsh(proto.sheaf_laplacian(fit_a))

    for i, R in enumerate(fit_a):
        add(_mat_row("fit_a_r", i, R))
    for i, r in enumerate(res_a):
        add(f"fit_a_residual {i} {_fmt(r)}")
    add("fit_a_holonomy " + " ".join(_fmt(v) for v in h_a.ravel()))
    add(f"fit_a_det_h {_fmt(det_a)}")
    add(f"fit_a_h_minus_i_fro {_fmt(fro_a)}")
    add(f"fit_a_residual_max {_fmt(max(res_a))}")
    add(f"fit_a_residual_median {_fmt(float(np.median(res_a)))}")
    add(f"fit_a_residual_max_over_median {_fmt(max(res_a) / float(np.median(res_a)))}")
    add(f"fit_a_lambda_1 {_fmt(float(lam_a[0]))}")
    add(f"fit_a_lambda_2 {_fmt(float(lam_a[1]))}")
    for k in range(1, N_LOOPS + 1):
        add(f"fit_a_closure_error {k} {_fmt(lce_a[k])}")

    # Model B: constant sheaf (single global frame, translations) — the parity
    # ablation. Odd laps must be ~7-10x worse than even ones.
    ts = proto.fit_translations(pairs)
    lce_b = proto.loop_closure_error(lambda i, x: x + ts[i], seqs, N_LOOPS)
    res_b = [
        float(np.mean([np.linalg.norm(p[1] - p[0] - ts[i]) ** 2 for p in pairs[i]]))
        for i in range(proto.N)
    ]
    for i, r in enumerate(res_b):
        add(f"fit_b_residual {i} {_fmt(r)}")
    add(f"fit_b_residual_max_over_median {_fmt(max(res_b) / float(np.median(res_b)))}")
    for k in range(1, N_LOOPS + 1):
        add(f"fit_b_closure_error {k} {_fmt(lce_b[k])}")

    # 2. Control D: orientable world, one NOISY sensor edge -> aberrant edge.
    r_ctl = proto.make_world(mobius=False)
    pairs_c, seqs_c = proto.rollout(r_ctl, n_loops=N_LOOPS, bad_edge=BAD_EDGE)
    fit_d = [proto.procrustes(p) for p in pairs_c]
    res_d = [float(proto.fit_edge_residual(pairs_c[i], fit_d[i])) for i in range(proto.N)]
    _, det_d, fro_d = holonomy_stats(fit_d)
    add(f"control_d_bad_edge {BAD_EDGE}")
    add(f"control_d_det_h {_fmt(det_d)}")
    add(f"control_d_h_minus_i_fro {_fmt(fro_d)}")
    for i, r in enumerate(res_d):
        add(f"control_d_residual {i} {_fmt(r)}")
    add(f"control_d_residual_max_over_median {_fmt(max(res_d) / float(np.median(res_d)))}")

    # 3. Control D': orientable world, one BIASED sensor edge -> coherent
    #    transport, nominal residuals, det = +1, non-trivial angle. This is the
    #    control that forces the continuous part of the holonomy to be reported
    #    as undecidable from a single cycle.
    r_bias = [R.copy() for R in r_ctl]
    r_bias[BAD_EDGE] = proto.rot(BIAS_RAD) @ r_bias[BAD_EDGE]
    pairs_b, seqs_b = proto.rollout(r_bias, n_loops=N_LOOPS)
    fit_db = [proto.procrustes(p) for p in pairs_b]
    res_db = [float(proto.fit_edge_residual(pairs_b[i], fit_db[i])) for i in range(proto.N)]
    _, det_db, fro_db = holonomy_stats(fit_db)
    add(f"control_dprime_bias_rad {_fmt(BIAS_RAD)}")
    add(f"control_dprime_det_h {_fmt(det_db)}")
    add(f"control_dprime_h_minus_i_fro {_fmt(fro_db)}")
    add(f"control_dprime_residual_max_over_median {_fmt(max(res_db) / float(np.median(res_db)))}")

    # 4. Scale table: holonomy is O(1) in N, lambda_2 = 2(1 - cos(pi/N)).
    add(f"scale_rows {len(SCALE_SIZES)}")
    for (n, fro, det, l1, l2, closed) in scale_table():
        add(
            f"scale_row {n} {_fmt(fro)} {_fmt(det)} {_fmt(l1)} {_fmt(l2)} {_fmt(closed)}"
        )

    os.makedirs(OUT_DIR, exist_ok=True)
    ref_path = os.path.join(OUT_DIR, "mobius_proto.txt")
    with open(ref_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    # Pairs, in a separate file so the reference of record stays readable.
    pair_lines = [
        "# SWM Mobius observation pairs — generated by tools/swm/dump_mobius_reference.py",
        "# One line per observed transition: pair <edge> <index> <x0> <x1> <y0> <y1>",
        "# with y ~ R_edge @ x + noise. DO NOT EDIT BY HAND.",
        f"format_version {FORMAT_VERSION}",
        f"ring_size {proto.N}",
        f"dim {proto.d}",
        f"pairs_per_edge {len(pairs[0])}",
    ]
    for i in range(proto.N):
        for j, (x, y) in enumerate(pairs[i]):
            pair_lines.append(
                f"pair {i} {j} {_fmt(x[0])} {_fmt(x[1])} {_fmt(y[0])} {_fmt(y[1])}"
            )
    pairs_path = os.path.join(OUT_DIR, "mobius_pairs.txt")
    with open(pairs_path, "w") as f:
        f.write("\n".join(pair_lines) + "\n")

    # Episode trajectories: needed to reproduce the loop-closure error, which
    # is the observable that separates model A from the translation ablation B
    # (7-10x parity gap at odd k). Rolled out for n_loops * N steps each.
    seq_lines = [
        "# SWM Mobius episode trajectories — generated by tools/swm/dump_mobius_reference.py",
        "# seq <episode> <step> <x0> <x1>, step in [0, n_loops*N]. DO NOT EDIT BY HAND.",
        f"format_version {FORMAT_VERSION}",
        f"n_episodes {n_ep}",
        f"steps_per_episode {N_LOOPS * proto.N + 1}",
        f"dim {proto.d}",
    ]
    for ep in range(n_ep):
        for t in range(seqs[ep].shape[0]):
            seq_lines.append(
                f"seq {ep} {t} " + " ".join(_fmt(v) for v in seqs[ep][t])
            )
    seqs_path = os.path.join(OUT_DIR, "mobius_seqs.txt")
    with open(seqs_path, "w") as f:
        f.write("\n".join(seq_lines) + "\n")
    print(f"wrote {seqs_path} ({len(seq_lines)} lines)")

    print(f"wrote {ref_path} ({len(lines)} lines)")
    print(f"wrote {pairs_path} ({len(pair_lines)} lines)")
    print()
    print("model A   det H = %+.3f   ||H-I||_F = %.3f   res max/median = %.1f"
          % (det_a, fro_a, max(res_a) / float(np.median(res_a))))
    print("          closure error k=1..4: "
          + ", ".join("%.3f" % lce_a[k] for k in range(1, N_LOOPS + 1)))
    print("model B   closure error k=1..4: "
          + ", ".join("%.3f" % lce_b[k] for k in range(1, N_LOOPS + 1))
          + "   (odd/even parity gap is the ablation's signature)")
    print("control D  det H = %+.3f   res max/median = %.1f"
          % (det_d, max(res_d) / float(np.median(res_d))))
    print("control D' det H = %+.3f   ||H-I||_F = %.3f   res max/median = %.1f"
          % (det_db, fro_db, max(res_db) / float(np.median(res_db))))


if __name__ == "__main__":
    main()
