"""The device reset's free-slot placement — one kernel, one table per family.

    from noeira.tasks.placement.table import PlacementTable, place_free_slots
    from noeira.tasks.placement.check import (
        require_device_placement, placement_table_drift,
    )
    from noeira.envs.libero.placement.libero_goal import LiberoGoalPlacement

`table.mojo` is the DEVICE half (the trait, the word encoding, the kernel) and
imports no spec parser beyond two constants; `check.mojo` is the HOST half that
refuses what the kernel cannot draw and diffs a table against its family. The
per-family tables are GENERATED by `tools/tasks/gen_placement_tables.mojo`
into each task root's `placement/` (`so101_tower` here, LIBERO's in
`noeira/envs/libero/placement/`).
"""
