"""SO-ARM100 (Standard Open Arm-100, 5 DOF + gripper) — model definition.

Reference: `references/mujoco_menagerie-main/trs_so_arm100/` — "Standard Open
Arm-100 5DOF v1.3", derived by the Menagerie maintainers from
`TheRobotStudio/SO-ARM100`'s URDF. Measured against the pixi MuJoCo runtime
(3.10.0): nbody 8, njnt 6 (all hinge, NO free joint), nq/nv/nu 6, ngeom 32
(23 mesh, 8 box, 1 plane), neq 0, ntendon 0, npair 0, nexclude 1, nkey 2.
See `docs/SO_ARM101_PORT_ASSESSMENT.md` for the full inventory.

TWO STRINGS, AND THE DIFFERENCE MATTERS:

  · `SO_ARM100_ROBOT_XML` — the robot and its floor, and NOTHING else. This is
    what `tests/robots/so_arm_ref.py` compiles against the reference MJCF and
    diffs across all 97 `mjModel` tables at tolerance 0.0. It is GENERATED by
    `tests/robots/so_arm_bake.py --inject`; do not hand-edit it.
  · `SO_ARM100_XML` — the above plus the reach task's target body, and the
    string the env actually builds. ALSO generated. The task fragment is kept
    OUT of the gated string on purpose: a target body changes `nbody`/`ngeom`
    and would make the layer-1 diff impossible, and "the gate had to be
    loosened to fit the task" is how a model stops being the reference model.

⚠ THE TASK BODY IS INLINED BY THE BAKE, NOT BY `merge_mjcf` (whose bug is
now FIXED; direct emission is kept for simplicity) — see
`so_arm101_xml.mojo` and `docs/PHYSICS3D_PARSER_GAPS_2026_08_13.md` §3. The
short version: `merge_mjcf` deletes a whole section when a COMMENT contains
that section's tag, because `_extract_section_inner` depth-counts raw text
without stripping comments. Nesting has nothing to do with it. Direct emission
is kept as one less dependency on that function.

⚠⚠ THREE DELIBERATE DEVIATIONS, all of them re-spellings of values MuJoCo
derives at compile time and our parser does not implement:

    <position inheritrange="1">  ->  explicit ctrlrange
    <position dampratio="1">     ->  explicit per-actuator kv
    (SO-101 only: fullinertia    ->  quat + diaginertia)

They fail in OPPOSITE directions if forgotten, and both read as tuning
problems rather than model bugs — without `inheritrange` the ctrlrange falls
back to the hardcoded +/-1 and `Pitch` (real range [-3.32, 0.174] rad) cannot
command most of its workspace; without `dampratio` kv defaults to 0 and the
servo rings instead of tracking. That is precisely why the layer-1 gate exists
and why the substituted numbers are read back out of `mjModel` at 17
significant digits rather than retyped.

⚠ `<keyframe>` IS IN THE XML AND IS IGNORED BY OUR PARSER (a real gap —
`docs/TODDLERBOT_PORT_PLAN.md` §4.6). It is left in so the layer-1 diff stays
honest; the two poses are ALSO baked into `so_arm100_config.mojo` as
`SO_ARM100_HOME` / `SO_ARM100_REST`, which is what the env actually resets to.
When `<keyframe>` lands, delete the baked copies rather than keeping both.

⚠ MESH COLLISION IS REAL HERE AND `NMESH_VERTS` IS NOT A HINT. Ten collidable
meshes totalling 2 456 MuJoCo hull vertices — but **2 551 of OURS**, which is what
the quantity to size against, see `sawyer_reach_config.mojo`'s note on getting
that wrong by 4.5x). `so_arm100_config.mojo` sets 2 560. A zero there silently
disables every mesh contact.

⚠ THE BARE ARM PRODUCES ZERO CONTACTS — measured, `ncon = 0` at both keyframes
and after 3 000 steps with the jaw driven shut. Contacts appear only once a
manipuland does (8 with one cube). A green reach gate therefore proves nothing
about the mesh path; do not read it as coverage.
"""

from mojo_rl.physics3d.parser import ModelDefFromXML
from mojo_rl.physics3d.types import ConeType
from mojo_rl.envs.robots.so_arm100_dims import SO_ARM100_DIMS


# --- BEGIN GENERATED XML (tests/robots/so_arm_bake.py) ---

# --- END GENERATED XML ---


comptime _pm = SO_ARM100_DIMS

comptime SoArm100Model = ModelDefFromXML[
    xml_path="mojo_rl/envs/robots/assets/so_arm100.xml",
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    neq=_pm.NEQ,
    # ⚠⚠ `nexclude` AND `npair` DEFAULT TO 0, AND THE DROP IS SILENT. Omitting
    # `nexclude` here left SO-100's `<exclude body1="Base"
    # body2="Rotation_Pitch"/>` unbuilt — `parse_xml` reported NEXCLUDE 1 while
    # the MODEL carried 0, so the two adjacent base geoms would have collided
    # with each other forever. Caught by printing the model's counts against
    # `parse_xml`'s, which is why `test_so_arm10x_vs_mujoco` asserts BOTH.
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    # `<option cone="elliptic" impratio="10"/>` — NOT our default. The
    # Menagerie authors chose it for no-slip grasping ("step 9" of their
    # derivation), and `opt.cone` is one of the fields the layer-1 gate
    # compares, so this is pinned rather than preferred.
    cone_type=ConeType.ELLIPTIC,
    # The bare arm reaches ncon = 0; one graspable cube reaches 8 (measured,
    # 4 000 steps). 16 leaves room for a second object without resizing, and
    # matches what manipulator uses.
    max_contacts=16,
    obs_dim_override=SO_ARM100_OBS_DIM,
    action_dim_override=6,
    # MuJoCo `m->nkey`: the `<keyframe>` has 2 `<key>` entries. The only model
    # in the tree with any. Asserted in `init_fields`.
    nkey = 2,
]

# Body indices, worldbody DFS order with world at 0 — MuJoCo's convention.
comptime BASE_BODY_IDX: Int = 1
comptime ROTATION_PITCH_BODY_IDX: Int = 2
comptime UPPER_ARM_BODY_IDX: Int = 3
comptime LOWER_ARM_BODY_IDX: Int = 4
comptime WRIST_BODY_IDX: Int = 5
comptime FIXED_JAW_BODY_IDX: Int = 6
comptime MOVING_JAW_BODY_IDX: Int = 7
comptime TARGET_BODY_IDX: Int = 8

# qpos/qvel addresses. Six hinges in XML order, so address == joint index.
comptime ROTATION_ADR: Int = 0
comptime PITCH_ADR: Int = 1
comptime ELBOW_ADR: Int = 2
comptime WRIST_PITCH_ADR: Int = 3
comptime WRIST_ROLL_ADR: Int = 4
comptime JAW_ADR: Int = 5

# obs = qpos(6) + qvel(6) + jaw_xyz(3) + target_xyz(3) + jaw_to_target(3)
comptime SO_ARM100_OBS_DIM: Int = 27

# Convex-hull vertex budget for the ten collidable meshes.
#
# ⚠⚠ SIZED FROM **OUR** HULL, NOT MUJOCO'S — and the two differ. MuJoCo's
# `mesh_graph` totals 2 456 vertices here; `fields_build` needs **2 551**.
# Our hull builder keeps ~4% more vertices than qhull does (26% more on
# SO-101), so a budget derived from `mjModel` UNDER-allocates. The way to get
# this number is to set it deliberately low and read the raise, which states
# the exact requirement — `load_mesh_hull` refuses to truncate rather than
# silently shrinking the collision shapes.
#
# ⚠ IT WAS BRIEFLY DTYPE-DEPENDENT, AND THAT WAS A BUG, NOT A PROPERTY. The
# hull ran in the runtime dtype, so float32 built a different one (2 636
# vertices against float64's 2 551) — different collision geometry in the
# renderer and the GPU batch than in every gate. The hull is constructed in
# float64 always now, so one number serves both;
# `test_convex_hull_dtype_invariance` keeps it that way.
#
# ⚠ NOT the raw STL total of 16 939 either; the hull is a small subset. See
# `sawyer_reach_config.mojo` on getting that wrong by 4.5x.
#
# ⚠⚠ RAISED 2560 -> 2746 WHEN TWO COLLISION MESHES CAME BACK. The `<mesh>`
# asset parser stopped at 16 entries, and this model declares 18, so
# `Moving_Jaw_Collision_2` and `_3` never reached the asset table:
# `mesh_id -1`, no hull, no collision geometry, and `rbound` left at the mesh
# default 0.5 against MuJoCo's 0.0279 and 0.0309. 2560 was measured with those
# two absent, so it was a budget for the wrong model. See `full_parser.mojo`'s
# mesh-asset loop.
comptime SO_ARM100_NMESH_VERTS: Int = 2746
