"""SO-ARM100 (Standard Open Arm-100, 5 DOF + gripper) — model definition.

Reference: `references/mujoco_menagerie-main/trs_so_arm100/` — "Standard Open
Arm-100 5DOF v1.3", derived by the Menagerie maintainers from
`TheRobotStudio/SO-ARM100`'s URDF. Measured against the pixi MuJoCo runtime
(3.10.0): nbody 8, njnt 6 (all hinge, NO free joint), nq/nv/nu 6, ngeom 32
(23 mesh, 8 box, 1 plane), neq 0, ntendon 0, npair 0, nexclude 1, nkey 2.
See `docs/SO_ARM101_PORT_ASSESSMENT.md` for the full inventory.

TWO STRINGS, AND THE DIFFERENCE MATTERS:

  · `SO_ARM100_ROBOT_XML` — the robot and its floor, and NOTHING else. This is
    what `tests/robots/so_arm_ref.py` compiles against the reference MJCF and
    diffs across all 97 `mjModel` tables at tolerance 0.0. It is GENERATED by
    `tests/robots/so_arm_bake.py --inject`; do not hand-edit it.
  · `SO_ARM100_XML` — the above plus the reach task's target body, and the
    string the env actually builds. ALSO generated. The task fragment is kept
    OUT of the gated string on purpose: a target body changes `nbody`/`ngeom`
    and would make the layer-1 diff impossible, and "the gate had to be
    loosened to fit the task" is how a model stops being the reference model.

⚠ THE TASK BODY IS INLINED BY THE BAKE, NOT BY `merge_mjcf` — see
`so_arm101_xml.mojo` and `docs/PHYSICS3D_PARSER_GAPS_2026_08_13.md` §3. The
short version: `merge_mjcf` deletes a whole section when a COMMENT contains
that section's tag, because `_extract_section_inner` depth-counts raw text
without stripping comments. Nesting has nothing to do with it. Direct emission
is kept as one less dependency on that function.

⚠⚠ THREE DELIBERATE DEVIATIONS, all of them re-spellings of values MuJoCo
derives at compile time and our parser does not implement:

    <position inheritrange="1">  ->  explicit ctrlrange
    <position dampratio="1">     ->  explicit per-actuator kv
    (SO-101 only: fullinertia    ->  quat + diaginertia)

They fail in OPPOSITE directions if forgotten, and both read as tuning
problems rather than model bugs — without `inheritrange` the ctrlrange falls
back to the hardcoded +/-1 and `Pitch` (real range [-3.32, 0.174] rad) cannot
command most of its workspace; without `dampratio` kv defaults to 0 and the
servo rings instead of tracking. That is precisely why the layer-1 gate exists
and why the substituted numbers are read back out of `mjModel` at 17
significant digits rather than retyped.

⚠ `<keyframe>` IS IN THE XML AND IS IGNORED BY OUR PARSER (a real gap —
`docs/TODDLERBOT_PORT_PLAN.md` §4.6). It is left in so the layer-1 diff stays
honest; the two poses are ALSO baked into `so_arm100_config.mojo` as
`SO_ARM100_HOME` / `SO_ARM100_REST`, which is what the env actually resets to.
When `<keyframe>` lands, delete the baked copies rather than keeping both.

⚠ MESH COLLISION IS REAL HERE AND `NMESH_VERTS` IS NOT A HINT. Ten collidable
meshes totalling 2 456 MuJoCo hull vertices — but **2 551 of OURS**, which is what
the quantity to size against, see `sawyer_reach_config.mojo`'s note on getting
that wrong by 4.5x). `so_arm100_config.mojo` sets 2 560. A zero there silently
disables every mesh contact.

⚠ THE BARE ARM PRODUCES ZERO CONTACTS — measured, `ncon = 0` at both keyframes
and after 3 000 steps with the jaw driven shut. Contacts appear only once a
manipuland does (8 with one cube). A green reach gate therefore proves nothing
about the mesh path; do not read it as coverage.
"""

from mojo_rl.physics3d.parser import parse_xml, ModelDefFromXML
from mojo_rl.physics3d.types import ConeType


# --- BEGIN GENERATED XML (tests/robots/so_arm_bake.py) ---
comptime SO_ARM100_ROBOT_XML = """<mujoco model="so_arm100">
  <compiler angle="radian" meshdir="mojo_rl/envs/robots/assets/so_arm100/"/>

  <option cone="elliptic" impratio="10"/>

  <asset>
    <material name="white" rgba="1 1 1 1"/>
    <material name="black" rgba="0.1 0.1 0.1 1"/>

    <mesh name="Base" file="Base.stl"/>
    <mesh name="Base_Motor" file="Base_Motor.stl"/>
    <mesh name="Rotation_Pitch" file="Rotation_Pitch.stl"/>
    <mesh name="Rotation_Pitch_Motor" file="Rotation_Pitch_Motor.stl"/>
    <mesh name="Upper_Arm" file="Upper_Arm.stl"/>
    <mesh name="Upper_Arm_Motor" file="Upper_Arm_Motor.stl"/>
    <mesh name="Lower_Arm" file="Lower_Arm.stl"/>
    <mesh name="Lower_Arm_Motor" file="Lower_Arm_Motor.stl"/>
    <mesh name="Wrist_Pitch_Roll" file="Wrist_Pitch_Roll.stl"/>
    <mesh name="Wrist_Pitch_Roll_Motor" file="Wrist_Pitch_Roll_Motor.stl"/>
    <mesh name="Fixed_Jaw" file="Fixed_Jaw.stl"/>
    <mesh name="Fixed_Jaw_Motor" file="Fixed_Jaw_Motor.stl"/>
    <mesh name="Fixed_Jaw_Collision_1" file="Fixed_Jaw_Collision_1.stl"/>
    <mesh name="Fixed_Jaw_Collision_2" file="Fixed_Jaw_Collision_2.stl"/>
    <mesh name="Moving_Jaw" file="Moving_Jaw.stl"/>
    <mesh name="Moving_Jaw_Collision_1" file="Moving_Jaw_Collision_1.stl"/>
    <mesh name="Moving_Jaw_Collision_2" file="Moving_Jaw_Collision_2.stl"/>
    <mesh name="Moving_Jaw_Collision_3" file="Moving_Jaw_Collision_3.stl"/>
    <!-- from trs_so_arm100/scene.xml -->
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
      markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
  </asset>

  <default>
    <default class="so_arm100">
      <joint frictionloss="0.1" armature="0.1"/>
      <position kp="50" forcerange="-3.5 3.5"/>  <!-- DEVIATION: dampratio -> per-actuator kv, see so_arm_bake.py -->
      <default class="Rotation">
        <joint axis="0 1 0" range="-1.92 1.92"/>
      </default>
      <default class="Pitch">
        <joint axis="1 0 0" range="-3.32 0.174"/>
      </default>
      <default class="Elbow">
        <joint axis="1 0 0" range="-0.174 3.14"/>
      </default>
      <default class="Wrist_Pitch">
        <joint axis="1 0 0" range="-1.66 1.66"/>
      </default>
      <default class="Wrist_Roll">
        <joint axis="0 1 0" range="-2.79 2.79"/>
      </default>
      <default class="Jaw">
        <joint axis="0 0 1" range="-0.174 1.75"/>
      </default>
      <default class="visual">
        <geom type="mesh" contype="0" conaffinity="0" density="0" group="2" material="white"/>
        <default class="motor_visual">
          <geom material="black"/>
        </default>
      </default>
      <default class="collision">
        <geom group="3" type="mesh" material="white"/>
        <default class="finger_collision">
          <geom type="box" solimp="2 1 0.01" solref="0.01 1" friction="1 0.005 0.0001"/>
        </default>
      </default>
    </default>
  </default>

  <worldbody>
    <body name="Base" childclass="so_arm100">
      <geom type="mesh" mesh="Base" class="visual"/>
      <geom type="mesh" mesh="Base_Motor" class="motor_visual"/>
      <geom type="mesh" mesh="Base" class="collision"/>
      <body name="Rotation_Pitch" pos="0 -0.0452 0.0165" quat="0.707105 0.707108 0 0">
        <inertial pos="-9.07886e-05 0.0590972 0.031089" quat="0.363978 0.441169 -0.623108 0.533504" mass="0.119226"
          diaginertia="5.94278e-05 5.89975e-05 3.13712e-05"/>
        <joint name="Rotation" class="Rotation"/>
        <geom type="mesh" mesh="Rotation_Pitch" class="visual"/>
        <geom type="mesh" mesh="Rotation_Pitch_Motor" class="motor_visual"/>
        <geom type="mesh" mesh="Rotation_Pitch" class="collision"/>
        <body name="Upper_Arm" pos="0 0.1025 0.0306" euler="1.57079 0 0">
          <inertial pos="-1.72052e-05 0.0701802 0.00310545" quat="0.50104 0.498994 -0.493562 0.50632" mass="0.162409"
            diaginertia="0.000213312 0.000167164 7.01522e-05"/>
          <joint name="Pitch" class="Pitch"/>
          <geom type="mesh" mesh="Upper_Arm" class="visual"/>
          <geom type="mesh" mesh="Upper_Arm_Motor" class="motor_visual"/>
          <geom type="mesh" mesh="Upper_Arm" class="collision"/>
          <body name="Lower_Arm" pos="0 0.11257 0.028" euler="-1.57079 0 0">
            <inertial pos="-0.00339604 0.00137796 0.0768007" quat="0.701995 0.0787996 0.0645626 0.704859"
              mass="0.147968" diaginertia="0.000138803 0.000107748 4.84242e-05"/>
            <joint name="Elbow" class="Elbow"/>
            <geom type="mesh" mesh="Lower_Arm" class="visual"/>
            <geom type="mesh" mesh="Lower_Arm_Motor" class="motor_visual"/>
            <geom type="mesh" mesh="Lower_Arm" class="collision"/>
            <body name="Wrist_Pitch_Roll" pos="0 0.0052 0.1349" euler="-1.57079 0 0">
              <inertial pos="-0.00852653 -0.0352279 -2.34622e-05" quat="-0.0522806 0.705235 0.0549524 0.704905"
                mass="0.0661321" diaginertia="3.45403e-05 2.39041e-05 1.94704e-05"/>
              <joint name="Wrist_Pitch" class="Wrist_Pitch"/>
              <geom type="mesh" mesh="Wrist_Pitch_Roll" class="visual"/>
              <geom type="mesh" mesh="Wrist_Pitch_Roll_Motor" class="motor_visual"/>
              <geom type="mesh" mesh="Wrist_Pitch_Roll" class="collision"/>
              <body name="Fixed_Jaw" pos="0 -0.0601 0" euler="0 1.57079 0">
                <inertial pos="0.00552377 -0.0280167 0.000483583" quat="0.41836 0.620891 -0.350644 0.562599"
                  mass="0.0929859" diaginertia="5.03136e-05 4.64098e-05 2.72961e-05"/>
                <joint name="Wrist_Roll" class="Wrist_Roll"/>
                <geom type="mesh" mesh="Fixed_Jaw" class="visual"/>
                <geom type="mesh" mesh="Fixed_Jaw_Motor" class="motor_visual"/>
                <geom type="mesh" mesh="Fixed_Jaw_Collision_1" class="collision"/>
                <geom type="mesh" mesh="Fixed_Jaw_Collision_2" class="collision"/>
                <geom class="finger_collision" name="fixed_jaw_pad_1" size="0.001 0.005 0.004" pos="0.0089 -0.1014 0"/>
                <geom class="finger_collision" name="fixed_jaw_pad_2" size="0.001 0.005 0.006" pos="0.0109 -0.0914 0"/>
                <geom class="finger_collision" name="fixed_jaw_pad_3" size="0.001 0.01 0.007" pos="0.0126 -0.0768 0"/>
                <geom class="finger_collision" name="fixed_jaw_pad_4" size="0.001 0.01 0.008" pos="0.0143 -0.0572 0"/>
                <body name="Moving_Jaw" pos="-0.0202 -0.0244 0" quat="1.34924e-11 -3.67321e-06 1 -3.67321e-06">
                  <inertial pos="-0.00161745 -0.0303473 0.000449646" quat="0.696562 0.716737 -0.0239844 -0.0227026"
                    mass="0.0202444" diaginertia="1.11265e-05 8.99651e-06 2.99548e-06"/>
                  <joint name="Jaw" class="Jaw"/>
                  <geom type="mesh" mesh="Moving_Jaw" class="visual"/>
                  <geom type="mesh" mesh="Moving_Jaw_Collision_1" class="collision"/>
                  <geom type="mesh" mesh="Moving_Jaw_Collision_2" class="collision"/>
                  <geom type="mesh" mesh="Moving_Jaw_Collision_3" class="collision"/>
                  <geom class="finger_collision" name="moving_jaw_pad_1" size="0.001 0.005 0.004"
                    pos="-0.0113 -0.077 0"/>
                  <geom class="finger_collision" name="moving_jaw_pad_2" size="0.001 0.005 0.006"
                    pos="-0.0093 -0.067 0"/>
                  <geom class="finger_collision" name="moving_jaw_pad_3" size="0.001 0.01 0.006"
                    pos="-0.0073 -0.055 0"/>
                  <geom class="finger_collision" name="moving_jaw_pad_4" size="0.001 0.01 0.008"
                    pos="-0.0073 -0.035 0"/>
                </body>
              </body>
            </body>
          </body>
        </body>
      </body>
    </body>
    <!-- from trs_so_arm100/scene.xml -->
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
  </worldbody>

  <actuator>
    <position class="Rotation"  joint="Rotation" name="Rotation" kv="5.12815011462096" ctrlrange="-1.92 1.92"/>
    <position class="Pitch"  joint="Pitch" name="Pitch" kv="5.0017601635440885" ctrlrange="-3.32 0.17399999999999993"/>
    <position class="Elbow"  joint="Elbow" name="Elbow" kv="4.666305248385883" ctrlrange="-0.17399999999999993 3.14"/>
    <position class="Wrist_Pitch"  joint="Wrist_Pitch" name="Wrist_Pitch" kv="4.497993395502867" ctrlrange="-1.66 1.66"/>
    <position class="Wrist_Roll"  joint="Wrist_Roll" name="Wrist_Roll" kv="4.473104837677079" ctrlrange="-2.79 2.79"/>
    <position class="Jaw"  joint="Jaw" name="Jaw" kv="4.472755053189025" ctrlrange="-0.17399999999999993 1.75"/>
  </actuator>

  <contact>
    <exclude body1="Base" body2="Rotation_Pitch"/>
  </contact>

  <keyframe>
    <key name="home" qpos="0 -1.57 1.57 1.57 -1.57 0" ctrl="0 -1.57 1.57 1.57 -1.57 0"/>
    <key name="rest" qpos="0 -3.32 3.11 1.18 0 -0.174" ctrl="0 -3.32 3.11 1.18 0 -0.174"/>
  </keyframe>
</mujoco>
"""

comptime SO_ARM100_XML = """<mujoco model="so_arm100">
  <compiler angle="radian" meshdir="mojo_rl/envs/robots/assets/so_arm100/"/>

  <option cone="elliptic" impratio="10"/>

  <asset>
    <material name="white" rgba="1 1 1 1"/>
    <material name="black" rgba="0.1 0.1 0.1 1"/>

    <mesh name="Base" file="Base.stl"/>
    <mesh name="Base_Motor" file="Base_Motor.stl"/>
    <mesh name="Rotation_Pitch" file="Rotation_Pitch.stl"/>
    <mesh name="Rotation_Pitch_Motor" file="Rotation_Pitch_Motor.stl"/>
    <mesh name="Upper_Arm" file="Upper_Arm.stl"/>
    <mesh name="Upper_Arm_Motor" file="Upper_Arm_Motor.stl"/>
    <mesh name="Lower_Arm" file="Lower_Arm.stl"/>
    <mesh name="Lower_Arm_Motor" file="Lower_Arm_Motor.stl"/>
    <mesh name="Wrist_Pitch_Roll" file="Wrist_Pitch_Roll.stl"/>
    <mesh name="Wrist_Pitch_Roll_Motor" file="Wrist_Pitch_Roll_Motor.stl"/>
    <mesh name="Fixed_Jaw" file="Fixed_Jaw.stl"/>
    <mesh name="Fixed_Jaw_Motor" file="Fixed_Jaw_Motor.stl"/>
    <mesh name="Fixed_Jaw_Collision_1" file="Fixed_Jaw_Collision_1.stl"/>
    <mesh name="Fixed_Jaw_Collision_2" file="Fixed_Jaw_Collision_2.stl"/>
    <mesh name="Moving_Jaw" file="Moving_Jaw.stl"/>
    <mesh name="Moving_Jaw_Collision_1" file="Moving_Jaw_Collision_1.stl"/>
    <mesh name="Moving_Jaw_Collision_2" file="Moving_Jaw_Collision_2.stl"/>
    <mesh name="Moving_Jaw_Collision_3" file="Moving_Jaw_Collision_3.stl"/>
    <!-- from trs_so_arm100/scene.xml -->
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
      markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
  </asset>

  <default>
    <default class="so_arm100">
      <joint frictionloss="0.1" armature="0.1"/>
      <position kp="50" forcerange="-3.5 3.5"/>  <!-- DEVIATION: dampratio -> per-actuator kv, see so_arm_bake.py -->
      <default class="Rotation">
        <joint axis="0 1 0" range="-1.92 1.92"/>
      </default>
      <default class="Pitch">
        <joint axis="1 0 0" range="-3.32 0.174"/>
      </default>
      <default class="Elbow">
        <joint axis="1 0 0" range="-0.174 3.14"/>
      </default>
      <default class="Wrist_Pitch">
        <joint axis="1 0 0" range="-1.66 1.66"/>
      </default>
      <default class="Wrist_Roll">
        <joint axis="0 1 0" range="-2.79 2.79"/>
      </default>
      <default class="Jaw">
        <joint axis="0 0 1" range="-0.174 1.75"/>
      </default>
      <default class="visual">
        <geom type="mesh" contype="0" conaffinity="0" density="0" group="2" material="white"/>
        <default class="motor_visual">
          <geom material="black"/>
        </default>
      </default>
      <default class="collision">
        <geom group="3" type="mesh" material="white"/>
        <default class="finger_collision">
          <geom type="box" solimp="2 1 0.01" solref="0.01 1" friction="1 0.005 0.0001"/>
        </default>
      </default>
    </default>
  </default>

  <worldbody>
    <body name="Base" childclass="so_arm100">
      <geom type="mesh" mesh="Base" class="visual"/>
      <geom type="mesh" mesh="Base_Motor" class="motor_visual"/>
      <geom type="mesh" mesh="Base" class="collision"/>
      <body name="Rotation_Pitch" pos="0 -0.0452 0.0165" quat="0.707105 0.707108 0 0">
        <inertial pos="-9.07886e-05 0.0590972 0.031089" quat="0.363978 0.441169 -0.623108 0.533504" mass="0.119226"
          diaginertia="5.94278e-05 5.89975e-05 3.13712e-05"/>
        <joint name="Rotation" class="Rotation"/>
        <geom type="mesh" mesh="Rotation_Pitch" class="visual"/>
        <geom type="mesh" mesh="Rotation_Pitch_Motor" class="motor_visual"/>
        <geom type="mesh" mesh="Rotation_Pitch" class="collision"/>
        <body name="Upper_Arm" pos="0 0.1025 0.0306" euler="1.57079 0 0">
          <inertial pos="-1.72052e-05 0.0701802 0.00310545" quat="0.50104 0.498994 -0.493562 0.50632" mass="0.162409"
            diaginertia="0.000213312 0.000167164 7.01522e-05"/>
          <joint name="Pitch" class="Pitch"/>
          <geom type="mesh" mesh="Upper_Arm" class="visual"/>
          <geom type="mesh" mesh="Upper_Arm_Motor" class="motor_visual"/>
          <geom type="mesh" mesh="Upper_Arm" class="collision"/>
          <body name="Lower_Arm" pos="0 0.11257 0.028" euler="-1.57079 0 0">
            <inertial pos="-0.00339604 0.00137796 0.0768007" quat="0.701995 0.0787996 0.0645626 0.704859"
              mass="0.147968" diaginertia="0.000138803 0.000107748 4.84242e-05"/>
            <joint name="Elbow" class="Elbow"/>
            <geom type="mesh" mesh="Lower_Arm" class="visual"/>
            <geom type="mesh" mesh="Lower_Arm_Motor" class="motor_visual"/>
            <geom type="mesh" mesh="Lower_Arm" class="collision"/>
            <body name="Wrist_Pitch_Roll" pos="0 0.0052 0.1349" euler="-1.57079 0 0">
              <inertial pos="-0.00852653 -0.0352279 -2.34622e-05" quat="-0.0522806 0.705235 0.0549524 0.704905"
                mass="0.0661321" diaginertia="3.45403e-05 2.39041e-05 1.94704e-05"/>
              <joint name="Wrist_Pitch" class="Wrist_Pitch"/>
              <geom type="mesh" mesh="Wrist_Pitch_Roll" class="visual"/>
              <geom type="mesh" mesh="Wrist_Pitch_Roll_Motor" class="motor_visual"/>
              <geom type="mesh" mesh="Wrist_Pitch_Roll" class="collision"/>
              <body name="Fixed_Jaw" pos="0 -0.0601 0" euler="0 1.57079 0">
                <inertial pos="0.00552377 -0.0280167 0.000483583" quat="0.41836 0.620891 -0.350644 0.562599"
                  mass="0.0929859" diaginertia="5.03136e-05 4.64098e-05 2.72961e-05"/>
                <joint name="Wrist_Roll" class="Wrist_Roll"/>
                <geom type="mesh" mesh="Fixed_Jaw" class="visual"/>
                <geom type="mesh" mesh="Fixed_Jaw_Motor" class="motor_visual"/>
                <geom type="mesh" mesh="Fixed_Jaw_Collision_1" class="collision"/>
                <geom type="mesh" mesh="Fixed_Jaw_Collision_2" class="collision"/>
                <geom class="finger_collision" name="fixed_jaw_pad_1" size="0.001 0.005 0.004" pos="0.0089 -0.1014 0"/>
                <geom class="finger_collision" name="fixed_jaw_pad_2" size="0.001 0.005 0.006" pos="0.0109 -0.0914 0"/>
                <geom class="finger_collision" name="fixed_jaw_pad_3" size="0.001 0.01 0.007" pos="0.0126 -0.0768 0"/>
                <geom class="finger_collision" name="fixed_jaw_pad_4" size="0.001 0.01 0.008" pos="0.0143 -0.0572 0"/>
                <body name="Moving_Jaw" pos="-0.0202 -0.0244 0" quat="1.34924e-11 -3.67321e-06 1 -3.67321e-06">
                  <inertial pos="-0.00161745 -0.0303473 0.000449646" quat="0.696562 0.716737 -0.0239844 -0.0227026"
                    mass="0.0202444" diaginertia="1.11265e-05 8.99651e-06 2.99548e-06"/>
                  <joint name="Jaw" class="Jaw"/>
                  <geom type="mesh" mesh="Moving_Jaw" class="visual"/>
                  <geom type="mesh" mesh="Moving_Jaw_Collision_1" class="collision"/>
                  <geom type="mesh" mesh="Moving_Jaw_Collision_2" class="collision"/>
                  <geom type="mesh" mesh="Moving_Jaw_Collision_3" class="collision"/>
                  <geom class="finger_collision" name="moving_jaw_pad_1" size="0.001 0.005 0.004"
                    pos="-0.0113 -0.077 0"/>
                  <geom class="finger_collision" name="moving_jaw_pad_2" size="0.001 0.005 0.006"
                    pos="-0.0093 -0.067 0"/>
                  <geom class="finger_collision" name="moving_jaw_pad_3" size="0.001 0.01 0.006"
                    pos="-0.0073 -0.055 0"/>
                  <geom class="finger_collision" name="moving_jaw_pad_4" size="0.001 0.01 0.008"
                    pos="-0.0073 -0.035 0"/>
                </body>
              </body>
            </body>
          </body>
        </body>
      </body>
    </body>
    <!-- from trs_so_arm100/scene.xml -->
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
    <body name="target" mocap="true" pos="0 -0.25 0.15">
      <geom name="target" type="sphere" size="0.012" rgba="0.9 0.1 0.1 0.6"
            contype="0" conaffinity="0" group="1"/>
    </body>
  </worldbody>

  <actuator>
    <position class="Rotation"  joint="Rotation" name="Rotation" kv="5.12815011462096" ctrlrange="-1.92 1.92"/>
    <position class="Pitch"  joint="Pitch" name="Pitch" kv="5.0017601635440885" ctrlrange="-3.32 0.17399999999999993"/>
    <position class="Elbow"  joint="Elbow" name="Elbow" kv="4.666305248385883" ctrlrange="-0.17399999999999993 3.14"/>
    <position class="Wrist_Pitch"  joint="Wrist_Pitch" name="Wrist_Pitch" kv="4.497993395502867" ctrlrange="-1.66 1.66"/>
    <position class="Wrist_Roll"  joint="Wrist_Roll" name="Wrist_Roll" kv="4.473104837677079" ctrlrange="-2.79 2.79"/>
    <position class="Jaw"  joint="Jaw" name="Jaw" kv="4.472755053189025" ctrlrange="-0.17399999999999993 1.75"/>
  </actuator>

  <contact>
    <exclude body1="Base" body2="Rotation_Pitch"/>
  </contact>

  <keyframe>
    <key name="home" qpos="0 -1.57 1.57 1.57 -1.57 0" ctrl="0 -1.57 1.57 1.57 -1.57 0"/>
    <key name="rest" qpos="0 -3.32 3.11 1.18 0 -0.174" ctrl="0 -3.32 3.11 1.18 0 -0.174"/>
  </keyframe>
</mujoco>
"""
# --- END GENERATED XML ---


comptime _pm = parse_xml(SO_ARM100_XML)

comptime SoArm100Model = ModelDefFromXML[
    xml=SO_ARM100_XML,
    nbody=_pm.NBODY,
    njoint=_pm.NJOINT,
    nq=_pm.NQ,
    nv=_pm.NV,
    ngeom=_pm.NGEOM,
    nact=_pm.NACT,
    ntex=_pm.NTEX,
    nmat=_pm.NMAT,
    nlight=_pm.NLIGHT,
    ncam=_pm.NCAM,
    nsite=_pm.NSITE,
    neq=_pm.NEQ,
    # ⚠⚠ `nexclude` AND `npair` DEFAULT TO 0, AND THE DROP IS SILENT. Omitting
    # `nexclude` here left SO-100's `<exclude body1="Base"
    # body2="Rotation_Pitch"/>` unbuilt — `parse_xml` reported NEXCLUDE 1 while
    # the MODEL carried 0, so the two adjacent base geoms would have collided
    # with each other forever. Caught by printing the model's counts against
    # `parse_xml`'s, which is why `test_so_arm10x_vs_mujoco` asserts BOTH.
    nexclude=_pm.NEXCLUDE,
    npair=_pm.NPAIR,
    timestep=_pm.TIMESTEP,
    # `<option cone="elliptic" impratio="10"/>` — NOT our default. The
    # Menagerie authors chose it for no-slip grasping ("step 9" of their
    # derivation), and `opt.cone` is one of the fields the layer-1 gate
    # compares, so this is pinned rather than preferred.
    cone_type=ConeType.ELLIPTIC,
    # The bare arm reaches ncon = 0; one graspable cube reaches 8 (measured,
    # 4 000 steps). 16 leaves room for a second object without resizing, and
    # matches what manipulator uses.
    max_contacts=16,
    obs_dim_override=SO_ARM100_OBS_DIM,
    action_dim_override=6,
]

# Body indices, worldbody DFS order with world at 0 — MuJoCo's convention.
comptime BASE_BODY_IDX: Int = 1
comptime ROTATION_PITCH_BODY_IDX: Int = 2
comptime UPPER_ARM_BODY_IDX: Int = 3
comptime LOWER_ARM_BODY_IDX: Int = 4
comptime WRIST_BODY_IDX: Int = 5
comptime FIXED_JAW_BODY_IDX: Int = 6
comptime MOVING_JAW_BODY_IDX: Int = 7
comptime TARGET_BODY_IDX: Int = 8

# qpos/qvel addresses. Six hinges in XML order, so address == joint index.
comptime ROTATION_ADR: Int = 0
comptime PITCH_ADR: Int = 1
comptime ELBOW_ADR: Int = 2
comptime WRIST_PITCH_ADR: Int = 3
comptime WRIST_ROLL_ADR: Int = 4
comptime JAW_ADR: Int = 5

# obs = qpos(6) + qvel(6) + jaw_xyz(3) + target_xyz(3) + jaw_to_target(3)
comptime SO_ARM100_OBS_DIM: Int = 21

# Convex-hull vertex budget for the ten collidable meshes.
#
# ⚠⚠ SIZED FROM **OUR** HULL, NOT MUJOCO'S — and the two differ. MuJoCo's
# `mesh_graph` totals 2 456 vertices here; `fields_build` needs **2 551**.
# Our hull builder keeps ~4% more vertices than qhull does (26% more on
# SO-101), so a budget derived from `mjModel` UNDER-allocates. The way to get
# this number is to set it deliberately low and read the raise, which states
# the exact requirement — `load_mesh_hull` refuses to truncate rather than
# silently shrinking the collision shapes.
#
# ⚠ NOT the raw STL total of 16 939 either; the hull is a small subset. See
# `sawyer_reach_config.mojo` on getting that wrong by 4.5x.
comptime SO_ARM100_NMESH_VERTS: Int = 2560
