"""MBPO Agent GPU Training on Humanoid.

This trains the MBPO (Model-Based Policy Optimization) agent on the Humanoid
environment using GPU-accelerated training with:
- GPU environment stepping (with early termination on unhealthy state)
- GPU SAC gradient updates
- GPU dynamics ensemble training (7 networks, 5 elites)
- GPU branched model rollouts from real states

Humanoid terminates early when torso z-position leaves [1.0, 2.0]. No
Humanoid-specific termination function exists for model rollouts, so
NeverTerminate is used (matching Walker2d / HalfCheetah / Swimmer). With
k=1 rollouts the impact of the mismatch is small.

Humanoid is high-dimensional (45D obs, 17D action) — SAC's maximum entropy
formulation benefits from the extra data generated by the learned model.

Run with:
    pixi run -e apple mojo run -I . examples/humanoid/mbpo_humanoid_training_gpu.mojo    # Apple Silicon
    pixi run -e nvidia mojo run -I . examples/humanoid/mbpo_humanoid_training_gpu.mojo   # NVIDIA GPU
"""

from std.random import seed
from std.time import perf_counter_ns
from std.memory import UnsafePointer

from std.gpu.host import DeviceContext

from mojo_rl.core.dotenv import load_dotenv
from mojo_rl.core.logger import RemoteLogger
from mojo_rl.deep_agents import MBPOAgent, MBPOSACAgent
from mojo_rl.deep_agents.core.configs.mbpo_config import DefaultMBPOConfig
from mojo_rl.deep_agents.core.strategies.termination import NeverTerminate
from mojo_rl.envs.humanoid import Humanoid


# =============================================================================
# Constants
# =============================================================================

# Humanoid: 45D observation, 17D continuous action
comptime OBS_DIM = 45  # qpos[2:24] + qvel[0:23]
comptime ACTION_DIM = 17  # 17 motors for all joints

# SAC network architecture
comptime HIDDEN_DIM = 256

# Buffer sizes
comptime BUFFER_CAPACITY = 1_000_000  # Real buffer
comptime SYNTH_CAPACITY = 400_000  # Synthetic buffer
comptime BATCH_SIZE = 128

# Dynamics ensemble
comptime NUM_ENSEMBLE = 7
comptime NUM_ELITES = 5
comptime DYN_HIDDEN = 200

# Training duration (Humanoid needs many steps due to high dimensionality)
comptime NUM_STEPS = 1_000_000
comptime WARMUP_STEPS = 10_000

comptime dtype = DType.float32

# MBPO config — Humanoid uses k=1 rollouts, NeverTerminate (no dedicated
# termination function; codebase convention is to ignore the minor real/synth
# horizon mismatch at k=1).
comptime MBPOHumanoidConfig = DefaultMBPOConfig[
    OBS_DIM,
    ACTION_DIM,
    HIDDEN_DIM,
    BUFFER_CAPACITY,
    SYNTH_CAPACITY,
    BATCH_SIZE,
    NUM_ENSEMBLE,
    NUM_ELITES,
    DYN_HIDDEN,
    0.0003,  # actor_lr
    0.0003,  # critic_lr (MBPO paper; 1e-3 over-shoots at high UTD)
    0.001,  # model_lr
    NeverTerminate,
]


# =============================================================================
# Main
# =============================================================================


def main() raises:
    seed(42)
    print("=" * 70)
    print("MBPO Agent GPU Training on Humanoid")
    print("=" * 70)
    print()

    # =========================================================================
    # Create GPU context and agent
    # =========================================================================

    with DeviceContext() as ctx:
        var agent = MBPOAgent[
            MBPOHumanoidConfig,
            RemoteLogger,
        ](
            gamma=0.99,
            tau=0.005,
            action_scale=0.4,  # match SAC Humanoid setup
            alpha=0.2,
            auto_alpha=True,
            alpha_lr=0.0003,
            target_entropy=-17.0,  # -ACTION_DIM
            model_train_freq=250,
            rollout_min_length=1,
            rollout_max_length=1,  # Humanoid is high-D; k=1 is more robust
            rollout_min_epoch=20,
            rollout_max_epoch=300,
            num_rollouts_per_step=100_000,
            real_ratio=0.05,
            sac_updates_per_step=20,  # n_train_repeat=20 for Humanoid
            checkpoint_every=100_000,
            checkpoint_path="mbpo_humanoid.ckpt",
            diag_every=500,  # log critic_loss, mean_q, mean_target, ... every 500 SAC updates
        )

        print("Environment: Humanoid Continuous (GPU)")
        print("Agent: MBPO (Model-Based Policy Optimization)")
        print("  Observation dim: " + String(OBS_DIM))
        print("  Action dim: " + String(ACTION_DIM))
        print("  SAC hidden dim: " + String(HIDDEN_DIM))
        print("  Dynamics hidden dim: " + String(DYN_HIDDEN))
        print("  Buffer capacity (real): " + String(BUFFER_CAPACITY))
        print("  Buffer capacity (synth): " + String(SYNTH_CAPACITY))
        print("  Batch size: " + String(BATCH_SIZE))
        print(
            "  Ensemble: "
            + String(NUM_ENSEMBLE)
            + " models, "
            + String(NUM_ELITES)
            + " elites"
        )
        print("  Key hyperparameters:")
        print("    - Actor LR: 3e-4")
        print("    - Critic LR: 3e-4")
        print("    - Model LR: 1e-3")
        print("    - Alpha LR: 3e-4 (auto-tuned)")
        print("    - Action scale: 0.4")
        print("    - Tau: 0.005")
        print("    - Model train freq: 250 steps")
        print("    - Rollout length: 1 (Humanoid)")
        print("    - Real ratio: 0.05 (95% synthetic)")
        print("    - SAC updates per step: 20")
        print("    - Termination: NeverTerminate")
        print("    - Warmup steps: " + String(WARMUP_STEPS))
        print()

        # =====================================================================
        # Setup logger
        # =====================================================================

        var env_vars = load_dotenv()
        var api_key = env_vars.get("RL_MONITOR_API_KEY", "")
        var url = env_vars.get("RL_MONITOR_URL", "")

        var logger = RemoteLogger(
            server_url=url,
            run_name="MBPO Humanoid GPU",
            buffer_size=64,
            api_key=api_key,
        )
        logger.set_config("agent", "MBPO")
        logger.set_config("env", "Humanoid")
        logger.set_config("hidden_dim", String(HIDDEN_DIM))
        logger.set_config("dyn_hidden", String(DYN_HIDDEN))
        logger.set_config("ensemble_size", String(NUM_ENSEMBLE))
        logger.set_config("actor_lr", "3e-4")
        logger.set_config("critic_lr", "3e-4")
        logger.set_config("model_lr", "1e-3")
        logger.set_config("batch_size", String(BATCH_SIZE))
        logger.set_config("model_train_freq", "250")
        logger.set_config("rollout_length", "1")
        logger.set_config("real_ratio", "0.05")
        logger.set_config("sac_updates_per_step", "20")

        # =====================================================================
        # Train
        # =====================================================================

        print("Starting GPU training...")
        print("-" * 70)

        var start_time = perf_counter_ns()

        try:
            var metrics = agent.train_gpu[
                Humanoid[dtype, TERMINATE_ON_UNHEALTHY=True],
                USE_CUDA_GRAPH=False,
            ](
                ctx,
                num_steps=NUM_STEPS,
                warmup_steps=WARMUP_STEPS,
                verbose=True,
                print_every=10_000,
                environment_name="Humanoid",
                logger=UnsafePointer(to=logger),
            )

            var end_time = perf_counter_ns()
            var elapsed_s = Float64(end_time - start_time) / 1e9

            logger.close()

            print("-" * 70)
            print()

            # =================================================================
            # Summary
            # =================================================================

            print("=" * 70)
            print("MBPO GPU Training Complete")
            print("=" * 70)
            print()
            print("Total steps: " + String(NUM_STEPS))
            print("Training time: " + String(elapsed_s)[byte=:6] + " seconds")
            print()

            print(
                "Final average reward (last 100 episodes): "
                + String(metrics.mean_reward_last_n(100))[byte=:8]
            )
            print(
                "Best episode reward: " + String(metrics.max_reward())[byte=:8]
            )
            print()

            var final_avg = metrics.mean_reward_last_n(100)
            if final_avg > 5000.0:
                print("EXCELLENT: Humanoid is running! (avg reward > 5000)")
            elif final_avg > 2000.0:
                print("SUCCESS: Humanoid learned to walk! (avg reward > 2000)")
            elif final_avg > 500.0:
                print(
                    "GOOD PROGRESS: Humanoid is learning locomotion"
                    " (avg reward > 500)"
                )
            elif final_avg > 0.0:
                print(
                    "LEARNING: Agent improving but needs more training"
                    " (avg reward > 0)"
                )
            else:
                print("EARLY STAGE: Agent still exploring (avg reward < 0)")

            print()
            print("=" * 70)

        except e:
            print("!!! EXCEPTION CAUGHT !!!")
            print("Error:", e)
            print("!!! END EXCEPTION !!!")

    print(">>> main() completed normally <<<")
