"""E1 — the Mobius corridor: locally coherent everywhere, globally inconsistent.

A ring of `N` cells. A distant landmark has a fixed direction `w in R^2` in the
universal cover, but is only ever OBSERVED in the local frame, and the frame is
transported by an orthogonal `R_i` as the agent crosses edge `i`. Every `R_i` is
a rotation except one, which carries a reflection: crossing the seam mirrors the
frame. Each transition is perfectly learnable on its own; no global frame exists.

After an ODD number of laps the agent stands in the same cell, sees the same
texture, and sees the landmark MIRRORED. That is perceptual aliasing that no
choice of a single global latent can resolve, and it is the whole experiment.

## Why the nuisance channel exists

The design doc's E1 is `x_i = g_i w` with `g_i in O(2)` and nothing else — the
observation IS an orthogonal group action. Recovering an O(2) structure from
data generated by an O(2) structure would not test hypothesis 4.0, which claims
the topologically relevant part of the state is *separable* from the rest: a
world with no "rest" cannot falsify it (see docs/SWM_IMPLEMENTATION_PLAN.md
§1.2 (a)). So each cell also carries a **nuisance** vector — its texture — that

  - identifies the cell,
  - is IDENTICAL at both lap parities, and
  - is NOT transported by any group action,

and the observation is a fixed linear mixing of landmark and nuisance into a
higher-dimensional space. The encoder therefore has to *find* the two-dimensional
transported subspace rather than be handed it. If a learned encoder cannot,
`det H` will not come out, and hypothesis 4.0 is false as stated. That is the
question Phase 3 asks, and this environment is built so the question is real.

## Ground truth

`true_landmark`, `place_id`, `lap_parity` and `frame` are ORACLES. They exist
for the gates and for the place oracle E1 is entitled to (v2 §4.1); an encoder
under test must never read them.
"""

from std.collections import InlineArray
from std.math import abs, cos, sin, sqrt, tanh

from ..so_d import SqMat
from ..rng import Rng

comptime ACTION_FORWARD: Int = 0
comptime ACTION_BACKWARD: Int = 1


@fieldwise_init
struct MobiusConfig(Copyable, ImplicitlyCopyable, Movable):
    """Knobs of the world. `mobius=False` is the ORIENTABLE control."""

    var mobius: Bool
    var world_seed: UInt64
    var obs_noise: Float64
    var max_turn: Float64
    """Per-edge frame rotation is drawn from [-max_turn, +max_turn]."""
    var obs_gain: Float64
    """Pre-nonlinearity gain. Ignored when `nonlinear_obs` is False."""
    var nonlinear_obs: Bool
    """`obs = tanh(gain * mix @ latent) + noise` instead of a linear mixing.

    A linear mixing leaves the landmark subspace linearly recoverable, so
    hypothesis 4.0's "separable" holds EXACTLY there and P1 is answered under
    the friendliest possible observation model. With the squash, recovering the
    frame requires inverting a nonlinearity that has entangled landmark with
    texture, which is the version of the question worth having an answer to.
    """

    @staticmethod
    def default_mobius(world_seed: UInt64 = 20260904) -> Self:
        return Self(True, world_seed, 0.02, 0.6, 1.0, False)

    @staticmethod
    def default_orientable(world_seed: UInt64 = 20260904) -> Self:
        return Self(False, world_seed, 0.02, 0.6, 1.0, False)

    @staticmethod
    def nonlinear_mobius(
        gain: Float64, world_seed: UInt64 = 20260904
    ) -> Self:
        return Self(True, world_seed, 0.02, 0.6, gain, True)

    @staticmethod
    def nonlinear_orientable(
        gain: Float64, world_seed: UInt64 = 20260904
    ) -> Self:
        return Self(False, world_seed, 0.02, 0.6, gain, True)


struct MobiusRing[
    N_CELLS: Int,
    NUISANCE_DIM: Int,
    OBS_DIM: Int,
    dtype: DType = DType.float64,
](Copyable, Movable):
    """Ring world with a transported landmark and a non-transported texture.

    `OBS_DIM` is deliberately larger than `2 + NUISANCE_DIM`: the observation is
    an overcomplete mixing, so nothing can be read off a coordinate.
    """

    comptime LATENT_DIM: Int = 2 + Self.NUISANCE_DIM
    comptime SEAM_EDGE: Int = Self.N_CELLS - 1

    var cfg: MobiusConfig
    var edge_rot: List[SqMat[2, Self.dtype]]
    """`R_i`: frame transport for the FORWARD crossing of edge i (cell i -> i+1)."""
    var nuisance: List[Scalar[Self.dtype]]
    """`N_CELLS x NUISANCE_DIM`, fixed per cell. Never transported."""
    var mix: List[Scalar[Self.dtype]]
    """`OBS_DIM x LATENT_DIM` fixed mixing. The encoder must invert this."""

    var cell: Int
    var frame: SqMat[2, Self.dtype]
    var w: List[Scalar[Self.dtype]]
    var seam_crossings: Int
    var steps: Int
    var rng: Rng

    def __init__(out self, cfg: MobiusConfig) raises:
        comptime assert Self.N_CELLS >= 3, "a ring needs at least 3 cells"
        comptime assert Self.NUISANCE_DIM >= 1, "the nuisance channel is the point"
        comptime assert (
            Self.OBS_DIM >= Self.LATENT_DIM
        ), "observation must not lose the latent"

        self.cfg = cfg
        var wr = Rng(cfg.world_seed)

        # Per-edge rotations, summing to zero so an ORIENTABLE ring has exactly
        # trivial holonomy: any non-triviality then comes from the seam alone.
        var angles = List[Float64]()
        var total = Float64(0)
        for _ in range(Self.N_CELLS - 1):
            var t = wr.uniform_range(-cfg.max_turn, cfg.max_turn)
            angles.append(t)
            total += t
        angles.append(-total)

        var reflection = SqMat[2, Self.dtype].identity()
        reflection[1, 1] = Scalar[Self.dtype](-1)

        self.edge_rot = List[SqMat[2, Self.dtype]]()
        for i in range(Self.N_CELLS):
            var r = SqMat[2, Self.dtype]()
            r[0, 0] = Scalar[Self.dtype](cos(angles[i]))
            r[0, 1] = Scalar[Self.dtype](-sin(angles[i]))
            r[1, 0] = Scalar[Self.dtype](sin(angles[i]))
            r[1, 1] = Scalar[Self.dtype](cos(angles[i]))
            if cfg.mobius and i == Self.SEAM_EDGE:
                r = reflection * r
            self.edge_rot.append(r)

        # Texture per cell. Well separated so it identifies the cell on its own
        # — a realistic place cue, and it makes the aliasing sharp: the texture
        # says "same cell" while the landmark says "mirrored".
        self.nuisance = List[Scalar[Self.dtype]](
            length=Self.N_CELLS * Self.NUISANCE_DIM, fill=0
        )
        for c in range(Self.N_CELLS):
            for k in range(Self.NUISANCE_DIM):
                self.nuisance[c * Self.NUISANCE_DIM + k] = Scalar[Self.dtype](
                    wr.uniform_range(-1.0, 1.0)
                )

        # Overcomplete mixing. Entries are bounded away from zero so that EVERY
        # observed coordinate genuinely blends landmark with texture; the gate
        # asserts this rather than trusting it.
        self.mix = List[Scalar[Self.dtype]](
            length=Self.OBS_DIM * Self.LATENT_DIM, fill=0
        )
        for r in range(Self.OBS_DIM):
            for c in range(Self.LATENT_DIM):
                var v = wr.uniform_range(-1.0, 1.0)
                if abs(v) < 0.25:
                    v = 0.25 if v >= 0 else -0.25
                self.mix[r * Self.LATENT_DIM + c] = Scalar[Self.dtype](v)

        self.cell = 0
        self.frame = SqMat[2, Self.dtype].identity()
        self.w = List[Scalar[Self.dtype]](length=2, fill=0)
        self.w[0] = 1
        self.seam_crossings = 0
        self.steps = 0
        self.rng = Rng(cfg.world_seed ^ 0xA5A5_A5A5_A5A5_A5A5)

    def __init__(out self, *, copy: Self):
        self.cfg = copy.cfg
        self.edge_rot = copy.edge_rot.copy()
        self.nuisance = copy.nuisance.copy()
        self.mix = copy.mix.copy()
        self.cell = copy.cell
        self.frame = copy.frame.copy()
        self.w = copy.w.copy()
        self.seam_crossings = copy.seam_crossings
        self.steps = copy.steps
        self.rng = copy.rng

    def __init__(out self, *, deinit move: Self):
        self.cfg = move.cfg
        self.edge_rot = move.edge_rot^
        self.nuisance = move.nuisance^
        self.mix = move.mix^
        self.cell = move.cell
        self.frame = move.frame^
        self.w = move.w^
        self.seam_crossings = move.seam_crossings
        self.steps = move.steps
        self.rng = move.rng

    # -- episode --------------------------------------------------------------

    def reset(mut self, episode_seed: UInt64, start_cell: Int = 0) raises:
        """Fresh landmark direction and frame. The frame starts at identity.

        `w` varies per episode because the per-edge transport has to be
        identifiable from observed pairs; a single fixed direction would leave
        the fit rank-deficient.
        """
        if start_cell < 0 or start_cell >= Self.N_CELLS:
            raise Error("reset: start_cell out of range")
        self.rng = Rng(episode_seed)
        var a = self.rng.uniform_range(0.0, 6.283185307179586)
        self.w[0] = Scalar[Self.dtype](cos(a))
        self.w[1] = Scalar[Self.dtype](sin(a))
        self.cell = start_cell
        self.frame = SqMat[2, Self.dtype].identity()
        self.seam_crossings = 0
        self.steps = 0

    def step(mut self, action: Int) raises:
        """Move one cell. Forward across edge `cell` applies `R_cell`;
        backward across edge `cell-1` applies `R_{cell-1}^T`."""
        if action == ACTION_FORWARD:
            var e = self.cell
            self.frame = self.edge_rot[e] * self.frame
            self.cell = (self.cell + 1) % Self.N_CELLS
            if e == Self.SEAM_EDGE:
                self.seam_crossings += 1
        elif action == ACTION_BACKWARD:
            var e = (self.cell - 1 + Self.N_CELLS) % Self.N_CELLS
            self.frame = self.edge_rot[e].transpose() * self.frame
            self.cell = e
            if e == Self.SEAM_EDGE:
                self.seam_crossings += 1
        else:
            raise Error("step: action must be 0 (forward) or 1 (backward)")
        self.steps += 1

    # -- what the agent sees --------------------------------------------------

    def observation(mut self) -> List[Scalar[Self.dtype]]:
        """`mix @ [frame w ; nuisance_cell] + noise`, of size `OBS_DIM`.

        Landmark and texture are blended into every coordinate, so the frame
        subspace has to be learned. `noise` is drawn from the episode stream, so
        two calls differ: an observation is a measurement, not a lookup.
        """
        var latent = List[Scalar[Self.dtype]](length=Self.LATENT_DIM, fill=0)
        var lm = self.true_landmark()
        latent[0] = lm[0]
        latent[1] = lm[1]
        for k in range(Self.NUISANCE_DIM):
            latent[2 + k] = self.nuisance[self.cell * Self.NUISANCE_DIM + k]

        var obs = List[Scalar[Self.dtype]](length=Self.OBS_DIM, fill=0)
        for r in range(Self.OBS_DIM):
            var s = Scalar[Self.dtype](0)
            for c in range(Self.LATENT_DIM):
                s += self.mix[r * Self.LATENT_DIM + c] * latent[c]
            if self.cfg.nonlinear_obs:
                s = Scalar[Self.dtype](
                    tanh(self.cfg.obs_gain * Float64(s))
                )
            obs[r] = s + Scalar[Self.dtype](
                self.rng.normal() * self.cfg.obs_noise
            )
        return obs^

    def frame_at(self, cell: Int, parity: Int) -> SqMat[2, Self.dtype]:
        """The frame reached by walking forward `cell` steps, `parity` laps in.

        On a Mobius ring there are `2 * N_CELLS` distinct frames, not `N_CELLS`:
        that doubling IS the double cover, and it is what a Clone-Structured
        Cognitive Graph has to discover by EM.
        """
        var f = SqMat[2, Self.dtype].identity()
        var laps = parity % 2
        for _ in range(laps):
            for i in range(Self.N_CELLS):
                f = self.edge_rot[i] * f
        for i in range(cell):
            f = self.edge_rot[i] * f
        return f^

    def _left_alignment(self, cell: Int, parity: Int) -> Float64:
        """`cos` between the locally observed landmark and "left" (+y)."""
        var f = self.frame_at(cell, parity)
        var x = Float64(f[0, 0] * self.w[0] + f[0, 1] * self.w[1])
        var y = Float64(f[1, 0] * self.w[0] + f[1, 1] * self.w[1])
        var n = sqrt(x * x + y * y)
        if n < 1e-12:
            return -2.0
        return y / n

    def goal_cell(self) -> Int:
        """Cell of the unique state where the landmark appears most to the LEFT."""
        return self._argmax_frame() // 2

    def goal_parity(self) -> Int:
        return self._argmax_frame() % 2

    def _argmax_frame(self) -> Int:
        """Index `2*cell + parity` of the best-aligned frame, over ALL 2N.

        Defined as an argmax rather than a fixed cell with a tolerance: the
        landmark direction is redrawn each episode, so a tolerance-based goal
        is satisfiable for some episodes and not others, which would make the
        task ill-posed rather than merely hard. (Measured: an earlier
        tolerance-based reward was parity-dependent only ~45% of episodes.)
        An argmax always exists and is generically unique.
        """
        var best = -3.0
        var best_idx = 0
        for cell in range(Self.N_CELLS):
            for parity in range(2):
                var a = self._left_alignment(cell, parity)
                if a > best:
                    best = a
                    best_idx = cell * 2 + parity
        return best_idx

    def goal_margin(self) -> Float64:
        """Gap between the best and second-best frame — degeneracy check."""
        var best = -3.0
        var second = -3.0
        for cell in range(Self.N_CELLS):
            for parity in range(2):
                var a = self._left_alignment(cell, parity)
                if a > best:
                    second = best
                    best = a
                elif a > second:
                    second = a
        return best - second

    def reward(self) -> Float64:
        """1 in the single state showing the landmark furthest to the LEFT.

        Parity-dependent by construction: the goal is a (cell, PARITY) pair, so
        standing in the right cell is not enough — the agent has to have crossed
        the seam the right number of times. It cannot know which cell that is
        without a model that carries the parity, which is exactly what E1 is
        asking of a world model.
        """
        if self.cell != self.goal_cell():
            return 0.0
        if self.lap_parity() != self.goal_parity():
            return 0.0
        return 1.0

    # -- oracles: GATES ONLY, never visible to an encoder ---------------------

    def true_landmark(self) -> InlineArray[Scalar[Self.dtype], 2]:
        """`frame @ w` — the transported part, unmixed and noiseless."""
        var out = InlineArray[Scalar[Self.dtype], 2](fill=0)
        for i in range(2):
            var s = Scalar[Self.dtype](0)
            for j in range(2):
                s += self.frame[i, j] * self.w[j]
            out[i] = s
        return out^

    def place_id(self) -> Int:
        """Oracle place identity (v2 §4.1). Learned recognition is a later phase."""
        return self.cell

    def lap_parity(self) -> Int:
        return self.seam_crossings % 2

    def nuisance_at(self, cell: Int) -> List[Scalar[Self.dtype]]:
        var out = List[Scalar[Self.dtype]](length=Self.NUISANCE_DIM, fill=0)
        for k in range(Self.NUISANCE_DIM):
            out[k] = self.nuisance[cell * Self.NUISANCE_DIM + k]
        return out^

    def edge_transport(self, edge: Int) -> SqMat[2, Self.dtype]:
        return self.edge_rot[edge].copy()
